import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'primeros-auxilios',
  title: 'Primeros Auxilios a Bordo',
  readingTime: 18,

  content: [
    { type: 'title', text: 'Aspectos Sanitarios: Primeros Auxilios' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'paragraph', text: 'Los primeros auxilios son grupos de técnicas destinadas a resolver la atención inmediata de aquellas personas que hayan sufrido alguna lesión o estén afectadas por alguna enfermedad, con el fin de estabilizarlas hasta el momento de su llegada a un sitio de tratamiento específico.' },
    { type: 'paragraph', text: 'En el contexto de este manual explicaremos aquellas técnicas de primeros auxilios que eventualmente pueda ser necesario aplicar abordo de una embarcación, y los procedimientos para solicitar ayuda y mantener estable a la víctima hasta el momento de llegar a puerto o de su evacuación.' },
    { type: 'subtitle', text: 'Primeros Auxilios.' },
    { type: 'paragraph', text: 'Relevamiento de Salud Previo a la Zarpada' },
    { type: 'paragraph', text: 'En travesías de media y larga distancia, es recomendable que el Capitán realice previamente un relevamiento básico de la condición de salud de cada tripulante y pasajero. Este procedimiento tiene por objeto anticipar posibles emergencias y permitir dar una respuesta más rápida y adecuada ante una eventual situación de salud a bordo.' },
    { type: 'paragraph', text: 'Conocer de antemano las condiciones médicas preexistentes de las personas embarcadas resulta especialmente importante en el ámbito de la náutica recreativa y deportiva, donde el acceso inmediato a asistencia médica ante una emergencia puede ser limitado y las decisiones deben tomarse con información precisa.' },
    { type: 'paragraph', text: 'Como mínimo, el Capitán debería relevar y registrar los siguientes datos:' },
    { type: 'paragraph', text: 'Enfermedades crónicas o condiciones médicas relevantes.' },
    { type: 'paragraph', text: 'Medicamentos de uso habitual.' },
    { type: 'subtitle', text: 'Elementos médicos personales.' },
    { type: 'paragraph', text: 'Tales como glucómetro, inhaladores o nebulizadores, o auto-inyector de adrenalina, entre otros.' },
    { type: 'paragraph', text: 'Restricciones o recomendaciones médicas.' },
    { type: 'paragraph', text: 'Como, por ejemplo, limitaciones para el esfuerzo físico, exposición al sol o consumo de alcohol, o dificultades visuales.' },
    { type: 'paragraph', text: 'Contactos.' },
    { type: 'paragraph', text: 'Datos de contacto del personal médico o profesional que atiende la condición de salud informada o, en todo caso, de familiares que puedan prestar ayuda o información cuando sea requerida.' },
    { type: 'paragraph', text: 'Es importante que esta información esté disponible a bordo en un lugar accesible para el Capitán y, de ser posible, para un segundo responsable, manteniendo siempre la confidencialidad de los datos cuando la persona que ha brindado la información así lo haya solicitado.' },
    { type: 'paragraph', text: 'Este relevamiento permite, en caso de emergencia, reconocer más rápidamente el cuadro clínico, aplicar medidas iniciales adecuadas y brindar información precisa durante una consulta médica por radio o ante la intervención del servicio guardacostas.' },
    { type: 'paragraph', text: 'La prevención y la anticipación son herramientas fundamentales de la seguridad náutica, y forman parte de las responsabilidades del Capitán en la conducción de una embarcación recreativa o deportiva.' },
    { type: 'paragraph', text: 'Tratamiento de las Emergencias' },
    { type: 'paragraph', text: 'Veremos ahora como actuar en caso de declararse una emergencia abordo, producto de un accidente o relacionada a una condición de salud.' },
    { type: 'paragraph', text: 'Si bien en la correlatividad de los temas de este manual aún no se ha hablado de las comunicaciones por radio y los mensajes de urgencia, emergencia y seguridad, creo que es útil explicar lo siguiente:' },
    { type: 'paragraph', text: 'El mensaje de llamada MAYDAY se utiliza específicamente cuando existe un peligro grave e inminente para la vida humana.' },
    { type: 'paragraph', text: 'Cuando la situación médica reviste urgencia, pero el paciente se encuentra estable y no existe un peligro inmediato para la vida, corresponde utilizar el mensaje PAN-PAN, solicitando asistencia o consejo médico sin declarar una situación de socorro.' },
    { type: 'paragraph', text: 'Ante la duda sobre la gravedad del cuadro, debe priorizarse siempre la seguridad de las personas a bordo, optando por el nivel de comunicación que garantice una respuesta rápida y eficaz por parte de los servicios guardacostas.' },
    { type: 'paragraph', text: 'Valoración de la Emergencia' },
    { type: 'paragraph', text: 'El primer paso ante una emergencia es realizar una rápida composición de lugar, asumir el control de la situación y transmitir tranquilidad tanto a la víctima como a las personas que lo rodean.' },
    { type: 'paragraph', text: 'Aprecie inicialmente el entorno, identificando los riesgos que pudiesen comprometer su propia seguridad. En la medida de lo posible, procure generar un ámbito de trabajo seguro, en el cual pueda operar sin otra preocupación que la atención de la emergencia. Una vez logrado esto, considere la situación del accidentado o enfermo, procurando que no agrave su estado ni se generen nuevas víctimas.' },
    { type: 'paragraph', text: 'Finalmente, evalúe el estado de la víctima y determine, en función de su condición, si puede ser atendida a bordo o si resulta necesario su traslado urgente.' },
    { type: 'paragraph', text: 'Si bien lo que el autor acaba de explicar parece mucho para hacer, en la práctica ocurre todo realmente muy rápido, resolviéndose en pocos segundos... menos de los que le ha llevado leer ese texto.' },
    { type: 'paragraph', text: 'Lo primero, en cuanto a apreciar la situación, es para determinar si existe alguna causa por la cual la víctima esté en esa condición, y evitar que eso nos suceda a nosotros. Esto se resuelve en dos segundos.' },
    { type: 'paragraph', text: 'Aclarado eso, entonces sí debemos poner manos a la obra con la víctima.' },
    { type: 'paragraph', text: 'Procedimiento para Solicitar Asistencia Médica por Radio' },
    { type: 'subtitle', text: 'Emergencia médica abordo.' },
    { type: 'paragraph', text: 'La Prefectura Naval Argentina, al igual que los servicios guardacostas de gran parte del mundo, brinda asistencia médica por radio a las embarcaciones que la soliciten, orientando a los navegantes sobre cómo actuar ante una emergencia sanitaria a bordo.' },
    { type: 'paragraph', text: 'En la República Argentina, la solicitud de asistencia médica se realiza por radio, modulando en el canal 16 de VHF, o bien telefónicamente llamando al número 106. Este servicio opera las 24 horas del día, todos los días del año.' },
    { type: 'paragraph', text: 'Ante una emergencia sanitaria o un accidente ocurrido a bordo, no dude en solicitar asistencia médica ante la menor duda de poder manejar la situación.' },
    { type: 'paragraph', text: 'Obviamente, si el paciente tiene algún seguro de salud o médico de cabecera, también deberá ser involucrado en la situación, comunicándose telefónicamente o por los medios que se hayan previsto.' },
    { type: 'paragraph', text: 'Mas allá de eso, este texto se limitará solo al proceso de asistencia y coordinación de la evacuación, si fuera necesaria, con la autoridad marítima.' },
    { type: 'paragraph', text: 'Al iniciar la comunicación, mantenga la calma, hable con claridad y sea lo más preciso posible. Tenga a mano papel y lápiz para anotar las indicaciones que se le brinden durante la consulta.' },
    { type: 'paragraph', text: 'En un procedimiento estándar, los operadores y médicos solicitarán los siguientes datos:' },
    { type: 'paragraph', text: 'Filiación del Paciente.' },
    { type: 'paragraph', text: 'Pedirán el nombre y apellido, sexo, edad, número de documento, lugar y fecha de nacimiento.' },
    { type: 'paragraph', text: 'Situación del Barco.' },
    { type: 'paragraph', text: 'Posición actual si se encuentra navegando, indicando rumbo, velocidad y distancia al puerto más cercano.' },
    { type: 'paragraph', text: 'Si la embarcación se encuentra fondeada o amarrada, indique la zona o puerto en el que se encuentra.' },
    { type: 'paragraph', text: 'Motivo de la Consulta.' },
    { type: 'paragraph', text: 'Lámina de situación de síntomas.' },
    { type: 'paragraph', text: 'En caso de tratar de una aparente enfermedad, señale cómo comenzó el cuadro, cuál fue el primer síntoma y desde cuándo se manifiestan.' },
    { type: 'paragraph', text: 'Describa las molestias o signos actuales e indique si el paciente ha tenido episodios similares con anterioridad.' },
    { type: 'paragraph', text: 'Informe también la presencia de otros signos asociados, yales como vómitos, tos, expectoración, diarrea, pus o sangre. Aporte su apreciación sobre posibles causas, como la ingesta de alimentos o bebidas, o la realización de alguna actividad física previa.' },
    { type: 'paragraph', text: 'Algunos servicios médicos de los guardacostas suelen utilizar láminas anatómicas de referencia para identificar la zona afectada. Es recomendable contar con una copia a bordo para facilitar una descripción objetiva.' },
    { type: 'paragraph', text: 'En caso de accidente, indique cómo ocurrió, en qué lugar de la embarcación y cuánto tiempo ha transcurrido desde entonces. Describa la lesión, precisando si se trata de quemaduras, hemorragias, fracturas, contusiones o heridas.' },
    { type: 'paragraph', text: 'Señale la zona afectada, el tamaño y profundidad de la lesión, y si existe alteración del movimiento, pérdida de sensibilidad o disminución de la fuerza.' },
    { type: 'paragraph', text: 'Informe también la presencia de síntomas asociados, como dolor intenso, pérdida de conciencia o dificultad respiratoria.' },
    { type: 'subtitle', text: 'Botiquín.' },
    { type: 'paragraph', text: 'Seguramente durante la consulta se le preguntará qué elementos contiene el botiquín de primeros auxilios de la embarcación, por lo que resulta conveniente tenerlo a mano.' },
    { type: 'paragraph', text: 'El personal médico o los operadores del servicio pueden establecer horarios para futuras comunicaciones o impartir instrucciones para una eventual evacuación de emergencia. Tome nota de ellas y trate de seguirlas como se le han indicado.' },
    { type: 'paragraph', text: 'Una vez finalizada la primera comunicación, intente seguir estrictamente las indicaciones impartidas por los operadores y el personal médico del servicio guardacostas, tanto en la aplicación de las medidas recomendadas como en la realización de comunicaciones de control, el desplazamiento hacia un puerto determinado o la preparación para una evacuación de emergencia.' },
    { type: 'paragraph', text: 'El Traslado' },
    { type: 'paragraph', text: 'Desde el punto de vista conceptual, el traslado del paciente consiste en llevarlo, a la mayor brevedad posible, a un lugar donde pueda recibir atención médica especializada.' },
    { type: 'paragraph', text: 'La decisión de trasladar a una persona corresponde, en primera instancia, al capitán de la embarcación, o puede surgir como recomendación del médico durante la consulta radial. En el primer caso, será el capitán quien determine el puerto más adecuado al cual dirigirse para efectuar el desembarco del paciente.' },
    { type: 'paragraph', text: 'Traslado de emergencia.' },
    { type: 'paragraph', text: 'Cuando la gravedad de la emergencia lo justifique, el capitán deberá coordinar, durante la navegación, la disponibilidad en el puerto de una ambulancia o de los medios necesarios para continuar la asistencia y el traslado inmediato del paciente una vez arribada la embarcación.' },
    { type: 'paragraph', text: 'En situaciones de extrema urgencia, la autoridad marítima podrá disponer la evacuación aeromédica mediante helicóptero o embarcación rápida. En tal caso, se impartirán las instrucciones necesarias para preparar la embarcación y al paciente para dicha evacuación.' },
    { type: 'paragraph', text: 'Diagnósticos de Urgencia' },
    { type: 'paragraph', text: 'Abordaremos ahora la tarea de realizar un diagnóstico de urgencia, comenzando por la exploración física del paciente, cuyo objetivo es evaluar su estado general y determinar los principales parámetros vitales.' },
    { type: 'paragraph', text: 'A partir de esta valoración inicial, analizaremos  luego de forma específica las distintas situaciones de emergencia médica y accidentes más frecuentes, identificando sus principales síntomas.' },
    { type: 'paragraph', text: 'Exploración Física' },
    { type: 'paragraph', text: 'Ante una emergencia médica, una de las primeras acciones será evaluar el estado general del paciente. Para ello, intente responder a las siguientes preguntas:' },
    { type: 'paragraph', text: '¿Qué aspecto tiene?' },
    { type: 'paragraph', text: '¿Qué postura adopta?' },
    { type: 'paragraph', text: 'Verifique si está agitado, inmóvil, encogido, recostado sobre un lado o si adopta alguna posición inusual.' },
    { type: 'paragraph', text: '¿Qué grado de conciencia presenta?' },
    { type: 'paragraph', text: 'Evalúe si reconoce dónde se encuentra y qué le ha ocurrido, o si está desorientado.' },
    { type: 'paragraph', text: 'Esta información será de utilidad al momento de responder las preguntas que le formule el médico durante la consulta por radio.' },
    { type: 'paragraph', text: 'Dependiendo del tipo de lesión o enfermedad, y siempre que sea posible, deberá tomar los signos vitales del paciente en situación de reposo, siguiendo las recomendaciones que se detallan a continuación.' },
    { type: 'paragraph', text: 'Pulso' },
    { type: 'paragraph', text: 'Pulso.' },
    { type: 'paragraph', text: 'El pulso se toma habitualmente en la cara palmar de la muñeca, sobre la arteria radial, aplicando las yemas de los dedos índice y mayor hacia la base del pulgar del paciente. También puede tomarse en una de las arterias carótidas, ubicadas a ambos lados del cuello, a la altura de la nuez.' },
    { type: 'paragraph', text: 'Una vez localizado el pulso, se deben contar las pulsaciones durante un minuto. En situaciones de urgencia, puede contarse durante diez segundos y multiplicar el resultado por seis.' },
    { type: 'paragraph', text: 'Los valores normales en reposo son:' },
    { type: 'paragraph', text: 'Infantes (hasta 2 años): 80 a 160 pulsaciones por minuto.' },
    { type: 'paragraph', text: 'Niños (2 a 12 años): 80 a 100 pulsaciones por minuto.' },
    { type: 'paragraph', text: 'Adolescentes: 70 a 90 pulsaciones por minuto.' },
    { type: 'paragraph', text: 'Adultos: 60 a 80 pulsaciones por minuto.' },
    { type: 'paragraph', text: 'Adultos mayores: 60 o menos pulsaciones por minuto.' },
    { type: 'paragraph', text: 'Estos valores pueden variar en personas afectadas por una enfermedad o un accidente. Una frecuencia cardíaca por encima de los valores normales se denomina taquicardia, y por debajo de ellos, bradicardia.' },
    { type: 'paragraph', text: 'Temperatura.' },
    { type: 'paragraph', text: 'Temperatura.' },
    { type: 'paragraph', text: 'La temperatura corporal debe medirse con un termómetro, colocándolo preferentemente en el hueco de la axila, con el extremo sensor en contacto directo con la piel, manteniéndolo en esa posición durante aproximadamente cinco minutos. También puede colocarse debajo de la lengua o en la ingle.' },
    { type: 'paragraph', text: 'La temperatura corporal normal oscila entre 36,5ºC y 37,0ºC.' },
    { type: 'paragraph', text: 'Frecuencia Respiratoria.' },
    { type: 'paragraph', text: 'Frecuencia respiratoria.' },
    { type: 'paragraph', text: 'La frecuencia respiratoria se determina contando el número de respiraciones por minuto, considerando una respiración como el ciclo completo de una inspiración seguida de una espiración.' },
    { type: 'paragraph', text: 'Para ello, observe el movimiento de ascenso y descenso del tórax, o coloque la palma de la mano sobre las últimas costillas y cuente cuántas veces ascienden y descienden con la respiración.' },
    { type: 'paragraph', text: 'Además del número de respiraciones, observe el ritmo, indicando si es regular o irregular, y la amplitud, determinando si la respiración es superficial o profunda.' },
    { type: 'paragraph', text: 'A modo de referencia, estos son los valores normales de frecuencia respiratoria medidos en reposo:' },
    { type: 'paragraph', text: 'Infantes (hasta 2 años): 24 a 40 respiraciones por minuto.' },
    { type: 'paragraph', text: 'Niños (2 a 12 años): 18 a 30 respiraciones por minuto.' },
    { type: 'paragraph', text: 'Adolescentes: 12 a 20 respiraciones por minuto.' },
    { type: 'paragraph', text: 'Adultos: 12 a 20 respiraciones por minuto.' },
    { type: 'paragraph', text: 'Adultos mayores: 12 a 18 respiraciones por minuto.' },
    { type: 'paragraph', text: 'Presión Arterial' },
    { type: 'paragraph', text: 'Raramente se dispone de un tensiómetro en el botiquín de una embarcación deportiva o de recreo. No obstante, si cuenta con uno, podrá medir la presión arterial del paciente.' },
    { type: 'paragraph', text: 'La presión arterial se expresa mediante dos valores:' },
    { type: 'paragraph', text: 'Presión máxima, correspondiente a la sístole.' },
    { type: 'paragraph', text: 'Presión mínima, correspondiente a la diástole.' },
    { type: 'paragraph', text: 'Los tensiómetros manuales requieren algo más de trabajo. Esos equipos constan de un manómetro y una pera neumática para inflar la faja de compresión que se coloca alrededor del brazo. Además, se utiliza un estetoscopio para escuchar los sonidos producidos por el paso de la sangre a través de la arteria durante la medición.' },
    { type: 'paragraph', text: 'La presión se toma generalmente en el brazo izquierdo, a la altura del pliegue anterior del codo, donde pasa la arteria humeral. El paciente debe encontrarse recostado o sentado, en reposo, con el brazo extendido, apoyado y relajado, y en lo posible en silencio.' },
    { type: 'paragraph', text: 'Tensiómetro y presión arterial.' },
    { type: 'paragraph', text: 'Una vez tomada la presión arterial, compárela con la que el paciente informe como sus valores típicos de presión.' },
    { type: 'paragraph', text: 'Mas allá de esto, y a modo de referencia, estos son los valores de presión normales, medidos en reposo, expresados en mmHg y se indican como "presión sistólica / presión diastólica".' },
    { type: 'paragraph', text: 'Adultos óptima: 120 / normal: 120–129 / 80–84 mmHg' },
    { type: 'paragraph', text: 'normal alta: 130–139 / 85–89 mmHg' },
    { type: 'paragraph', text: 'Adultos mayores: Los valores pueden ser ligeramente más elevados que los de la categoría "Adultos" sin que ello implique necesariamente una patología.' },
    { type: 'paragraph', text: 'En general, se aceptan cifras hasta 140/90 mmHg como límite superior de normalidad, siempre que la persona se encuentre asintomática.' },
    { type: 'paragraph', text: 'Glucemia' },
    { type: 'paragraph', text: 'Siempre que el paciente esté consciente, lúcido y pueda colaborar, es conveniente solicitarle que realice la medición por sí mismo. El valor obtenido debe anotarse junto con la fecha y hora de la medición, para tener trazabilidad de la información.' },
    { type: 'paragraph', text: 'Los valores de referencia habituales son los siguientes:' },
    { type: 'paragraph', text: 'En ayunas: 70 a 100 mg/dL.' },
    { type: 'paragraph', text: 'Luego de las comidas (aprox. 2 horas): Hasta 140 mg/dL.' },
    { type: 'paragraph', text: 'En diabéticos, estos valores pueden variar sensiblemente.' },
    { type: 'paragraph', text: 'Veremos ahora los síntomas de los principales eventos de salud y relacionados a accidentes que pueden ocurrir abordo de una embarcación.' },
    { type: 'paragraph', text: 'Estado de Shock' },
    { type: 'paragraph', text: 'En el ámbito de la náutica recreativa y deportiva, el shock puede aparecer tras caídas a bordo, golpes contra elementos de la embarcación, cortes profundos, quemaduras por fuego o combustibles, o luego de una reacción alérgica a picaduras o medicamentos.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse un estado de shock cuando el paciente presenta uno o más de los siguientes signos: hemorragias importantes, dolor agudo, piel pálida y fría con sudoración, pulso débil y acelerado, presión arterial baja, inquietud o ansiedad marcada, sed intensa, confusión mental o pérdida de la conciencia.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Ante esta situación, si el paciente se encuentra consciente, tranquilícelo, manténgalo abrigado y recuéstelo.' },
    { type: 'paragraph', text: 'Si no existen sospechas de traumatismos en la cabeza, el abdomen o las piernas, ni indicios de un ataque cardíaco, puede elevarle las piernas aproximadamente 40 centímetros, para favorecer el retorno de sangre hacia los órganos vitales. Luego, intente identificar la causa que originó el shock.' },
    { type: 'paragraph', text: 'Mientras esto ocurre, solicite asistencia médica por radio de inmediato y prepare la embarcación para un eventual traslado o evacuación, siguiendo las instrucciones del servicio guardacostas.' },
    { type: 'paragraph', text: 'Si el paciente se encuentra inconsciente, deberá tratarlo conforme a los procedimientos correspondientes a ese cuadro, priorizando el control de la vía aérea, la respiración y la circulación, y solicitando ayuda médica urgente.' },
    { type: 'paragraph', text: 'Reacción Alérgica Grave' },
    { type: 'paragraph', text: 'Reacción alérgica.' },
    { type: 'paragraph', text: 'Una reacción alérgica grave se produce cuando el organismo responde de forma exagerada ante una sustancia a la que la persona es sensible. Puede presentarse tras la ingesta de medicamentos o alimentos, el contacto con productos químicos, o por picaduras de insectos o animales marinos. Es más probable en personas con antecedentes alérgicos conocidos.' },
    { type: 'paragraph', text: 'En el ámbito de la náutica recreativa y deportiva, este cuadro puede aparecer luego del contacto con combustibles, solventes o productos de limpieza a bordo, por picaduras de insectos, medusas u otros organismos marinos, o tras la administración de medicamentos sin prescripción médica.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse una reacción alérgica grave cuando el paciente presenta uno o más de los siguientes signos: enrojecimiento de la piel, picazón intensa, sensación de ardor o quemazón, aparición de sarpullido o ronchas, hinchazón de labios, párpados, cara, lengua o garganta, dificultad para respirar o respiración ruidosa, sensación de opresión en el pecho.' },
    { type: 'paragraph', text: 'Esto puede estar asociado a mareos, confusión o pérdida de la conciencia en el peor de los casos.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Ante la sospecha de una reacción alérgica grave, tranquilice al paciente e interrumpa el contacto con el agente causante si ha podido identificarlo y si es posible hacerlo de forma segura.' },
    { type: 'paragraph', text: 'Coloque al paciente en una posición cómoda, preferentemente semisentado si presenta dificultad respiratoria. Afloje la ropa ajustada y manténgalo abrigado.' },
    { type: 'subtitle', text: 'Controle de manera continua la respiración y el nivel de conciencia.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio de inmediato.' },
    { type: 'paragraph', text: 'No administre medicamentos salvo indicación expresa del médico durante la consulta radial.' },
    { type: 'paragraph', text: 'Prepare la embarcación para un posible traslado o evacuación de emergencia, siguiendo estrictamente las instrucciones del servicio guardacostas.' },
    { type: 'paragraph', text: 'Ataque Cardíaco' },
    { type: 'paragraph', text: 'Ataque cardíaco.' },
    { type: 'paragraph', text: 'La expresión “ataque cardíaco” se utiliza de manera general para describir cualquier evento cardíaco súbito y grave. Para quienes no están especializados en la materia, este término puede abarcar situaciones como un infarto agudo de miocardio, un paro cardíaco, una angina de pecho grave, una arritmia severa o una insuficiencia cardíaca.' },
    { type: 'paragraph', text: 'Un ataque cardíaco puede estar ocurriendo cuando una persona presenta un dolor u opresión intensa en el centro del pecho, que puede irradiarse hacia uno o ambos hombros, el cuello, la mandíbula o los brazos. Este cuadro puede acompañarse de aturdimiento general, dificultad para respirar, náuseas y sudoración profusa.' },
    { type: 'paragraph', text: 'En el ámbito de la náutica recreativa y deportiva, los esfuerzos físicos, el estrés, el frío o el calor extremos y la demora en el acceso a atención médica pueden agravar rápidamente este tipo de emergencia.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse un ataque cardíaco cuando el paciente presenta dolor u opresión torácica persistente, con o sin irradiación, asociado a dificultad respiratoria, palidez, sudor frío, náuseas, mareos o sensación de muerte inminente.' },
    { type: 'paragraph', text: 'La positividad de este diagnóstico aumenta si la persona ha indicado que tiene alguna afección cardíaca durante el relevamiento de salud efectuado previamente a la zarpada.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Si el paciente se encuentra consciente, tranquilícelo y colóquelo en posición semisentada, en un lugar cómodo, bien ventilado y donde no sea necesario moverlo.' },
    { type: 'paragraph', text: 'No eleve las piernas.' },
    { type: 'paragraph', text: 'Afloje la ropa ajustada y manténgalo en reposo absoluto.' },
    { type: 'paragraph', text: 'No permita que el paciente fume ni le suministre alimentos o bebidas, especialmente bebidas alcohólicas.' },
    { type: 'paragraph', text: 'No administre medicamentos salvo indicación expresa del médico durante la consulta radial, o por indicación previa del paciente, relevada durante el relevamiento de salud previo a la partida.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio de inmediato al servicio guardacostas correspondiente e inicie los preparativos para el traslado según las indicaciones recibidas.' },
    { type: 'paragraph', text: 'Si el paciente pierde la conciencia, deberá actuar conforme a los procedimientos para ese estado, solicitando ayuda médica urgente.' },
    { type: 'paragraph', text: 'Apoplejía y Parálisis' },
    { type: 'paragraph', text: 'Parálisis facial.' },
    { type: 'paragraph', text: 'La apoplejía, actualmente denominada "ACV" por las iniciales de Accidente Cerebrovascular", suele presentarse de manera súbita y puede estar acompañada de un dolor de cabeza intenso, especialmente en los casos hemorrágicos.' },
    { type: 'paragraph', text: 'Generalmente afecta a un lado del cuerpo, produciendo pérdida de fuerza o parálisis. Cuando compromete la cara, pueden observarse asimetrías faciales, dificultad para mover un lado del rostro, alteraciones del habla, confusión y, en casos graves, disminución del nivel de conciencia.' },
    { type: 'paragraph', text: 'En el ámbito de la navegación recreativa y deportiva, estos cuadros pueden manifestarse durante o después de esfuerzos intensos, deshidratación, traumatismos, exposición prolongada al calor o en personas con antecedentes cardiovasculares. No obstante, también pueden aparecer sin un desencadenante evidente.' },
    { type: 'paragraph', text: 'Sin embargo, dado que a bordo no es posible establecer un diagnóstico diferencial preciso, toda parálisis facial de aparición súbita debe considerarse un posible ACV hasta que un médico indique lo contrario.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Si el paciente se encuentra consciente, tranquilícelo y permítale adoptar una posición cómoda, manteniéndolo en reposo.' },
    { type: 'paragraph', text: 'Procure elevar ligeramente la cabeza, el cuello y los hombros, evitando movimientos bruscos.' },
    { type: 'paragraph', text: 'No le administre alimentos ni bebidas, ni medicamentos sin indicación médica.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio de inmediato y prepare la embarcación para un traslado urgente, siguiendo las instrucciones del servicio guardacostas o de la autoridad marítima.' },
    { type: 'paragraph', text: 'Controle periódicamente el estado de conciencia, la respiración y el pulso del paciente.' },
    { type: 'paragraph', text: 'Si el paciente pierde la conciencia, actúe conforme a los procedimientos correspondientes, priorizando el control de la vía aérea, la respiración y la circulación, y manteniendo comunicación permanente con los servicios de emergencia.' },
    { type: 'paragraph', text: 'Convulsiones' },
    { type: 'paragraph', text: 'Las convulsiones son episodios caracterizados por contracciones musculares involuntarias, pérdida parcial o total de la conciencia y alteraciones del control corporal. Pueden ser consecuencia de epilepsia, traumatismos en la cabeza, fiebre elevada, infecciones, intoxicaciones, consumo o suspensión brusca de alcohol o drogas, y también de alteraciones metabólicas como la hipoglucemia.' },
    { type: 'paragraph', text: 'En una embarcación, las convulsiones pueden ocurrir tras una caída, un golpe contra estructuras rígidas, una insolación, deshidratación severa o como consecuencia de una enfermedad preexistente, en cuyo caso debería haber sido anotada en el relevamiento de salud previo a la zarpada.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse una convulsión cuando el paciente presenta movimientos bruscos e incontrolados de brazos y piernas, rigidez corporal, pérdida de la conciencia, desviación de los ojos, salivación excesiva, mordedura de la lengua o emisión involuntaria de orina.' },
    { type: 'paragraph', text: 'Finalizado el episodio, es frecuente que el paciente permanezca desorientado, somnoliento o confuso durante varios minutos.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'No introduzca objetos en la boca ni intente abrirla.' },
    { type: 'paragraph', text: 'Una vez finalizada la convulsión, colóquelo en posición lateral de seguridad, controle la respiración y manténgalo en reposo.' },
    { type: 'paragraph', text: 'Tranquilícelo al recuperar la conciencia, si la ha perdido.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio y prepare la embarcación para un posible traslado.' },
    { type: 'paragraph', text: 'Si las convulsiones se repiten, duran más de algunos minutos o el paciente no recupera la conciencia, la situación debe considerarse una urgencia grave.' },
    { type: 'paragraph', text: 'Hipoglucemia' },
    { type: 'paragraph', text: 'La hipoglucemia es la disminución anormal del nivel de glucosa en sangre.' },
    { type: 'paragraph', text: 'En la náutica recreativa y deportiva puede verse favorecida por el esfuerzo físico prolongado, el ayuno, el consumo de alcohol y la exposición al calor.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse una hipoglucemia cuando el paciente presenta sudoración fría, palidez, temblores, debilidad, hambre intensa, mareos, dolor de cabeza, alteraciones del comportamiento, confusión, dificultad para hablar o pérdida de la conciencia.' },
    { type: 'paragraph', text: 'En casos graves pueden aparecer convulsiones.' },
    { type: 'paragraph', text: 'Si el paciente es diabético y dispone de su glucómetro personal, puede y debe solicitarse que se mida el nivel de glucosa en sangre, siempre que esté consciente, lúcido y pueda hacerlo con seguridad.' },
    { type: 'paragraph', text: 'Este dato es muy útil para orientar la conducta y para informar al médico durante la consulta radial.' },
    { type: 'paragraph', text: 'En el contexto náutico recreativo, donde los recursos son limitados, contar con una medición objetiva de glucemia puede ayudar a diferenciar una hipoglucemia de otras causas de malestar o pérdida de conciencia.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Si el paciente está inconsciente o no puede tragar, no le administre alimentos ni líquidos por boca, debido al riesgo de aspiración. En este caso, colóquelo en posición lateral de seguridad, controle la respiración y solicite asistencia médica por radio de inmediato.' },
    { type: 'paragraph', text: 'En todos los casos, mantenga al paciente en reposo, abrigado y bajo observación, y prepare la embarcación para un eventual traslado según las indicaciones médicas o de la autoridad marítima.' },
    { type: 'subtitle', text: 'Quemaduras' },
    { type: 'paragraph', text: 'Las quemaduras a bordo pueden producirse por fuego, líquidos calientes, vapor, combustibles, productos químicos, electricidad o por contacto con superficies calientes del motor o del escape, o por exposición excesiva al Sol.' },
    { type: 'paragraph', text: 'En todos los casos, la prioridad es detener la causa de la quemadura, proteger al rescatista y atender al paciente con rapidez y seguridad.' },
    { type: 'paragraph', text: 'Lesiones de Cabeza, Cuello y Espalda' },
    { type: 'paragraph', text: 'Las lesiones que comprometen la cabeza, el cuello o la columna vertebral son potencialmente graves, ya que pueden afectar la médula espinal.' },
    { type: 'paragraph', text: 'Sospecha de lesión de columna.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse una lesión de la columna vertebral cuando el accidentado ha sufrido una caída desde cierta altura, ha recibido un golpe directo o le ha caído un peso sobre la cabeza, el cuello o la espalda.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'En estos casos, no debe mover al paciente, salvo que exista un riesgo inmediato para su vida por otra causa asociada. Si fuera imprescindible moverlo, deberá hacerse tratando la cabeza, el cuello y el cuerpo como una sola unidad, evitando cualquier flexión, rotación o extensión de la columna.' },
    { type: 'paragraph', text: 'El traslado de una persona con sospecha de lesión de columna requiere, idealmente, la participación de varias personas coordinadas. Una de ellas debe encargarse exclusivamente de sostener y estabilizar la cabeza, manteniéndola alineada con el eje del cuerpo, mientras las demás sostienen el tronco, la pelvis y las piernas.' },
    { type: 'paragraph', text: 'Debe levantarse al paciente de forma simultánea y controlada, manteniendo la misma posición en la que fue encontrado, y colocarse sobre una superficie firme y plana. Una vez allí, deben almohadillarse la nuca y la zona lumbar, y asegurar el cuerpo para evitar movimientos involuntarios.' },
    { type: 'paragraph', text: 'En embarcaciones con dotación reducida, donde estas maniobras no puedan realizarse con seguridad, debe priorizarse la inmovilización en el lugar y la solicitud de asistencia médica por radio.' },
    { type: 'paragraph', text: 'Sospecha de lesión en la Cabeza.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Puede sospecharse una lesión craneal cuando el paciente presenta desorientación o confusión persistente, pérdida de la conciencia, aunque sea breve, dolor de cabeza intenso, vómitos, salida de sangre o líquido claro por nariz u oídos, hematomas alrededor de los ojos o detrás de las orejas, bultos o hematomas en cabeza, cuello o espalda, dolor, pérdida de sensibilidad o parálisis de alguna parte del cuerpo.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Ante cualquiera de estas situaciones, controle de forma continua el nivel de conciencia del paciente, tranquilícelo y evite que se mueva.' },
    { type: 'paragraph', text: 'Si vomita, colóquelo cuidadosamente de lado, manteniendo alineados cabeza y cuerpo.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio lo antes posible e inicie el traslado según las indicaciones recibidas.' },
    { type: 'paragraph', text: 'Una vez inmovilizado y colocado en una posición segura, no vuelva a mover al paciente, ni permita que personas no entrenadas lo hagan, ya que podrían agravar las lesiones.' },
    { type: 'paragraph', text: 'No administre ningún medicamento salvo indicación expresa del personal médico del servicio guardacostas.' },
    { type: 'subtitle', text: 'Fracturas y Luxaciones' },
    { type: 'paragraph', text: 'Las fracturas y las luxaciones son lesiones traumáticas que afectan a los huesos y las articulaciones. Se producen generalmente como consecuencia de golpes, caídas o esfuerzos bruscos, y pueden variar desde lesiones leves hasta cuadros graves que comprometen la movilidad y la circulación del miembro afectado.' },
    { type: 'paragraph', text: 'También pueden ocurrir estando el barco amarrado, donde las luxaciones y fracturas ocurren debido a caidas dal intentar pasar del barco a la marina o regresando a bordo, cuando el cuerpo gol´pea contra el barco o el muelle.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Debe sospecharse la existencia de una fractura o una luxación cuando, tras un traumatismo, la persona manifiesta dolor localizado e intenso, hinchazón, deformidad visible del miembro afectado o aparición de hematomas. Esta condición puede estar acompañada por dificultad o imposibilidad para mover la extremidad lesionada.' },
    { type: 'paragraph', text: 'Las fracturas de costillas, además de provocar dolor localizado y la aparición de hematomas, suelen dificultar la respiración profunda, la tos y la risa.' },
    { type: 'paragraph', text: 'En el caso de una fractura expuesta, el hueso puede quedar visible a través de la piel y, obviamente, podrá haber una hemorragia asociada.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Falange sujeta con ferula de emergencia.' },
    { type: 'paragraph', text: 'AUna vez localizada la zona de la fractura o de la luxación, se deberá inmovilizar el miembro afectado en la posición en que se encuentra o mantener al paciente quieto, evitando movimientos innecesarios.' },
    { type: 'paragraph', text: 'Puede aplicarse frío local mediante bolsas de hielo o productos congelados envueltos en tela para disminuir el dolor y la inflamación, evitando el contacto directo con la piel.' },
    { type: 'paragraph', text: 'o intente acomodar, alinear ni reducir la fractura o la luxación por sus propios medios. No traslade al paciente sin haber inmovilizado previamente la zona afectada, salvo que sea imprescindible por razones de seguridad.' },
    { type: 'paragraph', text: 'En el caso de fracturas expuestas, será importante controlar la posible hemorragia y evaluar la circulación y la sensibilidad por debajo de la lesión, observando si el paciente puede sentir o mover los dedos del miembro afectado.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio y prepare la embarcación para un posible traslado o evacuación según las indicaciones recibidas.' },
    { type: 'paragraph', text: 'Ante la sospecha de una fractura de costillas, mantenga al paciente en reposo y colóquelo en una posición cómoda, preferentemente semisentado, que le permita respirar con mayor facilidad, sin que se vea sometido a movimientos innecesarios del tórax.' },
    { type: 'paragraph', text: 'No realice vendajes compresivos alrededor del pecho, ya que estos pueden dificultar la respiración y favorecer complicaciones respiratorias. Controle regularmente la respiración, observando la frecuencia y el esfuerzo respiratorio y, especialmente, que no haya esputos o mucosidad con sangre.' },
    { type: 'paragraph', text: 'Intoxicación por Ingestión' },
    { type: 'paragraph', text: 'La intoxicación por ingestión puede producirse por la ingesta accidental o voluntaria de medicamentos, productos químicos, combustibles, alcohol en exceso o alimentos en mal estado.' },
    { type: 'paragraph', text: 'En el ámbito de la náutica, este tipo de accidente puede estar relacionado con productos de limpieza, combustibles, solventes, medicamentos mal administrados o bebidas alcohólicas.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Intoxicación.' },
    { type: 'paragraph', text: 'Debe sospecharse de una intoxicación por ingestión cuando el paciente presenta náuseas, vómitos, dolor abdominal o retortijones, eventualmente acompañados de somnolencia marcada, confusión o pérdida de la conciencia.' },
    { type: 'paragraph', text: 'En algunos casos pueden observarse quemaduras o irritación alrededor de la boca, en los labios o en las manos, lo que sugiere la ingestión de sustancias corrosivas. Obviamente, estas son condiciones accesorias que también requerirán su correspondiente tratamiento.' },
    { type: 'paragraph', text: 'También puede presentar respiración rápida y superficial, convulsiones o alteraciones del pulso.' },
    { type: 'paragraph', text: 'Si el paciente está consciente, intente preguntarle qué sustancia ha ingerido, en qué cantidad y hace cuánto tiempo. Si no lo está, procure obtener esa información de las personas que estuvieron con él o busque indicios a bordo, como envases, botellas o recipientes abiertos o vacíos.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'No provoque el vómito bajo ninguna circunstancia, ya que podría agravar las lesiones, especialmente si se trata de sustancias corrosivas, hidrocarburos o productos químicos.' },
    { type: 'paragraph', text: 'No administre leche, alcohol ni otros supuestos antídotos.' },
    { type: 'paragraph', text: 'Solo ofrezca pequeños sorbos de agua si el paciente está consciente, puede tragar sin dificultad y no existen signos de ingestión de productos corrosivos, y únicamente mientras recibe indicaciones médicas.' },
    { type: 'paragraph', text: 'Solicite consejo médico por radio de inmediato, informando con la mayor precisión posible la sustancia ingerida, la cantidad estimada, el tiempo transcurrido y los síntomas observados.' },
    { type: 'paragraph', text: 'Controle continuamente el estado de conciencia, la respiración y el pulso, y prepare la embarcación para un eventual traslado o evacuación según las instrucciones del servicio médico o de guardacostas.' },
    { type: 'paragraph', text: 'Intoxicación por Inhalación' },
    { type: 'paragraph', text: 'La intoxicación por inhalación se produce al respirar gases, vapores o humos tóxicos.' },
    { type: 'paragraph', text: 'En una embarcación recreativa o deportiva puede ocurrir por acumulación de vapores de combustible en sentinas, fugas de gas, mala ventilación de motores, principios de incendios o funcionamiento defectuoso de equipos de combustión en espacios cerrados.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Siempre que sea posible, interrogue al paciente y a las personas que hayan estado con él para determinar el tipo de gas o vapor inhalado, el tiempo de exposición y la evolución de los síntomas.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'No se exponga usted mismo al riesgo. No ingrese en espacios cerrados o contaminados si no cuenta con ventilación adecuada o apoyo de otras personas. Recuerde que el rescatista también puede intoxicarse.' },
    { type: 'paragraph', text: 'Si las condiciones lo permiten, retire al paciente de inmediato a una zona abierta y bien ventilada, preferentemente al aire libre. Afloje la ropa que pueda dificultar la respiración y colóquelo en reposo.' },
    { type: 'paragraph', text: 'Controle la respiración y el nivel de conciencia. Si el paciente está inconsciente, pero respira, colóquelo en posición lateral de seguridad.' },
    { type: 'paragraph', text: 'Si no respira, inicie maniobras de reanimación según su entrenamiento.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio de inmediato, describiendo el entorno, los síntomas y la posible fuente de la intoxicación, y prepare la embarcación para un eventual traslado o evacuación siguiendo las indicaciones del servicio médico o de guardacostas.' },
    { type: 'subtitle', text: 'Hipotermia' },
    { type: 'paragraph', text: 'La hipotermia se produce cuando la temperatura corporal desciende por debajo de lo normal debido a una exposición prolongada al frío.' },
    { type: 'paragraph', text: 'En la náutica recreativa y deportiva puede presentarse tras una caída al agua, navegación prolongada con viento y rociones, permanencia con ropas mojadas, o durante guardias en condiciones climáticas adversas.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'A medida que la temperatura corporal desciende, pueden aparecer pulso y respiración lentos o difíciles de percibir, disminución del nivel de conciencia, confusión y, en casos graves, pérdida del conocimiento.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'subtitle', text: 'Hipotermia.' },
    { type: 'paragraph', text: 'No frote ni sacuda al paciente. Si el abrigo pasivo no es suficiente, otras personas pueden aportar calor corporal manteniéndose en contacto directo bajo las mantas.' },
    { type: 'paragraph', text: 'Puede aplicarse calor externo moderado, cuidando de no provocar quemaduras, ya que el paciente puede tener la sensibilidad disminuida.' },
    { type: 'paragraph', text: 'Si el paciente está consciente, ofrézcale líquidos calientes y azucarados. No administre bebidas alcohólicas ni café, y no permita que fume.' },
    { type: 'paragraph', text: 'En la mayoría de los casos, la hipotermia se resuelve rápidamente. Si la condición del paciente no evoluciona positivamente, solicite asistencia médica por radio y prepare la embarcación para un eventual traslado, siguiendo las indicaciones recibidas.' },
    { type: 'paragraph', text: 'Golpe de Calor' },
    { type: 'paragraph', text: 'El golpe de calor se produce cuando la temperatura corporal se eleva de forma peligrosa, generalmente por encima de los 40ºC, como consecuencia de una exposición prolongada al calor o al Sol, especialmente en ambientes calurosos y húmedos.' },
    { type: 'paragraph', text: 'En la náutica recreativa y deportiva puede presentarse durante navegaciones prolongadas a pleno Sol, o inlcusive en puerto o en el varadero cuando se efectuan trabajos en cubierta, y más aún cuando en cualquiera de estas situaciones se utiliza ropa inadecuada, o no se mantiene la hidratación o no hay buena ventilación.' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Golpe de Calor.' },
    { type: 'paragraph', text: 'También suele asociarse este término a la "insolación".' },
    { type: 'paragraph', text: 'Debe sospecharse un golpe de calor cuando el paciente presenta piel notáblemente caliente al contacto con la mano, y enrojecida, que puede estar seca o aún sudorosa. Este síntoma puede estar acompalado de pulso acelerado, sed intensa y malestar general.' },
    { type: 'paragraph', text: 'En casos más graves pueden aparecer dolor de cabeza, confusión, desorientación, alteraciones del comportamiento y hasta pérdida de la conciencia.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Si el paciente está consciente y puede tragar sin dificultad, ofrézcale agua fresca en pequeños sorbos.' },
    { type: 'paragraph', text: 'Controle la temperatura corporal y procure reducirla hasta aproximadamente 39ºC. A partir de ese punto, continúe vigilándola cada 10 minutos.' },
    { type: 'paragraph', text: 'Si la temperatura vuelve a elevarse, reanude las medidas de enfriamiento.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio y prepare la embarcación para un eventual traslado, siguiendo las indicaciones recibidas, especialmente si el paciente presenta alteraciones del nivel de conciencia o no responde positivamente al tratamiento inicial.' },
    { type: 'paragraph', text: 'Técnicas y Procedimientos de Primeros Auxilios' },
    { type: 'paragraph', text: 'A continuación, repasaremos las principales técnicas de recuperación, factibles de ser aplicadas a bordo de una embarcación.' },
    { type: 'paragraph', text: 'Tratamiento de Personas Inconscientes' },
    { type: 'paragraph', text: 'Inconsciencia.' },
    { type: 'paragraph', text: 'Si una persona se encuentra inconsciente, intente despertarla llamándola en voz alta por su nombre, tocándole la cara y sacudiendo suavemente sus hombros.' },
    { type: 'paragraph', text: 'Si no responde en pocos segundos, la situación debe considerarse una urgencia grave.' },
    { type: 'paragraph', text: 'Solicite asistencia médica por radio de inmediato e inicie los preparativos para el traslado, mientras comienza la atención a bordo.' },
    { type: 'paragraph', text: 'Recueste a la persona sobre una superficie firme y plana, aflójale la ropa si está ajustada y compruebe rápidamente si respira y tiene pulso. Para ello, acerque su oído a la boca y nariz del paciente observando si el pecho se eleva, y palpe el pulso sobre la muñeca o en una arteria carótida, a ambos lados del cuello, durante unos 5 a 10 segundos.' },
    { type: 'paragraph', text: 'Si respira y tiene pulso, manténgalo en observación y colóquelo en posición lateral de seguridad.' },
    { type: 'paragraph', text: 'Si no respira o no tiene pulso, inicie de inmediato las maniobras de RCP - reanimación cardiopulmonar.' },
    { type: 'subtitle', text: 'RCP - Reanimación Cardiopulmonar' },
    { type: 'paragraph', text: 'La RCP es un conjunto de maniobras destinadas a mantener la circulación de sangre oxigenada hacia los órganos vitales cuando una persona ha dejado de respirar o su corazón ha cesado de latir de forma repentina, como puede ocurrir tras un ahogamiento, una descarga eléctrica, un traumatismo grave o un evento cardíaco.' },
    { type: 'paragraph', text: 'La realización temprana y sostenida de RCP aumenta significativamente las probabilidades de supervivencia y reduce el riesgo de daño cerebral irreversible.' },
    { type: 'paragraph', text: 'El procedimiento básico de RCP es el siguiente:' },
    { type: 'paragraph', text: 'asegure la vía aérea' },
    { type: 'paragraph', text: 'Con el paciente recostado boca arriba, coloque una mano sobre la frente y la otra bajo el mentón, inclinando suavemente la cabeza hacia atrás y elevando el mentón para abrir la vía aérea, sin forzar el cuello.' },
    { type: 'paragraph', text: 'compruebe si respira' },
    { type: 'paragraph', text: 'Observe el tórax y acerque el oído a la boca y nariz durante unos segundos intentado detectar si el paciente respira, aunque sea levemente.' },
    { type: 'paragraph', text: 'Si no detecta respiración, prosiga.' },
    { type: 'subtitle', text: 'RCP.' },
    { type: 'paragraph', text: 'inicie las compresiones torácicas' },
    { type: 'paragraph', text: 'Si no respira normalmente, coloque el talón de una mano sobre el tercio inferior del esternón, y la otra mano encima, entrelazando los dedos.' },
    { type: 'paragraph', text: 'Con los brazos extendidos y el cuerpo alineado sobre el pecho del paciente, realice 30 compresiones profundas y rítmicas, a un ritmo aproximado de 100 a 120 compresiones por minuto.' },
    { type: 'paragraph', text: 'Permita que el pecho vuelva a su posición entre compresiones, sin retirar las manos.' },
    { type: 'paragraph', text: '¡Importante!' },
    { type: 'paragraph', text: 'En la actualidad, para personal no entrenado o en contextos como la náutica recreativa, se recomienda RCP solo con compresiones, sin respiración boca a boca.' },
    { type: 'paragraph', text: 'Mantenga las series de compresiones de forma continua hasta que el paciente recupere signos vitales, llegue ayuda médica o Usted esté físicamente exhausto.' },
    { type: 'paragraph', text: 'Si hay más de una persona capacitada, es conveniente turnarse cada pocos minutos para evitar la fatiga, procurando que el relevo sea rápido y sin interrupciones prolongadas.' },
    { type: 'paragraph', text: 'Si el paciente recupera la respiración o el pulso, colóquelo en posición lateral de seguridad o semisentado, según su estado.' },
    { type: 'paragraph', text: 'Manténgalo abrigado y en un ambiente tranquilo. Informe inmediatamente la evolución al servicio médico por radio y continúe con el traslado según indicaciones.' },
    { type: 'paragraph', text: 'Atragantamientos' },
    { type: 'paragraph', text: 'El atragantamiento ocurre cuando un cuerpo extraño obstruye parcial o totalmente las vías respiratorias, impidiendo la respiración normal. Si la persona no puede expulsar la obstrucción por sus propios medios, la situación constituye una urgencia vital.' },
    { type: 'paragraph', text: 'Si el paciente está consciente y puede toser, anímelo a toser con fuerza, ya que la tos es el mecanismo más eficaz para desalojar el objeto.' },
    { type: 'paragraph', text: 'No le golpee la espalda mientras tose, ya que esto puede agravar la obstrucción.' },
    { type: 'paragraph', text: 'Si la tos no resulta efectiva y la persona no puede respirar, hablar ni emitir sonidos, realice la Maniobra de Heimlich.' },
    { type: 'subtitle', text: 'Maniobra de Heimlich' },
    { type: 'paragraph', text: 'La Maniobra de Heimlich, con el paciente consciente, se realiza de la siguiente forma:' },
    { type: 'subtitle', text: 'Maniobra de Heimlich.' },
    { type: 'paragraph', text: 'preparación' },
    { type: 'paragraph', text: 'Ubíquese detrás del paciente y rodee su cintura con ambos brazos.' },
    { type: 'paragraph', text: 'Coloque un puño cerrado, con el pulgar hacia adentro, por encima del ombligo y por debajo del esternón.' },
    { type: 'paragraph', text: 'Si el paciente es más alto que usted, puede hacerlo sentar para facilitar la maniobra.' },
    { type: 'paragraph', text: 'En el contexto de una embarcación, procure afirmarse bien y evitar perder el equilibrio durante la asistencia.' },
    { type: 'paragraph', text: 'compresión' },
    { type: 'paragraph', text: 'Tome el puño con la otra mano y realice compresiones rápidas y firmes hacia adentro y hacia arriba, con movimientos bruscos.' },
    { type: 'paragraph', text: 'Repita la maniobra hasta que el objeto sea expulsado o el paciente pierda la conciencia.' },
    { type: 'paragraph', text: 'Con el paciente inconsciente o imposibilidad de maniobra de pie, se debe proceder como sigue:' },
    { type: 'paragraph', text: 'preparación' },
    { type: 'paragraph', text: 'Ubíquese detrás del paciente y rodee su cintura con ambos brazos.' },
    { type: 'paragraph', text: 'Coloque un puño cerrado, con el pulgar hacia adentro, por encima del ombligo y por debajo del esternón.' },
    { type: 'paragraph', text: 'Si la persona pierde la conciencia, acuéstela boca arriba sobre una superficie firme.' },
    { type: 'paragraph', text: 'Ubíquese a horcajadas sobre el paciente.' },
    { type: 'paragraph', text: 'Coloque el talón de una mano por encima del ombligo y la otra mano sobre la primera.' },
    { type: 'paragraph', text: 'compresión' },
    { type: 'paragraph', text: 'Realice compresiones firmes y rápidas hacia arriba, utilizando el peso de su cuerpo.' },
    { type: 'paragraph', text: 'Luego de cada serie de compresiones, abra la boca del paciente y observe si el objeto es visible. Si puede verlo, retírelo con cuidado.' },
    { type: 'paragraph', text: 'En cualquiera de los casos, si no logra desobstruir la vía aérea y el paciente no respira, inicie inmediatamente RCP y solicite asistencia médica por radio.' },
    { type: 'paragraph', text: 'En personas obesas o embarazadas, las compresiones deben realizarse sobre el centro del pecho, en el esternón, en lugar del abdomen.' },
    { type: 'paragraph', text: 'Una vez resuelto el atragantamiento, el paciente debe ser evaluado médicamente, ya que pueden quedar lesiones internas.' },
    { type: 'paragraph', text: 'Henry Heimlich fue un médico estadounidense que vivió entre 1920 y 2016.' },
    { type: 'paragraph', text: 'Henry Heimlich.' },
    { type: 'paragraph', text: 'Heimlich creó su maniobra basándose en estudios de fisiología respiratoria y experimentos con pulmones de cerdo, donde comprobó que una compresión desde el abdomen hacia arriba generaba suficiente presión en los pulmones para expulsar cuerpos extraños de la tráquea, simulando la acción de un estornudo o una tos forzada. A partir de estas observaciones desarrolló la técnica que lleva su nombre y promovió su uso en entrenamientos de primeros auxilios alrededor del mundo.' },
    { type: 'paragraph', text: 'Esta técnica se convirtió en un estándar internacional para salvar vidas en casos de asfixia.' },
    { type: 'paragraph', text: 'Posición Lateral de Seguridad' },
    { type: 'paragraph', text: 'La posición lateral de seguridad se utiliza para colocar a un paciente inconsciente que respira y tiene pulso en una postura cómoda y segura. Esta posición permite que cualquier fluido, como vómito o secreciones, drene sin obstaculizar la respiración. La barbilla debe inclinarse ligeramente hacia atrás, manteniendo la epiglotis abierta, y brazos y piernas deben colocarse de manera que la postura sea estable.' },
    { type: 'paragraph', text: 'No se debe aplicar esta posición si se sospecha de lesiones en cuello o columna vertebral.' },
    { type: 'paragraph', text: 'El procedimiento para lograr la posición lateral de seguridad, girando al paciente hacia su derecha, es el que describiremos a continuación. En caso de tener que girarlo a la izquierda, deberá invertir las instrucciones:' },
    { type: 'paragraph', text: 'preparación' },
    { type: 'paragraph', text: 'Acueste al paciente boca arriba y retire anteojos o cualquier objeto duro de sus bolsillos, para evitarle molestias.' },
    { type: 'paragraph', text: 'Colóquese Usted mismo sobre el lado derecho del paciente, a la altura de su cintura.' },
    { type: 'paragraph', text: 'Si el paciente yace sobre el suelo, arrodíllese sobre su lado derecho, a la misma altura.' },
    { type: 'paragraph', text: 'Posición lateral de seguridad.' },
    { type: 'paragraph', text: 'giro' },
    { type: 'paragraph', text: 'Extienda la pierna derecha del paciente y coloque el brazo derecho junto al cuerpo.' },
    { type: 'paragraph', text: 'Coloque el brazo izquierdo doblado sobre el abdomen y flexione la pierna llevando la rodilla hacia arriba manteniendo su pie apoyado en la superficie sobre la que yace.' },
    { type: 'paragraph', text: 'Ajuste la mano derecha hacia la espalda y la pierna izquierda extendida sobre la derecha flexionada, asegurando estabilidad.' },
    { type: 'paragraph', text: 'control' },
    { type: 'paragraph', text: 'Una vez lograda la posición lateral de seguridad, controle regularmente la respiración y el pulso del paciente.' },
    { type: 'paragraph', text: 'Tratamiento de Hemorragias' },
    { type: 'subtitle', text: 'Hemorragias Externas' },
    { type: 'paragraph', text: 'diagnóstico' },
    { type: 'paragraph', text: 'Las hemorragias externas se caracterizan por la salida visible de sangre al exterior del cuerpo.' },
    { type: 'paragraph', text: 'Pueden presentarse como sangrados leves, moderados o profusos, ya sea a través de una herida, de la nariz u otra abertura natural, o como consecuencia de una lesión traumática.' },
    { type: 'paragraph', text: 'tratamiento' },
    { type: 'paragraph', text: 'Ante una hemorragia externa, lo primero que debe hacerse es aplicar presión directa sobre la herida utilizando gasas estériles. En caso de no disponer de ellas de inmediato, puede utilizarse cualquier paño o toalla limpia hasta contar con el botiquín. La compresión debe mantenerse durante al menos diez minutos, sin retirar las gasas. Si el sangrado continúa, deben colocarse más gasas sobre las anteriores, sin interrumpir la presión.' },
    { type: 'paragraph', text: 'No es recomendable utilizar algodón en contacto directo con la herida en casos como estos, pues si existe riesgo de que queden restos adheridos que retrasarían la cicatrización facilitando al mismo tiempo la posibilidad de que se infecte.' },
    { type: 'paragraph', text: 'Si la hemorragia se produce en una extremidad, puede elevarse el miembro afectado por encima del plano del corazón, siempre que no exista sospecha de fractura. El taponamiento debe mantenerse hasta que la herida deje de sangrar o el drenaje se reduzca al mínimo.' },
    { type: 'paragraph', text: 'En el caso de hemorragia nasal, incline la cabeza del paciente hacia adelante y comprima ambos orificios nasales cerca del hueso de la nariz durante unos diez minutos. Aplique un paño frío sobre la nariz y la frente. Si el sangrado cede, recomiende no sonarse ni hurgarse la nariz durante las siguientes 24 horas. Si la hemorragia no se detiene luego de 30 minutos, puede colocarse cuidadosamente una gasa estéril recortada en forma de tira en el interior de la nariz, utilizando una pinza si se dispone de ella, y solicitar asistencia médica por radio.' },
    { type: 'paragraph', text: 'Si a pesar de las medidas iniciales la hemorragia continúa siendo muy intensa, o mana de un punto concreto en gran cantidad, puede recurrirse a la presión sobre una arteria o a la aplicación de un torniquete. La presión arterial requiere conocimiento previo de los puntos por donde pasan las arterias, pero permite reducir rápidamente el sangrado sin afectar todo el miembro.' },
    { type: 'paragraph', text: 'Torniquete improvisado.' },
    { type: 'paragraph', text: 'El torniquete debe utilizarse únicamente cuando han fracasado todas las medidas anteriores o como primera medida en hemorragias extremadamente profusas, como las producidas por amputaciones. Debe colocarse solo en extremidades, en zonas donde exista un hueso, y siempre entre la herida y el corazón. Puede improvisarse con un shock-cord, un cabo o un paño limpio, retorciéndolo hasta lograr la detención del sangrado.' },
    { type: 'paragraph', text: 'Al aplicar un torniquete es fundamental anotar la hora de colocación, ya que debe liberarse cada quince minutos para permitir la circulación sanguínea. Si al liberarlo la hemorragia reaparece, debe reaplicarse por otro período similar. Asimismo, es conveniente mantener fría la parte distal del miembro, utilizando hielo u otro elemento frío, siempre aislado de la piel mediante una venda o paño.' },
    { type: 'paragraph', text: 'El Botiquín' },
    { type: 'paragraph', text: 'El botiquín de a bordo es indispensable para poder resolver la asistencia sanitaria mínima ante alguna emergencia que pueda ocurrir a bordo. De su buen estado y mantenimiento puede depender la debida atención de una persona en caso de enfermedad o accidente.' },
    { type: 'paragraph', text: 'Es conveniente que el gabinete del botiquín sea estanco, para impedir que su contenido se humedezca, y debe guardarse en un sitio adecuado, que no esté expuesto al calor o al contacto directo con el agua. Es recomendable hacer una lista del contenido y guardarla en el botiquín. Asegúrese que todos los elementos estén debidamente resguardados y rotulados. En caso de líquidos, es conveniente utilizar envases plásticos, pues el vidrio puede romperse fácilmente. Es recomendable efectuar una revisión del botiquín al menos una vez cada tres meses a fin de reemplazar los elementos o fármacos que pudiesen haberse deteriorado o llegado a su fecha de vencimiento.' },
    { type: 'paragraph', text: 'Pueden adquirirse botiquines ya equipados en farmacias, o solicitarle al farmacéutico le aconseje como equiparlo.' },
    { type: 'paragraph', text: 'En cualquier caso, un botiquín náutico preparado para navegaciones de media y larga distancia debería contener el siguiente inventario, que de por sí es algo más amplio que el contenido de un botiquín básico y elemental:' },
    { type: 'paragraph', text: 'El botiquín.' },
    { type: 'paragraph', text: 'Analgésicos.' },
    { type: 'paragraph', text: 'Preferiblemente en forma de comprimidos o cápsulas, contenidas en blísters.' },
    { type: 'paragraph', text: 'Son útiles para calmar el dolor y pueden servir para aliviar la fiebre.' },
    { type: 'paragraph', text: 'Los más comunes para llevar a bordo son el ácido acetilsalicílico —aspirina— y el paracetamol, que produce menores molestias gástricas.' },
    { type: 'paragraph', text: 'Antinflamatorios.' },
    { type: 'paragraph', text: 'Se utilizan para disminuir inflamaciones, como las resultantes de contusiones, torceduras y demás lesiones traumáticas.' },
    { type: 'paragraph', text: 'Las presentaciones en forma de crema pomada o spray son las ideales para el botiquín, ya que la aplicación local disminuye la posibilidad de efectos secundarios.' },
    { type: 'paragraph', text: 'Antiácidos.' },
    { type: 'paragraph', text: 'Neutralizan la acidez del jugo gástrico.' },
    { type: 'paragraph', text: 'Resultan muy beneficiosos en todo tipo de ardores estomacales producidos por la ingesta de algunas comidas. Es preferible adquirirlos en forma de solución, ya que actúan más rápidamente.' },
    { type: 'paragraph', text: 'Antieméticos.' },
    { type: 'paragraph', text: 'Antidiarreicos.' },
    { type: 'paragraph', text: 'Antialérgicos.' },
    { type: 'paragraph', text: 'Útiles en cuadros alérgicos y en picaduras de insectos.' },
    { type: 'paragraph', text: 'Su presentación en forma de cremas o pomadas es la preferible para llevar a bordo.' },
    { type: 'paragraph', text: 'Desinfectantes.' },
    { type: 'paragraph', text: 'Son imprescindibles para la prevención de infecciones en heridas y quemaduras y también para la limpieza de lesiones cutáneas.' },
    { type: 'paragraph', text: 'Si bien el alcohol es el más común de ellos, los más prácticos para llevar a bordo son los que se presentan en cremas, y también resultan muy útiles los jabones antisépticos.' },
    { type: 'paragraph', text: 'Estos productos deben guardarse siempre en recipientes herméticamente cerrados.' },
    { type: 'paragraph', text: 'Cremas para quemaduras.' },
    { type: 'paragraph', text: 'Solo son eficaces en las pequeñas quemaduras o después de haber estado expuestos al Sol por largo tiempo.' },
    { type: 'paragraph', text: 'Cuando la lesión sea mayor se debe solicitar asistencia médica de inmediato.' },
    { type: 'paragraph', text: 'Antibióticos.' },
    { type: 'paragraph', text: 'Solo tiene sentido llevarlos a bordo en singladuras de larga distancia, en las que no se prevé tocar puerto por tiempo prolongado, y para ser utilizados entonces como paliativos hasta poder poner al enfermo en manos de un servicio médico.' },
    { type: 'paragraph', text: 'En este contexto los antibióticos más recomendables para componer un botiquín son aquellos derivados de la penicilina, del tipo de la ampicilina o la amoxicilina, eficaces contra gran número de gérmenes.' },
    { type: 'paragraph', text: 'Colirios.' },
    { type: 'paragraph', text: 'De la amplia gama de colirios existentes en el mercado farmacéutico debería elegirse un preparado del tipo antiséptico sedante, que sirva para combatir las conjuntivitis irritantes y leves, que son las más usuales.' },
    { type: 'paragraph', text: 'Además, disminuyen las molestias que acompañan a los orzuelos, las inflamaciones de los párpados y los característicos picores. Evite aquellos que contengan corticoides.' },
    { type: 'paragraph', text: 'Gasas y Compresas.' },
    { type: 'paragraph', text: 'En cuanto a las gasas, se sugieren aquellas que vienen en paquetes que contienen una o más gasas estériles individuales, en cuadrados o rectángulos, y que se utilizan para limpiar o cubrir heridas o detener hemorragias.' },
    { type: 'paragraph', text: 'Cada paquete se halla cerrado en cobertura estéril.' },
    { type: 'paragraph', text: 'Las compresas, por su lado, son porciones cuadradas de gasa estéril de mayor tamaño, y que se utilizan para cubrir heridas y hemorragias graves.' },
    { type: 'paragraph', text: 'Recuerde que siempre es preferible emplear gasas y compresas para limpiar las heridas, quemaduras y demás lesiones, ya que si se hace con algodón existe mayor riesgo de que queden restos de éste en la herida, los cuales retrasarían la cicatrización facilitando al mismo tiempo la posibilidad de que se infecte.' },
    { type: 'paragraph', text: 'Vendas.' },
    { type: 'paragraph', text: 'Especialmente en rollos, tanto elásticas como de gasa, y de diferentes anchos.' },
    { type: 'paragraph', text: 'Apósitos.' },
    { type: 'paragraph', text: ': Desde las conocidas "Curitas" hasta los apósitos de mayor tamaño, útiles para cubrir heridas pequeñas.' },
    { type: 'paragraph', text: 'Cinta adhesiva.' },
    { type: 'paragraph', text: 'Se utiliza para fijar gasas, apósitos, vendas y en segunda instancia para cerrar los bordes de las heridas. Son preferibles las de tipo hipoalergénicas.' },
    { type: 'paragraph', text: 'Algodón.' },
    { type: 'paragraph', text: 'Se usa para forrar los entablillados o inmovilizadores, para improvisar apósitos y desinfectar el instrumental.' },
    { type: 'paragraph', text: 'No se recomienda su aplicación directa sobre heridas abiertas.' },
    { type: 'paragraph', text: 'Instrumental y Otros Elementos Adicionales.' },
    { type: 'paragraph', text: 'Agregue un manual de primeros auxilios.' },
    { type: 'paragraph', text: 'Lleve también un pequeño anotador y un lápiz, que le servirá para anotar las instrucciones del servicio de emergencia o los valores de los signos vitales de su paciente.' },
    { type: 'paragraph', text: 'Comentario importante.' },
    { type: 'paragraph', text: 'En ausencia de un médico, la dosificación de cada medicamento debe ser efectuada siguiendo las recomendaciones de los respectivos prospectos.' },
    { type: 'paragraph', text: 'Recuerde que, ante cualquier duda, si no tiene un médico a bordo, o no puede contactar alguno de su confianza por teléfono, puede solicitar asistencia médica por radio al servicio guardacostas de la zona en la que se encuentre navegando.' },
    { type: 'paragraph', text: 'Esta lista es obviamente exigua y deberá adaptarse de acuerdo con las circunstancias y características de la embarcación utilizada, la cantidad y edades de los tripulantes, cantidad de días de la singladura y lugares que se visitaran. Su función sin embargo es dar una idea aproximada de la estructura y composición básica de un botiquín de emergencias.' },
    { type: 'paragraph', text: 'En la siguiente nota, y continuando con los aspectos de seguridad a bordo, veremos las técnicas de lucha contra el fuego.' },
    { type: 'paragraph', text: 'Cabuyería: Tipos de cabos y su aplicación.' },
    { type: 'paragraph', text: 'Técnicas de Fondeo.' },
  ],

  quiz: [
    {
      question: '¿Cuál es el primer paso ante una emergencia médica a bordo?',
      options: ['Llamar inmediatamente por radio', 'Evaluar la escena y garantizar la seguridad', 'Administrar medicamentos', 'Mover al paciente a un lugar seguro'],
      correctAnswer: 1,
      explanation: 'Ante cualquier emergencia, lo primero es evaluar la escena y garantizar la seguridad del auxiliador y del paciente antes de actuar.'
    },
    {
      question: '¿Qué debe contener un botiquín de primeros auxilios a bordo?',
      options: ['Solo medicamentos recetados', 'Material de curas, vendas, antisépticos, guantes y elementos básicos', 'Instrumentos quirúrgicos', 'Solo analgésicos'],
      correctAnswer: 1,
      explanation: 'El botiquín debe incluir material de curas, vendas, antisépticos, guantes desechables, tijeras, pinzas y elementos básicos para atender emergencias.'
    },
    {
      question: '¿Cuál es el tratamiento inicial para una hipotermia leve?',
      options: ['Sumergir en agua caliente', 'Abrigar, proporcionar bebidas calientes y evitar movimientos bruscos', 'Frotar vigorosamente las extremidades', 'Administrar alcohol'],
      correctAnswer: 1,
      explanation: 'Ante una hipotermia leve, se debe abrigar a la persona, proporcionar bebidas calientes no alcohólicas y evitar movimientos bruscos.'
    },
    {
      question: '¿Cómo se controla una hemorragia externa severa?',
      options: ['Aplicando torniquete inmediatamente', 'Presionando directamente sobre la herida con un apósito', 'Elevando la extremidad solamente', 'Aplicando hielo'],
      correctAnswer: 1,
      explanation: 'El control inicial de una hemorragia externa severa se realiza presionando directamente sobre la herida con un apósito o gasa estéril.'
    },
  ]
};