import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'corrientes-marinas',
  title: 'Las Corrientes Marinas',
  readingTime: 11,

  content: [
    { type: 'title', text: 'Las Corrientes Marinas' },
    { type: 'subtitle', text: 'Definiciones' },
    { type: 'subtitle', text: 'Corrientes marinas.' },
    { type: 'paragraph', text: 'Se denominan corrientes marinas o corrientes oceánicas a los movimientos organizados de circulación y desplazamiento de grandes masas de agua que se producen tanto en la superficie como en las capas profundas de los océanos y mares. Estos movimientos pueden ser persistentes y seguir trayectorias relativamente definidas, o bien presentar variaciones estacionales.' },
    { type: 'paragraph', text: 'Las corrientes marinas desempeñan un papel fundamental en el equilibrio térmico del planeta, ya que transportan calor desde las regiones ecuatoriales hacia latitudes medias y altas, y aguas más frías hacia zonas tropicales. De este modo, contribuyen a la regulación del clima global, de forma análoga a como lo hace la atmósfera mediante la circulación general atmosférica.' },
    { type: 'subtitle', text: 'Movimientos de las Corrientes' },
    { type: 'paragraph', text: 'Las corrientes marinas tienen su origen y dinámica en la confluencia de una serie de factores físicos, entre los que se destacan los siguientes:' },
    { type: 'subtitle', text: 'Vientos Dominantes' },
    { type: 'paragraph', text: 'Los vientos dominantes, generados por la circulación general de la atmósfera, ejercen fricción sobre la superficie del océano y arrastran las capas superficiales del agua con las que se encuentran en contacto, dando origen a las principales corrientes superficiales.' },
    { type: 'subtitle', text: 'Rotación de la Tierra' },
    { type: 'paragraph', text: 'La rotación de la Tierra produce el denominado efecto de Coriolis, que desvía la trayectoria de las corrientes marinas de manera similar a la que actúa sobre los vientos.' },
    { type: 'paragraph', text: 'Como resultado, las corrientes son desviadas hacia la derecha en el hemisferio norte y hacia la izquierda en el hemisferio sur, lo que se traduce, en términos generales, en una tendencia al desplazamiento hacia el oeste en las zonas tropicales.' },
    { type: 'paragraph', text: 'La rotación terrestre origina, además, entre aproximadamente 50 y 200 metros de profundidad, corrientes compensatorias que se desplazan en sentido opuesto a las corrientes superficiales, contribuyendo al equilibrio dinámico del sistema oceánico.' },
    { type: 'subtitle', text: 'Leyes Físicas' },
    { type: 'paragraph', text: 'En menor medida, intervienen también los movimientos asociados a la necesidad de equilibrar las diferencias de temperatura, densidad y salinidad existentes entre distintas regiones oceánicas.' },
    { type: 'paragraph', text: 'Estos procesos dan lugar a corrientes profundas y a la llamada circulación termohalina, fundamental para el transporte de energía a escala global.' },
    { type: 'paragraph', text: 'A su vez, las corrientes marinas se distinguen entre corrientes generales cálidas y frías, dependiendo de si su temperatura es mayor o menor a la de las aguas próximas a ellas.' },
    { type: 'paragraph', text: 'La velocidad de las corrientes generales raramente supera los 3 nudos. El desplazamiento de las aguas sucede en la superficie, pues en las profundidades el único rastro de la existencia de las corrientes lo indica la diferencia de temperatura de las aguas y no su movimiento.' },
    { type: 'paragraph', text: 'La Corriente del Golfo, que se origina en el Caribe, y cuyo flujo cálido ayuda a mantener templadas las costas de América del Norte y Europa, es la más conocida de las corrientes cálidas.' },
    { type: 'paragraph', text: 'El mismo efecto produce la Corriente Negra, así llamada por el color de sus aguas, sobre las costas de Japón, calentándolas con aguas del Pacifico central.' },
    { type: 'subtitle', text: 'Representación de las Corrientes Marinas' },
    { type: 'paragraph', text: 'La mayoría de las cartas náuticas informan los datos de dirección y velocidad de las corrientes marinas y de las mareas mediante flechas trazadas en las zonas de interés.' },
    { type: 'paragraph', text: 'Las corrientes marinas se indican con una flecha emplumada en ambos lados de su cola, señalando su dirección, que puede estar asociada a un número informando la velocidad máxima que puede alcanzar, expresada en nudos o en la unidad que indique la carta.' },
    { type: 'paragraph', text: 'No se confunda con las corrientes de marea, que se indican con dos tipos de flechas.' },
    { type: 'paragraph', text: 'La marea de flujo se informa con una flecha con plumas en uno de los lados de su cola, mientras que la marea de reflujo no tiene plumas en su cola.' },
    { type: 'paragraph', text: 'Flechas indicativas de las corrientes.' },
    { type: 'paragraph', text: 'En ambos casos las flechas pueden informar la velocidad máxima que puede alcanzar la corriente de marea, en nudos o en la unidad que indique la carta.' },
    { type: 'paragraph', text: 'Note que, en caso de figurar dos valores de velocidad, el más alto corresponderá a las mareas de sicigia y el más bajo a las de cuadratura.' },
    { type: 'subtitle', text: 'Corrientes Marinas de Importancia Local' },
    { type: 'paragraph', text: 'A continuación, enumeraremos las principales corrientes marinas que tienen influencia en nuestro subcontinente.' },
    { type: 'subtitle', text: 'Corriente Circumpolar Antártica' },
    { type: 'paragraph', text: 'Corriente Circumpolar Antártica.' },
    { type: 'paragraph', text: 'La Corriente Circumpolar Antártica es una corriente oceánica fría que fluye alrededor del continente antártico en sentido Oeste–Este, con velocidades superficiales típicas del orden de 1,5 a 2,0 nudos, aunque en algunos puntos puede ser mayor.' },
    { type: 'paragraph', text: 'De hecho, la Corriente Circumpolar Antártica es la única corriente oceánica que circunda completamente el globo sin interrupción continental.' },
    { type: 'paragraph', text: 'Esta circulación actúa como una barrera dinámica que aísla térmicamente a la Antártida, impidiendo el ingreso de aguas relativamente más cálidas provenientes de los océanos Atlántico, Índico y Pacífico, y contribuyendo así al mantenimiento de su extensa capa de hielo.' },
    { type: 'paragraph', text: 'La Corriente Circumpolar Antártica es bien conocida por los marinos, ya que su intensidad, combinada con los fuertes vientos y el estado de mar característico de la región, hace extremadamente difícil la navegación en sentido Este–Oeste alrededor de la Antártida y, particularmente, en el Pasaje de Drake donde el paso se angosta, acelerando el flujo de la corriente.' },
    { type: 'paragraph', text: 'Por el contrario, estas condiciones han favorecido históricamente las rutas hacia el Este, especialmente en las navegaciones de altas latitudes del hemisferio Sur.' },
    { type: 'subtitle', text: 'Corriente Fría de Malvinas' },
    { type: 'paragraph', text: 'Corriente Fría de Malvinas.' },
    { type: 'paragraph', text: 'La Corriente Fría de Malvinas se origina como una rama que se desprende de la Corriente Circumpolar Antártica luego de que esta haya atravesado el Pasaje de Drake.' },
    { type: 'paragraph', text: 'Las aguas de la Corriente Fría de Malvinas se caracterizan por ser, como su nombre lo indica, frías y relativamente menos salinas, en comparación con las aguas subtropicales.' },
    { type: 'paragraph', text: 'Aguas afuera de la corriente de Malvinas corre la Corriente Cálida de Brasil, que baja desde la franja ecuatorial, contorneando la silueta del Anticiclón Semipermanente del Atlántico Sur, con la cual entra en contacto generando fuertes gradientes de diferencias de temperatura y salinidad, que pueden favorecer la formación de nieblas y neblinas. Esa diferencia de características físicas da como resultado, además, un contexto de elevada productividad biológica.' },
    { type: 'paragraph', text: 'En esa zona de contacto entre la corriente Fría de Malvinas y la Calida de Brasil es donde operan las flotas pesqueras del Atlántico Sur.' },
    { type: 'paragraph', text: 'El límite de las 200 millas de la Zona Económica Exclusiva deja parte de esa zona dentro de la jurisdicción económica de nuestro país, quedando la franja más allá de la milla 200 abierta para la explotación de flotas pesqueras de otras banderas.' },
    { type: 'subtitle', text: 'Corriente Cálida de Brasil' },
    { type: 'paragraph', text: 'Corriente Cálida de Brasil.' },
    { type: 'paragraph', text: 'La Corriente Cálida de Brasil transporta aguas cálidas tropicales hacia el Sur, a lo largo de la costa oriental de América del Sur, principalmente frente a Brasil y Uruguay, manifestándose desde la superficie hasta aproximadamente los 600 metros de profundidad.' },
    { type: 'paragraph', text: 'Esta corriente se origina como una bifurcación de la Corriente Ecuatorial del Sur, la cual fluye al Sur del Ecuador en sentido Este–Oeste.' },
    { type: 'paragraph', text: 'Al alcanzar la plataforma continental frente a Cabo de São Roque, en el Nordeste de Brasil, dicha corriente se divide en dos ramas: la Corriente del Norte de Brasil, que continúa hacia el Oeste introduciéndose en las aguas del Caribe, y la Corriente Cálida de Brasil, que diverge hacia el Sur.' },
    { type: 'paragraph', text: 'La Corriente de Brasil fluye paralela a la costa con una velocidad media del orden de 0,5 nudos, desplazándose inicialmente sobre la plataforma continental.' },
    { type: 'paragraph', text: 'Aproximadamente a partir de los 12º S de latitud, comienza a separarse progresivamente de la costa y a intensificarse como corriente de borde occidental, avanzando hacia latitudes más altas hasta alcanzar el entorno de los 38º S. En ese recorrido es donde esta corriente corre paralela y entrando en contacto con la Corriente Fría de Malvinas, que corre en sentido contrario, hacia el Norte.' },
    { type: 'paragraph', text: 'Esa zona de confluencia entre ambas corrientes presenta una marcada variabilidad estacional, desplazándose hacia el Norte durante el invierno y la primavera del hemisferio Sur, y hacia el Sur durante el verano y el otoño, lo que tiene importantes implicancias sobre el clima regional, la visibilidad y la productividad biológica.' },
    { type: 'paragraph', text: 'Si bien la fuerza de la Corriente Calida de Brasil no supera la media de 0,5 nudos, esa estacionalidad debe ser considerada al momento de planificar rutas de larga distancia que corran sobre las costas de Brasil, a fin de aprovecharla en rutas descendentes o reducir su impacto en rutas ascendentes.' },
    { type: 'subtitle', text: 'Corriente Fría de Humboldt' },
    { type: 'paragraph', text: 'Corriente Fría de Humboldt.' },
    { type: 'paragraph', text: 'La Corriente Fría de Humboldt fluye a lo largo de la costa occidental de América del Sur, desde el sur de Chile hasta el norte de Perú, donde adopta formalmente la denominación de Corriente Peruana.' },
    { type: 'paragraph', text: 'Se origina como una derivación de la Corriente Circumpolar Antártica, la cual, al encontrar la masa continental sudamericana, se ve forzada a desviarse hacia el Norte. Desde allí, la corriente avanza paralela a las costas chilenas y peruanas con una velocidad promedio del orden de 0,5 nudos, transportando aguas frías de origen subantártico.' },
    { type: 'paragraph', text: 'Las bajas temperaturas de las aguas de la Corriente Fría de Humboldt ejercen una marcada influencia sobre el clima costero del Pacífico sudoriental y sobre los sistemas atmosféricos que atraviesan la Cordillera de los Andes hacia el este. En particular, contribuyen a que los anticiclones migratorios que ascienden desde la Antártida conserven sus características de masa de aire fría, limitando el calentamiento por radiación solar y restringiendo su desarrollo vertical. Este efecto dificulta que dichos sistemas superen la barrera orográfica de los Andes, influyendo de manera significativa en la distribución de precipitaciones y en la aridez característica de amplias regiones costeras.' },
  ],

  quiz: [
    {
      question: '¿Qué son las corrientes marinas?',
      options: ['Movimientos aleatorios del agua superficial', 'Movimientos organizados de circulación de grandes masas de agua', 'Solo las olas generadas por el viento', 'El movimiento de las mareas'],
      correctAnswer: 1,
      explanation: 'Las corrientes marinas son movimientos organizados de circulación y desplazamiento de grandes masas de agua, tanto superficiales como profundas.'
    },
    {
      question: '¿Qué efecto produce la rotación de la Tierra sobre las corrientes marinas en el hemisferio Sur?',
      options: ['Las desvía hacia la derecha', 'Las desvía hacia la izquierda', 'Acelera su velocidad', 'No tiene efecto sobre las corrientes'],
      correctAnswer: 1,
      explanation: 'El efecto de Coriolis desvía las corrientes hacia la izquierda en el hemisferio Sur y hacia la derecha en el hemisferio Norte.'
    },
    {
      question: '¿Qué indica una flecha emplumada en ambos lados de su cola en una carta náutica?',
      options: ['Corriente de marea de flujo', 'Corriente de marea de reflujo', 'Corriente marina general', 'Dirección del viento predominante'],
      correctAnswer: 2,
      explanation: 'Las corrientes marinas se indican con una flecha emplumada en ambos lados de su cola, mientras que las corrientes de marea usan otros tipos de flechas.'
    },
    {
      question: '¿Cuál es la velocidad máxima típica de las corrientes marinas generales?',
      options: ['1 nudo', '3 nudos', '5 nudos', '10 nudos'],
      correctAnswer: 1,
      explanation: 'La velocidad de las corrientes generales raramente supera los 3 nudos.'
    },
  ]
};
