import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'salvavidas-circular',
  title: 'Salvavidas Circular',
  readingTime: 6,

  content: [
    { type: 'title', text: 'Elementos de Seguridad: El Salvavidas Circular' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'paragraph', text: 'El aro salvavidas, también conocido como salvavidas circular o simplemente “la rosca”, es uno de los elementos de seguridad más antiguos y reconocibles a bordo. Su función principal es proporcionar flotabilidad inmediata a una persona que ha caído al agua, permitiéndole mantener la cabeza fuera del agua hasta ser rescatada.' },
    { type: 'paragraph', text: 'En la navegación moderna, el salvavidas circular sigue siendo un componente obligatorio y esencial. Los convenios internacionales, como el SOLAS, establecen sus dimensiones, colores, materiales y características reflectantes, garantizando que sea visible, durable y capaz de soportar condiciones adversas.' },
    { type: 'subtitle', text: 'Salvavidas circular.' },
    { type: 'paragraph', text: 'Especificaciones Técnicas' },
    { type: 'paragraph', text: 'El Salvavidas' },
    { type: 'paragraph', text: 'Existen varios tipos de salvavidas circulares, pero todos comparten una característica esencial: deben poder ser arrojados rápidamente y ofrecer flotabilidad suficiente para sostener a un adulto en el agua durante el tiempo que dure la maniobra de rescate. Las normas internacionales, especialmente el Convenio SOLAS, establecen los requisitos mínimos que deben cumplir.' },
    { type: 'paragraph', text: 'Información Adicional' },
    { type: 'paragraph', text: 'El Convenio SOLAS' },
    { type: 'paragraph', text: 'Este Convenio define, entre otras cosas, las características que deben cumplir los elementos de seguridad que llevamos a bordo de nuestros barcos.' },
    { type: 'paragraph', text: 'Un salvavidas certificado bajo norma SOLAS debe ser capaz de soportar una caída libre desde al menos 30 metros de altura sin dañarse ni perder flotabilidad, tener un diámetro exterior de unos 70 a 75 centímetros, y una masa mínima de 2,5 kilogramos para garantizar un buen alcance al lanzarlo. Además, debe ser de color naranja intenso e incluir bandas reflectantes de materiales homologados.' },
    { type: 'paragraph', text: 'Por otro lado, en la náutica deportiva y recreativa se admiten versiones más livianas o de materiales sintéticos como el polietileno expandido o la espuma de celda cerrada, que no cumplen estrictamente la norma SOLAS pero que resultan aceptables para embarcaciones pequeñas. Aunque estos modelos suelen carecer del peso reglamentario o de la homologación para uso comercial, mantienen la flotabilidad y visibilidad necesarias para actuar como primera respuesta en una caída al agua.' },
    { type: 'paragraph', text: 'El Cabo Flotante' },
    { type: 'paragraph', text: 'Cabo flotante.' },
    { type: 'paragraph', text: 'Vale recordar, que el cabo del aro salvavidas no debe estar amarrado al barco.' },
    { type: 'paragraph', text: 'Hay dos razones muy simples para ello.' },
    { type: 'paragraph', text: 'Primero, porque si estuviera atado, limitaría la distancia del lanzamiento, impidiendo que el aro alcance al náufrago justo cuando más lo necesita.' },
    { type: 'paragraph', text: 'Y segundo, y no menos importante, porque al seguir el barco su marcha, el cabo arrastraría al salvavidas, dándole un gran disgusto al desafortunado que lo esperaba en el agua.' },
    { type: 'paragraph', text: 'Por eso, el cabo debe poder correr libremente, permitiendo lanzar el aro lo más lejos posible sin riesgo de que quede retenido o arrastrado por la embarcación.' },
    { type: 'paragraph', text: 'El cabo debe ser flotante, flexible y fácilmente manejable, fabricado generalmente en polipropileno trenzado, que combina ligereza, resistencia y flotabilidad natural. El color suele ser naranja o amarillo intenso, para facilitar su visibilidad, y su diámetro ronda los 8 a 10 milímetros, un equilibrio entre resistencia y facilidad de agarre.' },
    { type: 'paragraph', text: 'Desde el punto de vista operativo, conviene que el cabo esté siempre atado al salvavidas, y estibado en una bolsa o un carretel sin nudos que lo traben, de tal forma que al arrojarlo salga inmediatamente limpio, sin necesidad de tener que estar preparándolo previamente.' },
    { type: 'paragraph', text: 'La Baliza Luminosa' },
    { type: 'paragraph', text: 'Baliza luminosa.' },
    { type: 'paragraph', text: 'El salvavidas circular debe ir acompañado también por una baliza luminosa automática, que es un dispositivo que se activa al contacto con el agua y emite una luz intermitente de alta intensidad. Su función es señalar la posición en la que ha quedado el salvavidas, tanto para el náufrago como los rescatistas puedan ubicarlo en la oscuridad de la noche o con baja visibilidad.' },
    { type: 'paragraph', text: 'Estas balizas suelen funcionar con baterías selladas y pueden permanecer encendidas entre dos y más de diez horas, según el modelo. En la mayoría de los barcos, se montan en un soporte combinado con el aro, de manera que, al liberar el salvavidas, la baliza cae junto con él y se activa automáticamente.' },
    { type: 'paragraph', text: 'El Silbato' },
    { type: 'paragraph', text: 'Los silbatos homologados para uso náutico producen un sonido agudo, continuo y muy potente, perceptible a más de 1.000 metros con viento moderado. Además, están diseñados sin bolilla interna, de modo que funcionan incluso mojados o parcialmente sumergidos.' },
    { type: 'paragraph', text: 'Cantidad y Ubicación del Salvavidas a Bordo' },
    { type: 'paragraph', text: 'El aro debe estar a la vista, listo para lanzar en menos de un segundo, sin amarras, cobertores ni trabas. Lo ideal es que esté montado cerca de la posición del timonel, donde alguien pueda alcanzarlo sin moverse demasiado ni perder de vista al náufrago.' },
    { type: 'paragraph', text: 'Información Adicional' },
    { type: 'paragraph', text: 'Hombre al Agua' },
    { type: 'paragraph', text: 'Guía completa sobre qué hacer ante una situación de "hombre al agua": cómo reaccionar, qué hacer con el aro salvavidas y cómo regresar al punto de caída de la víctima para rescatarla.' },
    { type: 'paragraph', text: 'Opciones Alternativas al Salvavidas Circular' },
    { type: 'subtitle', text: 'Salvavidas herradura.' },
    { type: 'paragraph', text: 'Aunque el aro salvavidas tradicional sigue siendo obligatorio por normativa, existen dispositivos alternativos o complementarios que pueden cumplir funciones similares o incluso mejorar la eficacia del rescate, sobre todo en embarcaciones pequeñas o tripulaciones reducidas.' },
    { type: 'paragraph', text: 'Dispositivos de tipo Herradura' },
    { type: 'paragraph', text: 'Son salvavidas de espuma cerrada con forma de “U”, más compactos y fáciles de manipular que el aro salvavidas tradicional.' },
    { type: 'paragraph', text: 'Se lanzan al agua o se colocan sobre el náufrago desde la borda.' },
    { type: 'paragraph', text: 'Suelen utilizarse como dispositivo de rescate, adicional al salvavidas circular.' },
    { type: 'paragraph', text: 'Su principal ventaja es que pueden rodear el torso del náufrago y ofrecer mayor flotabilidad lateral.' },
    { type: 'paragraph', text: 'Rescue Sling' },
    { type: 'paragraph', text: 'Es un sistema de cabo flotante con una gaza grande en el extremo.' },
    { type: 'paragraph', text: 'El náufrago se introduce dentro del lazo y desde a bordo se lo recupera tirando del cabo o con ayuda de una polea. Suele ser útil en veleros donde no siempre es posible detener el movimiento o acercarse al hombre al agua.' },
    { type: 'paragraph', text: 'Jonbuoy' },
    { type: 'paragraph', text: 'Es un equipo desplegable que, en general, se lleva montado en la popa, que al arrojarse al agua y activarse se infla automáticamente formando una especie de boya o pequeño flotador vertical con bandera y luz.' },
    { type: 'paragraph', text: 'Brinda alta visibilidad y una flotabilidad mucho mayor que un aro tradicional, y puede ser utilizado conjuntamente con este.' },
    { type: 'paragraph', text: 'Hay varios modelos, donde unos cumplen con la normativa SOLAS y otros con la ISO 12402.' },
    { type: 'paragraph', text: 'En definitiva, el salvavidas circular sigue siendo uno de los elementos más simples y, al mismo tiempo, más efectivos del equipo de seguridad a bordo.' },
    { type: 'paragraph', text: 'Su correcta disposición, mantenimiento y uso pueden marcar la diferencia entre un susto y una tragedia. Por eso, más allá de cumplir con la normativa, es fundamental mantenerlo siempre listo, visible y libre de obstáculos, y que toda la tripulación sepa exactamente cómo y cuándo utilizarlo: un gesto rápido y certero puede salvar una vida.' },
    { type: 'paragraph', text: 'En la siguiente nota continuaremos entonces con el tratamiento de este los elementos de seguridad de a bordo.' },
    { type: 'paragraph', text: 'Cabuyería: Tipos de cabos y su aplicación.' },
    { type: 'paragraph', text: 'Técnicas de Fondeo.' },
  ],

  quiz: [
    {
      question: '¿Cuál es la función del salvavidas circular?',
      options: ['Servir como asiento', 'Proporcionar flotación de emergencia a una persona en el agua', 'Señalizar el rumbo del barco', 'Proteger el casco de impactos'],
      correctAnswer: 1,
      explanation: 'El salvavidas circular se lanza al agua para proporcionar flotación inmediata a una persona que ha caído por la borda.'
    },
    {
      question: '¿Qué elemento suele llevar asociado el salvavidas circular?',
      options: ['Una driza', 'Una boya luminosa o señal luminosa', 'Un ancla', 'Un cabo de remolque'],
      correctAnswer: 1,
      explanation: 'El salvavidas circular suele llevar asociada una boya luminosa o señal luminosa para facilitar su localización en el agua, especialmente de noche.'
    },
  ]
};