import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'cospas-sarsat',
  title: 'Sistema COSPAS-SARSAT',
  readingTime: 7,

  content: [
    { type: 'title', text: 'Elementos de Seguridad: Sistema COSPAS-SARSAT' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'subtitle', text: 'Sistema COSPAS-SARSAT.' },
    { type: 'paragraph', text: 'En la navegación moderna, la capacidad de solicitar auxilio de manera rápida y efectiva es un factor clave para la seguridad de la vida humana en el mar.' },
    { type: 'paragraph', text: 'Entre los sistemas internacionales destinados a este fin, el COSPAS-SARSAT ocupa un lugar fundamental, ya que permite la detección y localización de señales de socorro emitidas por balizas de emergencia, tanto en el ámbito marítimo como aeronáutico y terrestre.' },
    { type: 'paragraph', text: 'Descripción y Funcionamiento del Sistema COSPAS-SARSAT' },
    { type: 'paragraph', text: 'Un accidente sufrido por un avión de carga de Air France en el Ártico canadiense, en una zona extremadamente remota y de muy difícil acceso, fue el catalizador que dio inicio al sistema COSPAS-SARSAT-' },
    { type: 'paragraph', text: 'Aunque ese avión llevaba una baliza de emergencia, que funcionó correctamente, lamentablemente no existía entonces un sistema satelital capaz de detectar y localizar su señal con rapidez, con lo cual el caso terminó de la peor manera... cuando los rescatistas llegaron finalmente a la zona, ya no había sobrevivientes entre los tripulantes.' },
    { type: 'paragraph', text: 'Este accidente, junto con otros incidentes similares ocurridos en la misma época, tuvo un fuerte impacto en las autoridades aeronáuticas de Canadá y Francia, y contribuyó de manera decisiva a instalar la idea de que no bastaba con que la baliza funcionara... era imprescindible contar con un sistema global, automático y permanente capaz de recibir esas señales en cualquier lugar del planeta.' },
    { type: 'paragraph', text: 'Así fue entonces que, aún en el contexto marcado por la Guerra Fría, Estados Unidos, la Unión Soviética, Canadá y Francia lograron ponerse de acuerdo para desarrollar un proyecto de carácter estrictamente humanitario, integrando sus capacidades espaciales, por un lado, y de búsqueda y rescate por el otro, en un sistema global y permanente, destinado exclusivamente a la localización de señales de socorro y, por ende, a la protección de la vida humana.' },
    { type: 'paragraph', text: 'Su funcionamiento se basa en el uso de radiobalizas de emergencia que, una vez activadas, comienzan a emitir una señal de radio que puede ser detectada y localizada por satélites, permitiendo orientar con precisión el operativo SAR hacia el lugar donde se ha producido la emergencia.' },
    { type: 'paragraph', text: 'El sistema COSPAS-SARSAT se compone de tres segmentos:' },
    { type: 'paragraph', text: 'Segmento Espacial.' },
    { type: 'paragraph', text: 'Está constituido por el conjunto de satélites pertenecientes a las distintas flotas aportadas por los países miembros, así como por sus respectivos planos orbitales.' },
    { type: 'paragraph', text: 'Segmento Terrestre.' },
    { type: 'subtitle', text: 'Radiobalizas.' },
    { type: 'paragraph', text: 'Las radiobalizas son los dispositivos utilizados por los usuarios del sistema y son las encargadas de emitir la señal de socorro al activarse.' },
    { type: 'paragraph', text: 'Existen tres tipos de balizas:' },
    { type: 'paragraph', text: 'EPIRB.' },
    { type: 'paragraph', text: 'EPIRB.' },
    { type: 'paragraph', text: 'Las EPIRB son radiobalizas de emergencia de uso marítimo. Su función principal es transmitir la señal de socorro a ser detectada por los satélites del sistema COSPAS-SARSAT, permitiendo la localización de la emergencia en cualquier lugar del mundo.' },
    { type: 'paragraph', text: 'Estas balizas pueden activarse de manera automática o manual. En la mayoría de las instalaciones, la EPIRB se coloca en un soporte con un dispositivo hidrostático de liberación, que actúa cuando la embarcación se hunde y alcanza cierta profundidad. En ese momento, al sumergirse en el agua, la baliza se libera, asciende a la superficie y se activa. De manera complementaria, la tripulación puede activarla manualmente en situaciones de emergencia, tanto a bordo como luego de haber abandonado la embarcación.' },
    { type: 'paragraph', text: 'Para garantizar su correcto funcionamiento, las EPIRB deben instalarse en el exterior de la embarcación, en un lugar despejado y sin obstrucciones, que permita su libre flotación en caso de hundimiento. No deben guardarse en el interior ni en compartimentos cerrados, ya que ello impediría su liberación automática y anularía su función principal. Durante la navegación, la baliza debe permanecer firmemente asegurada en su soporte, pero accesible para una activación manual si la situación lo requiere.' },
    { type: 'paragraph', text: 'ELT.' },
    { type: 'paragraph', text: 'ELT.' },
    { type: 'paragraph', text: 'En condiciones normales, las ELT permanecen instaladas de manera fija dentro de la aeronave, generalmente en la sección posterior del fuselaje, en un punto estructuralmente protegido pero adecuado para que el dispositivo pueda activarse en caso de impacto. Su activación es normalmente automática, mediante un interruptor de inercia que detecta una desaceleración brusca asociada a un choque o aterrizaje violento. No obstante, las ELT disponen también de un sistema de activación manual, accesible desde la cabina o desde el propio equipo, lo que permite su uso en situaciones de emergencia que no involucren un impacto directo, como un aterrizaje forzoso o un abandono de la aeronave.' },
    { type: 'paragraph', text: 'El correcto funcionamiento de una ELT depende en gran medida de su instalación, del estado de su antena y del mantenimiento periódico del equipo. Una antena dañada o mal conectada puede reducir considerablemente el alcance de la señal, aun cuando la baliza se haya activado. Por este motivo, la normativa aeronáutica exige inspecciones periódicas, pruebas de funcionamiento controladas y el reemplazo de baterías dentro de los plazos establecidos por el fabricante y por la autoridad aeronáutica competente.' },
    { type: 'paragraph', text: 'PLB.' },
    { type: 'paragraph', text: 'PLB.' },
    { type: 'paragraph', text: 'Son dispositivos de tamaño reducido, fácilmente transportables, pensados para ser llevados encima o en el equipo personal. En el ámbito náutico, su uso resulta especialmente valioso para tripulantes que navegan en embarcaciones pequeñas, realizan trabajos en cubierta, navegan en solitario o participan en actividades donde existe riesgo de caída al agua lejos del buque.' },
    { type: 'paragraph', text: 'La activación de una PLB es únicamente manual. En una situación de emergencia, el usuario despliega la antena y acciona el mecanismo de encendido, tras lo cual el equipo comienza a transmitir la señal digital detectable por los satélites de la flota COSPAS-SARSAT.' },
    { type: 'paragraph', text: 'En navegación marítima, las PLB no reemplazan a las EPIRB, sino que actúan como un complemento de seguridad personal.' },
    { type: 'paragraph', text: 'Las balizas, cualquiera sea su tipo, debe estar registradas ante la autoridad competente del país de abanderamiento, vinculando su código de identificación con los datos del buque y de las personas responsables. Este registro es esencial para que los centros de coordinación de rescate puedan verificar rápidamente la autenticidad de la alerta y contactar a los responsables, reduciendo falsas alarmas y acelerando la respuesta.' },
    { type: 'paragraph', text: 'El navegante debe verificar periódicamente el estado general del equipo, realizar las pruebas de funcionamiento indicadas por el fabricante, controlar la fecha de vencimiento de la batería y del dispositivo hidrostático, y asegurarse de que la identificación de la baliza sea claramente legible.' },
    { type: 'paragraph', text: 'Como se ha explicado, estas radiobalizas están preparadas para activarse tanto de forma manual como automática. Una vez activada, la baliza inicia la transmisión de una señal de emergencia con una duración aproximada de 30 segundos, en la frecuencia de 406,025 MHz o 406,028 MHz, con una potencia típica de 5 watts. Esta transmisión se repite aproximadamente cada 50 segundos, hasta el agotamiento de la batería, cuya autonomía suele oscilar entre 24 y 48 horas, dependiendo del modelo y fabricante.' },
    { type: 'paragraph', text: 'Por la frecuencia en la que transmiten, se denomina a las balizas como "Balizas 406".' },
    { type: 'paragraph', text: 'Las EPIRB, destinadas al uso marítimo, deben instalarse preferentemente en el exterior de la embarcación, en un lugar despejado y sin obstrucciones, que permita su libre flotación en caso de hundimiento. Durante la navegación, deben permanecer colocadas en su soporte correspondiente. Es recomendable que tanto la radiobaliza como su sistema de sujeción y liberación automática sean sometidos periódicamente a pruebas de funcionamiento, conforme a lo indicado por el fabricante y por la autoridad de aplicación en la República Argentina.' },
    { type: 'paragraph', text: 'El mensaje transmitido por una radiobaliza contiene información relativa al país en el que fue registrada, un código único de identificación que vincula la señal con la baliza y, cuando el equipo dispone de receptor GPS interno, incluye además las coordenadas de posición geográfica.' },
    { type: 'paragraph', text: 'La señal de emergencia es detectada por los satélites del sistema COSPAS-SARSAT y retransmitida a las estaciones LUT, las cuales procesan la información para determinar la posición de la radiobaliza, ya sea a partir de los datos GPS transmitidos o mediante el cálculo por efecto Doppler.' },
    { type: 'subtitle', text: 'Sistema COSPAS-SARSAT.' },
    { type: 'paragraph', text: 'Un par de párrafos más arriba, el autor dice que se verifica la validez de la alerta.' },
    { type: 'paragraph', text: 'Esto es en realidad un proceso de verificación para descartar falsos positivos... es decir, descartar alertas producidas por error de manipulación de la baliza.' },
    { type: 'paragraph', text: 'Para ello, los operadores del sistema comprueban, en el caso de una embarcación, que efectivamente se encuentre navegando en la zona en la que activó la baliza, e intentan ponerse en contacto con las personas de contacto indicadas al momento de registrarla para comprobar lo mismo.' },
    { type: 'paragraph', text: 'Segmento Argentino COSPAS-SARSAT' },
    { type: 'paragraph', text: 'Área de servicio del ARMCC.' },
    { type: 'paragraph', text: 'Desde el punto de vista operativo, la República Argentina se integró plenamente al sistema COSPAS-SARSAT a fines del año 2002.' },
    { type: 'paragraph', text: 'Desde entonces nuestro país asume la responsabilidad por la detección de alertas y la coordinación de las tareas de búsqueda y rescate en una amplia zona del Atlántico Sur y, en forma conjunta con Chile, en el sector correspondiente a la península Antártica.' },
    { type: 'paragraph', text: 'Desde el punto de vista del navegante, el papel del SASS es fundamental, aunque no siempre visible: es el organismo que recibe primero el pedido de auxilio emitido por una EPIRB, identifica al buque y canaliza la información hacia los medios de rescate adecuados. Por ello, el correcto registro de la baliza, la actualización de los datos y el uso responsable del equipo son aspectos esenciales para que el sistema funcione eficazmente y cumpla su objetivo principal: salvar vidas humanas.' },
    { type: 'paragraph', text: 'Por su  parte, el ARMCC, se encuentra ubicado en la Base Aérea de El Palomar, en la provincia de Buenos Aires, y es operado en forma conjunta por la Fuerza Aérea Argentina y la Armada Argentina.' },
    { type: 'paragraph', text: 'El ARMCC tiene a su cargo las siguientes funciones:' },
    { type: 'paragraph', text: 'Recibir y procesar las señales provenientes de las estaciones terrenas ubicadas en la Base Aérea de El Palomar y en Río Grande, provincia de Tierra del Fuego.' },
    { type: 'paragraph', text: 'Recibir desde los otros MCC las alertas generadas por las balizas registradas en nuestro país.' },
    { type: 'paragraph', text: 'Administrar la Base de Datos Única de Balizas 406 de la Argentina, en la cual se registran las balizas EPIRB, ELT y PLB correspondientes al país.' },
    { type: 'paragraph', text: 'Con esta nota terminamos el recorrido de los elementos de seguridad de a bordo.' },
    { type: 'paragraph', text: 'En la próxima repasaremos los procedimientos de Primeros Auxilios en una embarcación.' },
    { type: 'paragraph', text: 'Mientras tanto, puede entretenerse con este ejercicio.' },
    { type: 'subtitle', text: 'Maniobras y gobierno de la embarcación.' },
    { type: 'paragraph', text: 'Nudos: Tipos de nudos y su aplicación.' },
  ],

  quiz: [
    {
      question: '¿Qué función cumple el sistema COSPAS-SARSAT?',
      options: ['Predecir el clima marítimo', 'Detectar y localizar señales de socorro de radiobalizas', 'Controlar el tráfico marítimo', 'Medir la altura de las olas'],
      correctAnswer: 1,
      explanation: 'COSPAS-SARSAT es un sistema internacional de búsqueda y salvamento que detecta y localiza señales de socorro emitidas por radiobalizas.'
    },
    {
      question: '¿Qué tipo de satélites utiliza COSPAS-SARSAT?',
      options: ['Satélites geoestacionarios solamente', 'Satélites en órbita polar baja y geoestacionarios', 'Satélites de comunicaciones comerciales', 'Satélites meteorológicos'],
      correctAnswer: 1,
      explanation: 'COSPAS-SARSAT utiliza una constelación mixta de satélites en órbita polar baja (LEOSAR) y satélites geoestacionarios (GEOSAR).'
    },
  ]
};