import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'chaleco',
  title: 'Chaleco Salvavidas',
  readingTime: 7,

  content: [
    { type: 'title', text: 'Elementos de Seguridad: El Chaleco Salvavidas' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'subtitle', text: 'Chaleco salvavidas autoinflable con arnés.' },
    { type: 'paragraph', text: 'Los chalecos salvavidas son, probablemente, el elemento de seguridad más importante a bordo de cualquier embarcación, desde un gran buque mercante hasta un velero recreativo o una lancha de pesca. Su función es simple pero vital: mantener a la persona a flote y con la cabeza fuera del agua, aun si se encuentra inconsciente, dándole una oportunidad real de sobrevivir mientras aguarda el rescate. Con el tiempo han evolucionado en materiales, diseño y prestaciones, y hoy existen múltiples tipos adaptados a diferentes condiciones de navegación, normativas e incluso preferencias personales.' },
    { type: 'paragraph', text: 'En la náutica deportiva y recreativa esto cobra especial relevancia, porque el chaleco no solo debe salvar la vida, sino también ser cómodo, permitir libertad de movimiento y ser adecuado para la actividad que se practica, ya sea crucero, regata, pesca o travesías costeras y oceánicas. Por eso es importante conocer las distintas opciones, sus certificaciones, cómo funcionan, cual es el adecuado para la talla de cada uno, y en qué situaciones se recomienda cada opción.' },
    { type: 'paragraph', text: 'Especificaciones Técnicas' },
    { type: 'paragraph', text: 'Los chalecos salvavidas modernos se fabrican considerando principalmente las especificaciones de dos grandes familias normativas: el Convenio SOLAS y las recomendaciones ISO. Estas normas determinan, entre otras cosas, si un chaleco será capaz de girar automáticamente, a una persona que ha caído inconsciente al agua, de tal forma que quede boca arriba con su vía aérea libre, o cuánta flotabilidad real es capaz de proporcionar para sostener a flote el peso de su cuerpo en distintas condiciones.' },
    { type: 'paragraph', text: 'Información Adicional' },
    { type: 'paragraph', text: 'El Convenio SOLAS' },
    { type: 'paragraph', text: 'Este Convenio define, entre otras cosas, las características que deben cumplir los elementos de seguridad que llevamos a bordo de nuestros barcos.' },
    { type: 'paragraph', text: 'En términos generales, los chalecos certificados SOLAS están pensados para el ámbito profesional y la navegación comercial, donde debe cumplirse con estándares de seguridad muy altos. Esos requisitos se trasladan a los chalecos salvavidas de uso deportivo y recreativo, que tienen que cumplir entonces, y entre otros, con los siguientes:' },
    { type: 'paragraph', text: 'No debe producir dudas acerca de si se lo está colocando al derecho o al revés.' },
    { type: 'paragraph', text: 'Lo que se busca es qué, ante la emergencia, el usuario pueda tomar un chaleco y colocárselo correctamente de forma intuitiva, sin necesidad de haber recibido instrucciones previamente para hacerlo.' },
    { type: 'paragraph', text: 'Permitir lanzarse al agua con el chaleco ya puesto, desde una altura de al menos 4,5 metros sin lesionarse y sin que el chaleco quede mal colocado o sufra daños.' },
    { type: 'paragraph', text: 'Permitir al usuario nadar una distancia corta y subir a una embarcación sin otras dificultades que las de tener que adaptarse al volumen del chaleco.' },
    { type: 'paragraph', text: 'Debe lograr dar vuelta en el agua el cuerpo de una persona desvanecida desde cualquier posición, hasta que la cabeza y, particularmente, las vías respiratorias, queden fuera del agua, en no más de 5 segundos.' },
    { type: 'paragraph', text: 'Su flotabilidad no debe reducirse en más de un 5% después de haber pasado 24 horas de inmersión en agua dulce.' },
    { type: 'paragraph', text: 'Deben ser de colores llamativos con detalles reflectantes, contar con una luz destellante y un silbato  sujeto por un cordón.' },
    { type: 'paragraph', text: 'Composición corporal.' },
    { type: 'paragraph', text: 'Le explico cómo entender esto de los Newtons.' },
    { type: 'paragraph', text: 'El cuerpo humano está compuesto más o menos así:' },
    { type: 'paragraph', text: '80% de agua, que por lo tanto tiene flotabilidad neutra cuando el cuerpo está sumergido en el agua.' },
    { type: 'paragraph', text: '15% de grasa corporal, que tiene flotabilidad positiva.' },
    { type: 'paragraph', text: '5% de materiales pesados, que agregan flotabilidad negativa.' },
    { type: 'paragraph', text: 'En función de esos números, si tuviésemos que construir un chaleco salvavidas para lograr mantener a flote a una persona que ha caído al agua, tendríamos que poner la prioridad en compensar, como mínimo, ese 5% de componentes pesados que tiende a hundirla, con algún material que aporte el 5% de flotabilidad positiva. Luego, de allí en mas, todo lo que se agregue en términos de flotabilidad positiva, será en beneficio de que el náufrago tenga más o menos de su cuerpo fuera del agua' },
    { type: 'paragraph', text: 'Llevemos esto a un ejemplo práctico:' },
    { type: 'paragraph', text: 'Si tomáramos, por ejemplo, a una persona de 100 kilos de peso, necesitaríamos compensar unos 5 kilos de flotabilidad negativa,  ¿no?' },
    { type: 'paragraph', text: '= Flotabilidad (kilos)' },
    { type: 'paragraph', text: '= peso de la persona x 5% =' },
    { type: 'paragraph', text: '= 100 kg x 5% =' },
    { type: 'paragraph', text: '= 5 kg' },
    { type: 'paragraph', text: '"Flotabilidad (kilos)", es el peso, en este caso en kilos, que debe ser compensado para lograr la flotabilidad.' },
    { type: 'paragraph', text: 'luego, si un Newton equivale a 0,1 kilogramo, necesitaríamos una fuerza de flotabilidad de 50 Newtowns (50N) para compensar esos 5 Kg de peso negativo.' },
    { type: 'paragraph', text: 'Flotabilidad (Newtons)' },
    { type: 'paragraph', text: '= Flotabilidad (kilos) x 0,1 Newton =' },
    { type: 'paragraph', text: '= 5 kg x 0,1 Newton =' },
    { type: 'paragraph', text: '= 50 Newtons → 50N' },
    { type: 'subtitle', text: 'Tipos de Chalecos Salvavidas' },
    { type: 'paragraph', text: 'Los chalecos salvavidas que se utilizan en la náutica deportiva pueden dividirse, en líneas generales, en tres grandes familias, cada una con un propósito y un nivel de protección diferente.' },
    { type: 'paragraph', text: 'DAF - Dispositivos de Ayuda a la Flotación' },
    { type: 'paragraph', text: 'DAF - Dispositivos de Ayuda a la Flotación.' },
    { type: 'paragraph', text: 'Estos chalecos se caracterizan más que nada por ser anatómicos y cómodos de usar. Ayudan a mantenerse a flote siempre y cuando el usuario esté consciente y puede colaborar en su propio rescate, pero no están diseñados para girar el cuerpo boca arriba si la persona queda inconsciente. Por eso se los considera elementos de ayuda a la flotación, y no chalecos salvavidas.' },
    { type: 'subtitle', text: 'Chalecos Salvavidas Clásicos' },
    { type: 'subtitle', text: 'Chalecos tradicionales tipo "poncho".' },
    { type: 'paragraph', text: 'Los chalecos clásicos tipo "poncho", que se colocan pasando la cabeza por su centro, y que son lo que la mayoría imagina cuando piensa en un salvavidas tradicional. Aquí es donde la normativa marca la diferencia, pues dentro de este grupo hay modelos certificados bajo estándar SOLAS, pensados para entornos profesionales o recreativos de mayor riesgo y otros NO SOLAS en los que se relajan ciertos parámetros.' },
    { type: 'paragraph', text: 'La flotabilidad de estos chalecos proviene también de espumas de celda cerrada, generalmente polietileno expandido o PVC espumado de mayor densidad, distribuidas de asimétricamente, de tal forma que entregue más empuje en el frente y cuello, y menos en la espalda. Esa geometría es la que logra que el cuerpo se de vuelta en el agua, quedando boca arriba. La estructura exterior suele ser de nylon o poliéster muy resistente, a veces con refuerzos tipo Cordura y con cintas reflectivas certificadas, silbato y paneles de alto contraste para búsqueda nocturna o con mala visibilidad. Las cinchas de sujeción son más robustas que en un DAF y se regulan mediante hebillas de plástico técnico o acero inoxidable, buscando un ajuste firme que no permita que el chaleco se mueva al caer al agua.' },
    { type: 'paragraph', text: 'Comparados con los chalecos autoinflables, que le explicarán a continuación, los chalecos clásicos son claramente más voluminosos y algo menos cómodos, pero tienen una ventaja determinante: funcionan siempre, sin depender de cartuchos, sensores, mantenimiento especializado o verificación previa.' },
    { type: 'subtitle', text: 'Chalecos Salvavidas Autoinflables' },
    { type: 'subtitle', text: 'Chalecos autoinflables.' },
    { type: 'paragraph', text: 'Los chalecos autoinflables son hoy los favoritos de los navegantes de crucero y regata pues reúnen lo mejor de ambos mundos: son ergonómicamente cómodos, se usan sin sentirlos y permiten moverse en cubierta sin dificultades, y entregan la flotabilidad necesaria cuando realmente se la necesita.' },
    { type: 'paragraph', text: 'Dentro de esta familia existen versiones de inflado manual, inflado automático por pastilla hidrosoluble o mecánicas activadas por la inmersión, además de sistemas mixtos que permiten tanto el inflado manual como el automático.' },
    { type: 'paragraph', text: 'Este tipo de chalecos cumple también en su gran mayoría con los requisitos del Convenio SOLAS.' },
    { type: 'paragraph', text: 'En cuanto a su fabricación, a diferencia de los chalecos tradicionales, el material interno no es espuma, sino una cámara de flotación inflable, fabricada de poliuretano o TPU termosellado, que se lleva plegada dentro de una funda montada alrededor del cuello de un arnés de tres o cinco puntos de sujeción, según el modelo. Ese arnés tiene también el punto de conexión de la línea de seguridad, completando así la doble función de chaleco salvavidas y arnés de seguridad.' },
    { type: 'paragraph', text: 'Información Adicional' },
    { type: 'paragraph', text: 'El Arnés y la Línea de Seguridad' },
    { type: 'paragraph', text: 'Todo lo esencial sobre el arnés y la línea de seguridad: para qué sirven, que diferentes versiones existen, y cómo deben ser utilizados para garantizar la seguridad.' },
    { type: 'paragraph', text: 'La cámara de flotación permanece plegada y comprimida en su funda hasta el momento de su activación manual o automática.' },
    { type: 'paragraph', text: 'El inflado manual se realiza soplando a través de un tubo conectado a la cámara de flotación, y el inflado automático lo inicia un mecanismo que al activarse perfora un cartucho de CO₂ cuyo contenido infla la cámara de flotación en pocos segundos. Ese mecanismo se dispara, dependiendo el modelo de chaleco, o bien cuando una pastilla hidrosoluble se deshace al entrar en contacto con el agua, dejando que la aguja se dispare, o bien mediante un sensor de profundidad que suelta la aguja cuando se ha sumergido en al menos 10 centímetros de agua. La desventaja de la pastilla hidrosoluble es que puede disolverse, activando el inflado del chaleco, si este comienza a mojarse con el oleaje o lluvias intensas durante largas horas. En ese sentido, el mecanismo de sensor de profundidad no produce estos "falsos positivos" pero es más caro.' },
    { type: 'paragraph', text: 'Claramente este tipo de chalecos es el preferido por los navegantes, básicamente porque son muy cómodos, ofrecen un nivel de flotabilidad altísimo, y porque en el mismo equipo se integra el chaleco salvavidas y el arnés de seguridad, simplificando la tarea al tener que preparase para salir al cockpit.' },
    { type: 'paragraph', text: 'Mantenimiento de los Chalecos Salvavidas' },
    { type: 'paragraph', text: 'La durabilidad de un chaleco salvavidas depende tanto de su material de construcción como del cuidado que reciba.' },
    { type: 'paragraph', text: 'Los modelos de flotación sólida, como los DAF o los clásicos de espuma, son prácticamente indestructibles, su flotabilidad no disminuye con el tiempo siempre que la espuma no se deteriore, y desde el punto de vista funcional no dependen de mecanismos ni cartuchos que haya que reemplazar. Sin embargo, el sol, la humedad y el salitre degradan progresivamente la tela exterior y las costuras. Por eso se recomienda enjuagarlos con agua dulce tras cada uso, secarlos a la sombra, y almacenarlos en un lugar ventilado. Si el material se vuelve quebradizo o amarillento, o si pierde su forma original, conviene reemplazarlo.' },
    { type: 'paragraph', text: 'Los autoinflables, en cambio, requieren mantenimiento más meticuloso, siguiendo idealmente las recomendaciones de cada fabricante.' },
    { type: 'paragraph', text: 'A modo de conclusión, el chaleco salvavidas no es solo un requisito reglamentario, sino un elemento esencial de supervivencia.' },
    { type: 'paragraph', text: 'Esperamos que esta explicación le sirva para guiarlo luego en la elección del modelo adecuado para su tipo de navegación.' },
    { type: 'paragraph', text: 'En la siguiente nota continuaremos entonces con el tratamiento de este los elementos de seguridad de a bordo.' },
    { type: 'paragraph', text: 'Cabuyería: Tipos de cabos y su aplicación.' },
    { type: 'paragraph', text: 'Técnicas de Fondeo.' },
  ],

  quiz: [
    {
      question: '¿Qué función cumple el chaleco salvavidas?',
      options: ['Proteger del frío', 'Mantener a flote a una persona inconsciente con la vía aérea fuera del agua', 'Sujetar al tripulante al barco', 'Señalizar la posición del barco'],
      correctAnswer: 1,
      explanation: 'El chaleco salvavidas está diseñado para mantener a flote a una persona, incluso inconsciente, manteniendo sus vías respiratorias fuera del agua.'
    },
    {
      question: '¿Cuándo debe usarse el chaleco salvavidas?',
      options: ['Solo en emergencias', 'Siempre que se esté en cubierta o exista riesgo de caída al agua', 'Solo de noche', 'Solo cuando el capitán lo ordene'],
      correctAnswer: 1,
      explanation: 'El chaleco debe usarse siempre que se esté en cubierta o exista riesgo de caída al agua, independientemente de las condiciones meteorológicas.'
    },
  ]
};