import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'servicio-movil-maritimo',
  title: 'Servicio Móvil Marítimo',
  readingTime: 28,

  content: [
    { type: 'title', text: 'Servicio Móvil Marítimo' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'paragraph', text: 'En este capítulo abordaremos los principios básicos del GMDSS, los tipos de llamadas: socorro, urgencia y seguridad, el uso correcto de los equipos de radio y las buenas prácticas operativas que todo navegante deportivo y recreativo debe conocer y aplicar.' },
    { type: 'paragraph', text: 'Radiocomunicaciones.' },
    { type: 'paragraph', text: 'Algo de historia, para los lectores curiosos.' },
    { type: 'paragraph', text: 'Reconociendo esta situación, la OMI - Organización Marítima Internacional promovió una serie de iniciativas orientadas a desarrollar procedimientos de emergencia. En este marco, en 1979 se adoptó el Convenio Internacional SAR cuyo objetivo fue establecer un protocolo común a nivel mundial para la organización y coordinación de las operaciones de búsqueda y rescate en el mar.' },
    { type: 'paragraph', text: 'El Convenio SOLAS establece, entre otras obligaciones, que el capitán de todo buque que, hallándose en navegación, reciba una señal indicando que otra embarcación, una aeronave, un bote salvavidas o una persona se encuentran en peligro, deberá acudir a su auxilio con la mayor rapidez posible, siempre que ello no implique un riesgo grave para su propio buque o tripulación.' },
    { type: 'paragraph', text: 'En este contexto, la UIT - Unión Internacional de Telecomunicaciones, a través de sus Conferencias Mundiales de Radiocomunicaciones, estableció los criterios normativos y los protocolos operativos que deben seguir los buques y las estaciones costeras en materia de radiocomunicaciones marítimas, los cuales fueron adoptados por la República Argentina y son de aplicación también para la navegación civil y deportiva.' },
    { type: 'paragraph', text: 'Sistemas de Comunicaciones' },
    { type: 'paragraph', text: 'Según su definición general, la comunicación es la transmisión de información de un punto a otro. En términos tecnológicos, para que esa comunicación sea posible es necesario contar con un sistema emisor, un receptor y un canal de comunicación, que no es otra cosa que el medio utilizado para transportar la información entre ambos extremos.' },
    { type: 'paragraph', text: 'La transmisión de la información se realiza mediante la codificación, en el lado emisor, de un conjunto de señales de acuerdo con un protocolo previamente acordado entre las partes. Dichas señales se transmiten alterando el medio que actúa como canal de comunicación y se propagan a través de él hasta alcanzar al receptor, quien al recibirlas deberá decodificarlas para interpretar su contenido.' },
    { type: 'paragraph', text: 'A su vez, los canales de comunicaciones se definen por el siguiente conjunto de características:' },
    { type: 'paragraph', text: 'El Medio de Transmisión.' },
    { type: 'paragraph', text: 'Que puede ser la atmósfera, el agua, el vacío, o un conductor físico como un cable metálico o una fibra óptica.' },
    { type: 'paragraph', text: 'El Tipo de Señal Utilizada.' },
    { type: 'paragraph', text: 'Por ejemplo, señales electromagnéticas, sonoras o luminosas.' },
    { type: 'paragraph', text: 'Completando lo anterior, puede decirse que las señales son perturbaciones que se propagan a través de un medio a lo largo del tiempo, y que pueden representarse mediante funciones matemáticas continuas en las que varían su amplitud y su período.' },
    { type: 'paragraph', text: 'Un pulso continuo de audio, de luz o de corriente eléctrica son ejemplos de señales portadoras. Sobre estas señales se codifica la información haciendo variar alguna de sus características, como el volumen del sonido, la intensidad del haz luminoso, o la amplitud o frecuencia de una corriente eléctrica.' },
    { type: 'paragraph', text: 'La Velocidad de Transmisión.' },
    { type: 'paragraph', text: 'Representa el tiempo que tarda la señal en desplazarse de un extremo a otro del canal.' },
    { type: 'paragraph', text: 'El Ancho de Banda.' },
    { type: 'paragraph', text: 'Define el caudal de información que puede transmitirse por unidad de tiempo.' },
    { type: 'paragraph', text: 'Las Distancia Máxima de Alcance.' },
    { type: 'paragraph', text: 'Toda señal sufre atenuaciones a medida que se propaga a través del medio, degradando la calidad de la señal, al punto de hacerla incomprensible.' },
    { type: 'paragraph', text: 'La distancia máxima de alcance define el punto más remoto al que una señal puede propagarse sin dejar de ser comprensible.' },
    { type: 'paragraph', text: '¿Recuerda esas viejas películas de guerra en las que desde un barco le pasaban mensajes a otro haciendo destellos con una lámpara?' },
    { type: 'paragraph', text: 'Lampara de señales.' },
    { type: 'paragraph', text: 'El canal de comunicación era simplemente el aire, en la oscuridad de la noche, a través del cual se propagaba el haz de luz.' },
    { type: 'paragraph', text: 'Esos pulsos de luz son los que alteran el medio, es decir la oscuridad de la noche, de tal forma que pudiesen ser percibidos e interpretados desde el otro barco.' },
    { type: 'paragraph', text: 'En la navegación civil y deportiva se emplean principalmente sistemas de comunicación basados en ondas electromagnéticas, comúnmente denominadas ondas de radio, las cuales se describen mediante una serie de parámetros básicos:' },
    { type: 'paragraph', text: 'Amplitud de onda.' },
    { type: 'paragraph', text: 'Es el valor máximo del desplazamiento de la onda respecto de su posición de equilibrio.' },
    { type: 'paragraph', text: 'Longitud de onda.' },
    { type: 'paragraph', text: 'Es la distancia entre dos puntos consecutivos de la onda que se encuentran en el mismo estado de vibración, como dos crestas o dos valles sucesivos.' },
    { type: 'paragraph', text: 'Se representa mediante la letra griega "λ" (lambda).' },
    { type: 'paragraph', text: 'Período.' },
    { type: 'paragraph', text: 'Es el tiempo que tarda la onda en recorrer una distancia igual a una longitud de onda.' },
    { type: 'paragraph', text: 'Frecuencia.' },
    { type: 'paragraph', text: 'Parámetros.' },
    { type: 'paragraph', text: 'El Espectro Radioeléctrico' },
    { type: 'paragraph', text: 'El espectro radioeléctrico es la parte del espectro electromagnético que comprende el conjunto de frecuencias utilizadas para la transmisión de información mediante ondas de radio. Forma parte de un espectro mucho más amplio que incluye, entre otras, la luz visible, los rayos infrarrojos, los rayos X y los rayos gamma, cuyas frecuencias alcanzan valores extremadamente elevados.' },
    { type: 'paragraph', text: 'Espectro radioeléctrico.' },
    { type: 'paragraph', text: 'Debido a su gran amplitud, el espectro radioeléctrico se divide en bandas de frecuencia, a cada una de las cuales se le asigna un nombre en función de su longitud de onda o de su rango de frecuencias. Esta clasificación permite referirse a ellas con mayor facilidad y ordenar su utilización. Las bandas empleadas para las radiocomunicaciones abarcan desde los 3 kHz hasta los 30 GHz, y que se muestran en el siguiente cuadro.' },
    { type: 'paragraph', text: 'banda' },
    { type: 'paragraph', text: 'propagación' },
    { type: 'paragraph', text: 'rango' },
    { type: 'paragraph', text: 'uso' },
    { type: 'paragraph', text: 'VLF' },
    { type: 'paragraph', text: '(Very Low Frequency)' },
    { type: 'paragraph', text: 'Terrestre.' },
    { type: 'paragraph', text: '3 kHz a 30 Kkz' },
    { type: 'paragraph', text: 'Navegación marítima.' },
    { type: 'paragraph', text: 'LF (Low Frequency)' },
    { type: 'paragraph', text: 'Terrestre.' },
    { type: 'paragraph', text: '30 KHz a 300 KHz' },
    { type: 'paragraph', text: 'Navegación y comunicaciones en AM (amplitud modulada).' },
    { type: 'paragraph', text: 'MF (Mid Frequency)' },
    { type: 'paragraph', text: 'Terrestre e ionosférica.' },
    { type: 'paragraph', text: '300 KHz a 3 MHz' },
    { type: 'paragraph', text: 'Emisoras de radio en AM (amplitud modulada).' },
    { type: 'paragraph', text: 'HF (High Frequency)' },
    { type: 'paragraph', text: 'Ionosférica.' },
    { type: 'paragraph', text: '3 MHz a 30 MHz' },
    { type: 'paragraph', text: 'Emisoras de radio en FM (frecuencia modulada), señales de TV, banda urbana.' },
    { type: 'paragraph', text: 'VHF (Very High Frequency)' },
    { type: 'paragraph', text: 'Directa en la línea del horizonte.' },
    { type: 'paragraph', text: '30 MHz a 300 MHz' },
    { type: 'subtitle', text: 'Señales de TV y emisoras de radio en FM (frecuencia modulada.' },
    { type: 'paragraph', text: 'UHF (Ultra High Frequency)' },
    { type: 'paragraph', text: 'Ghz a 30 GHz' },
    { type: 'subtitle', text: 'Señales de TV y emisoras de radio en FM (frecuencia modulada.' },
    { type: 'paragraph', text: 'A su vez, cada banda de frecuencias se subdivide en "canales", donde cada canal corresponde a una frecuencia determinada, o a un par de frecuencias, según el modo en que se realice la comunicación. De acuerdo con esta característica, los canales pueden clasificarse en:' },
    { type: 'subtitle', text: 'Canales Símplex.' },
    { type: 'paragraph', text: 'Permiten la transmisión en un solo sentido a la vez.' },
    { type: 'paragraph', text: 'Los interlocutores transmiten de manera alternada utilizando una única frecuencia.' },
    { type: 'paragraph', text: 'La ventaja de utilizar canales simplex en equipos VHF es claramente económica, puesto que, por un lado, al trabajar con una única frecuencia, no solo se reduce el costo de fabricación del equipamiento, sino que además consumen menos energía, haciendo que sus baterías duren mucho más tiempo, lo cual es vital en la náutica. Lo mismo sucede al utilizar protocolos manuales, puesto que para hacerlos automáticos deberían agregarse más componentes a los equipos, encareciéndolos.' },
    { type: 'paragraph', text: 'Ese protocolo de "invitación a transmitir" es manual, puesto que es el operador que se encuentra transmitiendo quien le cede el turno a su contraparte diciéndole por ejemplo "cambio", o "adelante".' },
    { type: 'paragraph', text: 'Los sistemas de comunicaciones más complejos utilizan protocolos automáticos, donde el permiso para transmitir se maneja sobre un canal 	de control separado o con un mensaje específico.' },
    { type: 'subtitle', text: 'Canales Dúplex.' },
    { type: 'paragraph', text: 'Utilizan dos frecuencias distintas, una para transmitir y otra para recibir, lo que permite la comunicación simultánea en ambos sentidos.' },
    { type: 'subtitle', text: 'Canales Semidúplex.' },
    { type: 'paragraph', text: 'Utilizan dos frecuencias distintas, una para transmitir y otra para recibir, pero no permiten la comunicación simultánea en ambos sentidos.' },
    { type: 'paragraph', text: 'En este tipo de canales, mientras un interlocutor transmite, el otro solo puede recibir, debiendo esperar a que la transmisión finalice para responder.' },
    { type: 'paragraph', text: 'Este modo es habitual en las comunicaciones entre buques y estaciones costeras, donde la estación costera transmite en una frecuencia diferente a la utilizada por el buque, pero la conversación se realiza de manera alternada.' },
    { type: 'subtitle', text: 'Canales VHF del Servicio Móvil Marítimo' },
    { type: 'paragraph', text: 'Como norma general, en los equipos de VHF todos los canales se encuentran preestablecidos en sus correspondientes frecuencias para facilitar su operación, y disminuir las posibilidades de error que existirían en caso de tener que seleccionar una frecuencia manualmente.' },
    { type: 'subtitle', text: 'Alcance de las Señales de Radio' },
    { type: 'paragraph', text: 'Desde el punto de vista conceptual, el alcance de las señales de radio depende de su frecuencia, de su longitud de onda y de la forma en que dicha señal interactúa con el entorno, ya sea difractándose, reflejándose o propagándose a través de la atmósfera.' },
    { type: 'paragraph', text: 'Para comprender esto, es necesario partir del hecho de que las ondas electromagnéticas se caracterizan por vibrar a diferentes frecuencias y que, a mayor frecuencia, menor es su longitud de onda, dado que todas ellas se propagan a una velocidad prácticamente constante de 300.000 kilómetros por segundo, es decir, a la velocidad de la luz en el vacío.' },
    { type: 'subtitle', text: 'Frecuencias bajas – "LF" Long Frequency' },
    { type: 'paragraph', text: 'Esto significa que, si se considera por ejemplo una señal de 300 kHz, se está indicando que la onda vibra 300.000 veces por segundo.' },
    { type: 'paragraph', text: 'Entonces, dado que dicha onda avanza a 300.000 kilómetros por segundo, cada ciclo tendrá una longitud aproximada de 1 kilómetro. En este caso se habla, por lo tanto, de ondas muy largas, o de "Long Frecuency", abreviado como "LF", que en radiocomunicaciones se utilizan para transmitir a grandes distancias.' },
    { type: 'paragraph', text: 'Debido a su gran longitud de onda, estas señales pueden verse afectadas por fenómenos de difracción, permitiéndoles rodear obstáculos geográficos como montañas o accidentes naturales y alcanzar zonas que no se encuentran en línea de vista directa.' },
    { type: 'subtitle', text: 'Frecuencias Medias y Altas – "MF" Mid Frecuency y "HF" High Frequency' },
    { type: 'subtitle', text: 'Equipo de banda lateral única.' },
    { type: 'paragraph', text: 'Estas frecuencias presentan la particularidad de ser refractadas o reflejadas por las capas altas de la atmósfera, especialmente la ionósfera, lo que permite que la señal se propague a miles de kilómetros mediante sucesivas reflexiones entre la superficie de la Tierra y dicha capa atmosférica, con una atenuación relativamente baja. Por esta razón, las radios BLU fueron durante décadas el principal medio de comunicación de los buques de altura.' },
    { type: 'paragraph', text: 'Sin embargo, la capacidad de reflexión de la ionósfera no es constante, ya que depende de factores como la hora del día, la actividad solar, la estación del año y la latitud. Durante el día suelen propagarse mejor las frecuencias más altas, mientras que por la noche resultan más eficaces las frecuencias más bajas.' },
    { type: 'paragraph', text: 'Por este motivo, los servicios de radio marítimos y las estaciones costeras suelen trabajar con tablas horarias de propagación, que indican qué frecuencias conviene utilizar en cada franja del día para lograr la mejor cobertura posible. Los operadores de radio a bordo consultan estas tablas para seleccionar la banda más adecuada según la hora y la distancia a la estación con la que desean comunicarse.' },
    { type: 'subtitle', text: 'Frecuencias muy altas – "VHF" Very High Frequency' },
    { type: 'subtitle', text: 'Equipos de VHF.' },
    { type: 'paragraph', text: 'En la navegación civil y deportiva, los sistemas de radio utilizados habitualmente operan en la banda de VHF, entre 156,0 MHz y 174,0 MHz, lo que corresponde a longitudes de onda del orden de los 2 metros, conocidas como ondas métricas.' },
    { type: 'paragraph', text: 'A estas frecuencias, la señal ya no se refleja en la ionósfera ni presenta difracción significativa, por lo que se propaga esencialmente en línea recta. Como consecuencia, su alcance queda limitado por la curvatura de la Tierra, quedando fuera de cobertura cualquier antena receptora que se encuentre por debajo del horizonte radioeléctrico.' },
    { type: 'paragraph', text: 'Dicho de otra forma. el alcance efectivo de una comunicación en VHF dependerá entonces, y principalmente, de la altura de las antenas de las estaciones que participan de la comunicación. A medida que aumenta la distancia entre las antenas, estas deben ganar altura para mantenerse en línea de vista con las otras por sobre el nivel del horizonte radioeléctrico.' },
    { type: 'paragraph', text: 'Particularmente en lo que hace al Servicio Móvil Marítimo, debe tenerse e cuenta que existen límites de la potencia para emitir en el rango de VHF, por lo tanto aun cuando haya visibilidad entre antenas en muy largas distancia, la señal se degradará.' },
    { type: 'subtitle', text: 'Frecuencias Ultra Altas – "UHF" Ultra High Frequency' },
    { type: 'subtitle', text: 'Equipos de UHF.' },
    { type: 'paragraph', text: 'Al aumentar aún más la frecuencia se ingresa en la banda de UHF, cuyas señales se propagan de forma estrictamente rectilínea. En este caso, la única manera de extender su alcance es mediante el uso de antenas repetidoras, que reciben la señal y la retransmiten desde una ubicación elevada.' },
    { type: 'subtitle', text: 'Microondas' },
    { type: 'paragraph', text: 'Por encima de estas bandas se encuentran las ondas cuyas longitudes van desde los centímetros hasta los milímetros, conocidas como microondas. Estas se utilizan tanto en los radares marítimos como en aplicaciones domésticas e industriales.' },
    { type: 'paragraph', text: 'Las microondas se propagan en haces muy concentrados, transportando su energía de manera altamente direccional, lo que permite una gran precisión, pero exige una clara alineación entre emisor y receptor.' },
    { type: 'subtitle', text: 'Modos de Propagación de las Señales de Radio' },
    { type: 'paragraph', text: 'Según la frecuencia utilizada, las señales de radio pueden propagarse de distintas maneras. En el ámbito marítimo, los dos modos más relevantes desde el punto de vista histórico y conceptual son la onda terrestre y la onda refractada.' },
    { type: 'subtitle', text: 'Onda terrestre' },
    { type: 'paragraph', text: 'Comprende a la porción de la señal de radio que se propaga siguiendo la curvatura de la superficie de la Tierra, desplazándose próxima al suelo o al mar.' },
    { type: 'paragraph', text: 'Este modo de propagación es característico de las frecuencias bajas, correspondientes a ondas largas, como las bandas de "LF" y "MF". Gracias a su gran longitud de onda, estas señales pueden difractarse alrededor de obstáculos naturales y mantener cobertura a grandes distancias, especialmente sobre superficies conductoras como el agua de mar.' },
    { type: 'paragraph', text: 'La onda terrestre fue ampliamente utilizada en los primeros sistemas de radiocomunicaciones marítimas, y constituyó durante muchos años el principal medio de enlace a media y larga distancia.' },
    { type: 'subtitle', text: 'Onda Refractada' },
    { type: 'paragraph', text: 'También conocida como onda ionosférica, refiere a la señal que, al alcanzar las capas altas de la atmósfera, es refractada o reflejada parcialmente por la ionósfera, regresando nuevamente hacia la superficie terrestre.' },
    { type: 'paragraph', text: 'Este tipo de propagación se produce principalmente en las bandas de "HF", como las utilizadas por los sistemas de BLU en los buques comerciales. Mediante sucesivos "saltos" entre la ionósfera y la superficie de la Tierra, estas señales pueden recorrer miles de kilómetros, permitiendo comunicaciones de muy largo alcance.' },
    { type: 'paragraph', text: 'La eficacia de la propagación ionosférica depende de diversos factores, como la hora del día, la estación del año, y la actividad solar.' },
    { type: 'subtitle', text: 'Propagación en Línea de Vista Directa' },
    { type: 'paragraph', text: 'En las bandas de "VHF", "UHF" y de "microondas", las señales ya no utilizan ni la onda terrestre ni la onda refractada. En estos casos, la propagación es esencialmente en línea de vista directa, siguiendo una trayectoria prácticamente recta.' },
    { type: 'paragraph', text: 'Por esta razón, el alcance de las comunicaciones en estas bandas queda limitado por la curvatura de la Tierra y por la altura relativa de las antenas, siendo necesario recurrir a antenas elevadas, repetidoras o enlaces intermedios para extender la cobertura.' },
    { type: 'paragraph', text: 'Este es el modo de propagación característico de las comunicaciones en VHF marino, ampliamente utilizadas en la navegación civil y deportiva.' },
    { type: 'subtitle', text: 'Tipos de propagación de las señales de radio.' },
    { type: 'subtitle', text: 'Alcance de los Equipos de Radio VHF' },
    { type: 'paragraph', text: 'En función de las características de propagación ya comentadas, los sistemas de comunicaciones basados en VHF operan de manera confiable dentro del radio de alcance al horizonte radioeléctrico de la antena instalada en el buque. Si bien este alcance es relativamente corto en comparación con el de los sistemas que operan en MF o HF, resulta más que suficiente para la navegación civil y deportiva, que habitualmente se desarrolla en zonas costeras, ríos y estuarios.' },
    { type: 'paragraph', text: 'De esto se desprende que las comunicaciones en VHF solo podrán establecerse con aquellas estaciones que se encuentren dentro de ese rango de distancia y en línea de vista. Obstáculos entre los interlocutores, tales como arboledas densas, montes, cerros o edificaciones elevadas, pueden interferir o bloquear la propagación de la señal, reduciendo sensiblemente el alcance efectivo.' },
    { type: 'paragraph', text: 'Asimismo, dado que la banda de VHF es un recurso compartido, si varios buques transmiten simultáneamente en un mismo canal, sus señales se interferirán entre sí, siendo audible únicamente aquella que llegue con mayor potencia al receptor. Para gestionar esta situación, la mayoría de los equipos VHF permite seleccionar el nivel de potencia de transmisión. Emitir con potencia excesiva hacia estaciones cercanas no solo resulta innecesario, sino que puede provocar interferencias a comunicaciones legítimas de otros buques situados a mayor distancia, sin aportar beneficio alguno a la comunicación propia.' },
    { type: 'paragraph', text: 'Atento a esto, el Servicio Móvil Marítimo establece que la potencia máxima de los transmisores VHF instalados a bordo de embarcaciones no debe exceder los 25 watts. En la práctica, siempre que sea posible, debe utilizarse la menor potencia necesaria para establecer una comunicación clara.' },
    { type: 'paragraph', text: 'El control de la potencia de transmisión presenta además una ventaja adicional: permite reducir el consumo eléctrico, que es un aspecto particularmente relevante en embarcaciones con capacidad energética limitada.' },
    { type: 'paragraph', text: 'Para asegurar una buena calidad de transmisión y recepción, es fundamental prestar especial atención a la instalación de la antena. En términos generales, esta debe montarse lo más alta posible, ya que, como ya se explicó, la altura de la antena influye en el alcance del VHF. En los veleros, el emplazamiento óptimo suele ser el tope del mástil. El cable coaxial que conecta la antena con el equipo también reviste gran importancia: un cable de baja calidad, deteriorado o instalado de manera deficiente puede provocar pérdidas significativas de señal.' },
    { type: 'subtitle', text: 'Llamada en VHF.' },
    { type: 'subtitle', text: 'Servicio Móvil Marítimo' },
    { type: 'paragraph', text: 'El Servicio Móvil Marítimo es aquel mediante el cual se aseguran las comunicaciones radioeléctricas entre estaciones costeras y estaciones de barco, así como las comunicaciones de buque a buque. También se consideran incluidas dentro de este servicio las estaciones de embarcaciones de salvamento y las radiobalizas de localización de siniestros.' },
    { type: 'paragraph', text: 'Luego, los estados miembros, como la República Argentina, adoptan estas definiciones y las implementan mediante sus organismos nacionales competentes, en este caso la Prefectura Naval Argentina.' },
    { type: 'paragraph', text: 'De manera análoga, el Reglamento de Radiocomunicaciones define también el Servicio Móvil Aeronáutico, destinado a asegurar las comunicaciones radioeléctricas entre aeronaves y estaciones aeronáuticas, así como entre aeronaves entre sí, cuando corresponde.' },
    { type: 'paragraph', text: 'En la República Argentina, la Prefectura Naval Argentina es la autoridad competente para proveer y administrar los servicios de comunicaciones vinculados con la seguridad de la navegación y la salvaguarda de la vida humana en el mar, en ríos y en otros espacios acuáticos bajo jurisdicción nacional.' },
    { type: 'paragraph', text: 'Asimismo, el CONTRASE tiene a su cargo la emisión de avisos a los navegantes, proporcionando información actualizada sobre condiciones meteorológicas e hidrográficas, el estado del balizamiento y otras ayudas a la navegación.' },
    { type: 'paragraph', text: 'En situaciones de emergencia, el CONTRASE es responsable de alertar, coordinar y apoyar las operaciones de búsqueda, asistencia y salvamento, actuando como nexo entre las embarcaciones en peligro y los distintos medios disponibles para la atención del siniestro.' },
    { type: 'subtitle', text: 'CONTRASE.' },
    { type: 'subtitle', text: 'Asignación de Canales en VHF' },
    { type: 'paragraph', text: 'Como hemos visto, el rango de frecuencias comprendido entre 156,0 MHz y 174,0 MHz, correspondiente a la banda de VHF, ha sido asignado al Servicio Móvil Marítimo.' },
    { type: 'paragraph', text: 'Dentro de este rango de frecuencias se han reservado canales específicos para distintos usos, entre los que se destacan los siguientes:' },
    { type: 'subtitle', text: 'Canal 16.' },
    { type: 'paragraph', text: '156,800 MHz – canal simplex.' },
    { type: 'paragraph', text: 'Es la frecuencia internacional de llamada, socorro, urgencia y seguridad.' },
    { type: 'paragraph', text: 'Es decir que el canal 16 se utiliza para establecer llamadas con estaciones costeras u otros buques, y una vez establecida la comunicación, debe continuarse el diálogo por otro canal de trabajo, liberando el canal 16. Y además se usa este canal para emitir los mensajes de MAYDAY, PAN PAN y SECURITE, que corresponden a las llamadas de socorro, urgencia y seguridad, respectivamente.' },
    { type: 'paragraph', text: 'Las estaciones costeras pueden utilizar también este canal para difundir anuncios breves, tales como el aviso previo a la transmisión de información marítima en otro canal.' },
    { type: 'subtitle', text: 'Canales 75 y 76.' },
    { type: 'paragraph', text: '156,725 MHz y 156,775 MHz – canales simplex.' },
    { type: 'paragraph', text: 'Las frecuencias asignadas a los canales 75 y 76 son la anterior y posterior del canal 16, por lo que deben usarse únicamente para comunicaciones relacionadas con la navegación, sin causar interferencias perjudiciales en el canal 16, limitando la potencia de transmisión a 1 Watt.' },
    { type: 'subtitle', text: 'Canal 70.' },
    { type: 'paragraph', text: '156,525 MHz – canales simplex digital.' },
    { type: 'paragraph', text: 'Digital Selective Call.' },
    { type: 'paragraph', text: 'En algunos equipos de radio el botón DSC está etiquetado como DISTRESS, palabra que implica que existe alguna condición externa muy seria que afecta a la tripulación o a la embarcación.' },
    { type: 'paragraph', text: 'Y puesto que dentro de las opciones básicas de la llamada selectiva digital está la transmisión de mensajes de socorro, urgencia o seguridad, es que se reemplaza la etiqueta DSC por la de DISTRESS para facilitar la identificación del servicio.' },
    { type: 'subtitle', text: 'Canales 10 y 11.' },
    { type: 'paragraph', text: '156,500 MHz y 156,550 MHz – canales simplex.' },
    { type: 'paragraph', text: 'Son los canales anterior y posterior al canal 70.' },
    { type: 'paragraph', text: 'Al operar en estos canales deben extremarse las precauciones para no interferir las comunicaciones DSC, dado el carácter crítico del canal 70 para la seguridad de la navegación.' },
    { type: 'subtitle', text: 'Canal 13.' },
    { type: 'paragraph', text: '156,650 MHz – canal simplex.' },
    { type: 'paragraph', text: 'El canal 13 está reservado como canal de comunicaciones para la seguridad de la navegación, principalmente para las que se realizan entre barcos envueltos en estas operaciones.' },
    { type: 'paragraph', text: 'Puede también utilizarse en el servicio de movimiento de barcos y operaciones portuarias.' },
    { type: 'subtitle', text: 'Canal 06.' },
    { type: 'paragraph', text: '156,300 MHz – canal simplex.' },
    { type: 'paragraph', text: 'Se utiliza principalmente para las comunicaciones entre buques y aeronaves que participan en operaciones coordinadas de búsqueda y salvamento (SAR).' },
    { type: 'paragraph', text: 'Asimismo, puede emplearse como canal alternativo al canal 16 para comunicaciones de socorro, urgencia o seguridad cuando las circunstancias así lo requieran.' },
    { type: 'subtitle', text: 'Operación durante las comunicaciones por radio.' },
    { type: 'subtitle', text: 'Disposiciones Operativas' },
    { type: 'paragraph', text: 'Por ejemplo:' },
    { type: 'subtitle', text: 'Uso Responsable.' },
    { type: 'paragraph', text: 'A fin de garantizar la disponibilidad del espectro, que es finito, queda prohibido a todas las estaciones efectuar trasmisiones inútiles, superfluas, y por supuesto, falsas.' },
    { type: 'paragraph', text: 'Las transmisiones de prueba para ajuste de equipos deben reducirse al mínimo, buscando que no excedan de algunos pocos segundos, y en lo posible deben ser realizadas fuera de los canales destinados a comunicaciones de emergencia, y nunca en el canal 70. En cualquier caso, deben efectuarse indicando el nombre de la embarcación o estación desde la cual se la emite.' },
    { type: 'paragraph', text: 'A los operadores de las estaciones de radio les está prohibido interceptar o escuchar, sin autorización, las comunicaciones no destinadas al público general.' },
    { type: 'subtitle', text: 'Prioridades.' },
    { type: 'subtitle', text: 'Identificación.' },
    { type: 'paragraph', text: 'Las estaciones costeras, por su lado, se identificarán también mediante un distintivo de llamada o mediante el nombre geográfico del lugar, seguido de la palabra "radio".' },
    { type: 'paragraph', text: 'En cualquier caso y sea cual sea la identidad, ninguna de ellas deberá estar formada de manera que pueda existir confusión de esta con señales de socorro, urgencia o seguridad.' },
    { type: 'paragraph', text: '¿Escuchó alguna vez los reportes de novedades que la Prefectura Naval Argentina emite una vez por hora?' },
    { type: 'paragraph', text: 'Bueno, ahora ya sabe entonces porque el operador dice "Esta es Lima Dos Golf, Prefectura Naval radio".' },
    { type: 'subtitle', text: 'Claridad en la Comunicación.' },
    { type: 'paragraph', text: 'Durante las comunicaciones por radio, hable claramente, sin apresurarse, especialmente cuando detecte baja calidad en la recepción del audio en alguno de los extremos.' },
    { type: 'paragraph', text: 'Evite el uso de términos del argot local, especialmente si se está comunicando con interlocutores de otras regiones o países, que no estén habituados a esa terminología.' },
    { type: 'paragraph', text: 'En caso de existir dificultades de idioma o cuando sea preciso deletrear nombres, distintivos de llamada, abreviaturas reglamentarias o cualquier otra palabra durante una comunicación radiofónica, se recomienda utilizar el Alfabeto Fonético Internacional. Este es utilizado por los radio operadores en todo el mundo, por lo que es útil para comunicarse en esas circunstancias.' },
    { type: 'paragraph', text: 'Las fechas se sugiere verbalizarlas de conformidad con el calendario Gregoriano, esto es indicando primero el día, luego el mes, y después el año, en su forma extendida, por ejemplo, diciendo "tres de mayo de dos mil quince", o expresándola de forma totalmente numérica según una secuencia fija de seis números en la que cada grupo de dos dígitos representará el día, el mes y el año, por ejemplo "030515".' },
    { type: 'paragraph', text: 'Siempre que se indique una hora, especialmente en comunicaciones internacionales, deberá hacérselo en horario UTC, representándolo en grupos de cuatro dígitos, desde el "0000 hs" a las "2359 hs".' },
    { type: 'paragraph', text: 'Al pronunciar cifras, puede dictarlas dígito a dígito, separando los enteros de los decimales con la palabra "decimal", diciendo, por ejemplo, "uno dos tres decimal nueve ocho" para dictar el número "123,98".' },
    { type: 'subtitle', text: 'Distintivos de Llamada' },
    { type: 'paragraph', text: 'Distintivo de llamada.' },
    { type: 'paragraph', text: 'Los distintivos de llamada se forman combinando las veintiséis letras del alfabeto y los números del 0 al 9, respetando el siguiente formato:' },
    { type: 'paragraph', text: 'PP-EEE' },
    { type: 'paragraph', text: 'de "AY" a "AZ"' },
    { type: 'paragraph', text: 'de "L2" a "L9"' },
    { type: 'paragraph', text: 'de "LO" a "LW"' },
    { type: 'paragraph', text: 'Y los siguientes tres caracteres, llamados "EEE", se utilizan para identificar a la estación en sí misma.' },
    { type: 'paragraph', text: 'Así entonces, y a modo de ejemplo, podemos nombrar algunas de las identificaciones de las estaciones costeras de las Prefecturas Navales de Argentina y Uruguay ubicadas en la zona Delta y Rio de la Plata Interior.' },
    { type: 'paragraph', text: 'PNA, CONTRASE:' },
    { type: 'paragraph', text: 'L2G (Lima Dos Golf)' },
    { type: 'paragraph', text: 'PNA San Isidro:' },
    { type: 'paragraph', text: 'L5J (Lima Cinco Juliet)' },
    { type: 'paragraph', text: 'PNA San Fernando:' },
    { type: 'paragraph', text: 'L5K (Lima Cinco Kilo)' },
    { type: 'paragraph', text: 'PNA San Isidro:' },
    { type: 'paragraph', text: 'L5J (Lima Cinco Juliet)' },
    { type: 'paragraph', text: 'PNN Control Colonia:' },
    { type: 'paragraph', text: 'CWC23 (Charly Whisky Charly Dos Siete)' },
    { type: 'paragraph', text: 'PNN Control Buceo:' },
    { type: 'paragraph', text: 'CWC27 (Charly Whisky Charly Cuatro Siete)' },
    { type: 'subtitle', text: 'Protocolo de Comunicación en VHF' },
    { type: 'paragraph', text: 'Toda comunicación tiene un protocolo preestablecido, tácito o explícito, que se utiliza habitualmente casi sin pensar en él. Esto es válido tanto para una charla telefónica, como para el envío de una carta por correo, y por supuesto para una comunicación de radio utilizando equipos VHF.' },
    { type: 'paragraph', text: 'En términos generales, todos los estos protocolos se dividen en tres bloques muy fáciles de identificar:' },
    { type: 'subtitle', text: 'Establecimiento de la Llamada.' },
    { type: 'paragraph', text: 'Este bloque incluye los pasos necesarios para contactar a la contraparte de la comunicación.' },
    { type: 'paragraph', text: 'Por ejemplo, en una llamada telefónica, el establecimiento de la comunicación se inicia cuando se digita el número de teléfono llamado, y finaliza cuando se ha dado con la persona buscada.' },
    { type: 'paragraph', text: 'A este proceso se lo denomina "llamada" en una comunicación de radio, y es aquel por el cual se llama a la estación con la cual se quiere establecer la conexión.' },
    { type: 'subtitle', text: 'Intercambio de Mensajes.' },
    { type: 'paragraph', text: 'Es el proceso que comienza una vez que la conexión se ha establecido, y en el cual se intercambian los mensajes objeto de la llamada.' },
    { type: 'subtitle', text: 'Finalización de la Comunicación.' },
    { type: 'paragraph', text: 'Este subproceso se utiliza para formalizar el final de la comunicación.' },
    { type: 'subtitle', text: 'Operación durante las comunicaciones por radio.' },
    { type: 'subtitle', text: 'Protocolo de Llamada' },
    { type: 'paragraph', text: 'Como se ha dicho, las funciones resumidas en este protocolo se aplican también en las comunicaciones por VHF. Así entonces, cuando una embarcación deba establecer una comunicación con una estación costera u otro buque, deberá hacerlo respetando el siguiente protocolo de llamada:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN LLAMADA]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: 'IDENTIFICACIÓN DE LA ESTACIÓN LLAMADA: Puede ser el "distintivo de llamada", el "MMSI" o simplemente el "nombre de la estación" o del barco al que se está llamando.' },
    { type: 'paragraph', text: 'SEPARADOR: Es una palabra que se utiliza para separar claramente el distintivo de ambas partes. Pueden usarse, por ejemplo, las palabras "AQUI" o "PARA", o cualquier otra aplicable en el mismo sentido.' },
    { type: 'paragraph', text: 'En el caso de llamadas efectuadas a estaciones costeras, es una buena práctica agregar también el tipo de embarcación, como por ejemplo "VELERO" o "YATE", u otra palabra que le sirva al interlocutor para identificar más apropiadamente a quien está iniciando la llamada.' },
    { type: 'paragraph', text: 'IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA: Puede ser el "identificativo de llamada", el "MMSI" o el "nombre de la estación" o del barco que está iniciando la llamada.' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET,' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET,' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET' },
    { type: 'paragraph', text: 'AQUÍ VELERO' },
    { type: 'paragraph', text: 'PRIMAVERA,' },
    { type: 'paragraph', text: 'PRIMAVERA,' },
    { type: 'paragraph', text: 'PRIMAVERA' },
    { type: 'paragraph', text: 'En este mensaje de llamada se ha usado el separador "AQUÍ" precediendo al nombre de la estación que efectúa la llamada, y puesto que "AQUÍ" es una palabra del idioma español, el mensaje solo podría ser correctamente interpretado por quienes hablan ese lenguaje.' },
    { type: 'paragraph', text: 'Para resolver esto, puesto que es evidentemente imposible saber cómo se dice "AQUÍ" en cada lenguaje, se ha convenido reemplazar esa palabra por las letras "DELTA ECHO" cuando exista alguna posibilidad de diferencias idiomáticas entre los interlocutores.' },
    { type: 'paragraph', text: 'Así entonces, esta misma llamada se haría de la siguiente forma.' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET,' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET,' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET' },
    { type: 'paragraph', text: 'DELTA ECHO' },
    { type: 'paragraph', text: 'PRIMAVERA,' },
    { type: 'paragraph', text: 'PRIMAVERA,' },
    { type: 'paragraph', text: 'PRIMAVERA' },
    { type: 'paragraph', text: 'No obstante, cuando las condiciones para el establecimiento de la comunicación sean buenas, puede resumirse el llamado repitiendo solo una vez el nombre de las estaciones. Y, en cualquier caso, cuando no exista un canal acordado previamente para establecer las comunicaciones, la llamada tanto entre barcos como entre una estación costera y un barco se iniciará por el canal 16 de VHF.' },
    { type: 'paragraph', text: 'Luego, la estación llamada debe responder de la forma siguiente:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: '[REPUESTA]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN A LA QUE SE RESPONDE]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE RESPONDE LA LLAMADA]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[CANAL DE TRABAJO OFRECIDO]' },
    { type: 'paragraph', text: 'RESPUESTA: Es cualquier palabra que signifique reconocimiento y aceptación de la llamada.' },
    { type: 'paragraph', text: 'Por ejemplo: "ADELANTE". "HOLA" o cualquier otra del mismo tenor.' },
    { type: 'paragraph', text: 'CANAL DE TRABAJO OFRECIDO: Es el canal de VHF al que se invita al interlocutor a continuar la llamada.' },
    { type: 'paragraph', text: 'ADELANTE' },
    { type: 'paragraph', text: 'PRIMAVERA' },
    { type: 'paragraph', text: 'AQUÍ' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET' },
    { type: 'paragraph', text: 'PASEMOS AL CANAL SESENTA Y OCHO, SEIS OCHO' },
    { type: 'paragraph', text: 'Tal como se mencionó anteriormente, y como se ha hecho en este ejemplo, puede resumirse la cantidad de repeticiones de las identificaciones cuando las condiciones técnicas lo permiten. La estación que responde debe hacerlo en el mismo canal por el que se la ha contactado.' },
    { type: 'paragraph', text: 'Note que el número sesenta y ocho ha sido repetido en este caso nombrando cada dígito por separado, para asegurar su correcta interpretación.' },
    { type: 'paragraph', text: 'Una vez que se ha pasado al canal de operación, se considerará que la comunicación se ha establecido, iniciándose entonces el intercambio de mensajes.' },
    { type: 'paragraph', text: 'En cualquier caso, las estaciones que capten una transmisión referida a la seguridad de la navegación deberán escuchar el mensaje hasta tener certeza de que no les concierne, debiendo en este caso abstenerse de efectuar cualquier transmisión en ese canal que pueda perturbar la transmisión del mensaje.' },
    { type: 'paragraph', text: 'Si la estación llamada no pudiese aceptar la comunicación, deberá responder en la forma señalada anteriormente, añadiendo lo siguiente:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: '[REPUESTA]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN A LA QUE SE RESPONDE]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE RESPONDE LA LLAMADA]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[OCUPADO]' },
    { type: 'paragraph', text: '[TIEMPO DE DEMORA]' },
    { type: 'paragraph', text: '[CAUSA DE LA DEMORA]' },
    { type: 'paragraph', text: 'OCUPADO: O cualquier otro sinónimo, indica que la estación llamada no puede responder la llamada en ese momento.' },
    { type: 'paragraph', text: 'TIEMPO DE DEMORA y CAUSA DE LA DEMORA: Son opcionales, aunque por buena práctica y cordialidad, merecen ser agregados.' },
    { type: 'paragraph', text: 'Por ejemplo, si se quiere demorar la llamada por cinco minutos pues se está atendiendo otra comunicación, podría responderse de la siguiente manera:' },
    { type: 'paragraph', text: 'ADELANTE' },
    { type: 'paragraph', text: 'PRIMAVERA' },
    { type: 'paragraph', text: 'AQUÍ' },
    { type: 'paragraph', text: 'LIMA CINCO JULIET' },
    { type: 'paragraph', text: 'POR FAVOR, AGUARDE' },
    { type: 'paragraph', text: 'CINCO MINUTOS' },
    { type: 'paragraph', text: 'TENGO OTRA COMUNICACIÓN EN CURSO' },
    { type: 'paragraph', text: 'Cuando una estación reciba una llamada sin tener la seguridad de que le está dirigida, no deberá responderla hasta que luego de escuchar su repetición pueda confirmar que efectivamente es para su estación.' },
    { type: 'paragraph', text: 'Y, por otro lado, cuando se reciba una llamada en la que no se comprenda la identificación de la estación llamante, deberá respondérsela de inmediato solicitando a esta última que repita su distintivo de llamada o cualquier otra identificación que utilice.' },
    { type: 'paragraph', text: 'Una vez establecida la llamada se la continuará por el canal de trabajo acordado. Si durante la misma sucediese que las condiciones técnicas no permitieran operar por dicho canal, cualquiera de las estaciones podrá indicar a la otra la necesidad de cambiar a un nuevo canal.' },
    { type: 'subtitle', text: 'MAYDAY - Llamada de Socorro' },
    { type: 'paragraph', text: 'Note que la condición que amerita el inicio de una llamada de socorro es el riesgo de la vida humana y no el de pérdida o daño de la embarcación.' },
    { type: 'paragraph', text: 'Excepto que el riesgo que tenga la embarcación sea una amenaza para la vida humana.' },
    { type: 'subtitle', text: 'MAYDAY.' },
    { type: 'paragraph', text: 'Por lo pronto, debe tenerse en cuenta que no existe ninguna disposición que impida a una estación que se encuentre en peligro, o a las estaciones que eventualmente la asistan, hacer uso de todos los medios de comunicaciones de los que dispongan, sea para solicitar ayuda o para prestar asistencia. Inclusive, en caso de emergencia, se permite la comunicación integrada entre estaciones del Servicio Móvil Marítimo con sus pares del Servicio Móvil Aeronáutico.  La lógica de esto radica obviamente en que ante una emergencia la salvaguarda de la vida humana tiene prioridad absoluta sobre cualquier otra condición o regulación existente, por lo tanto, quien se encuentre en esa situación debe poder pedir socorro por cualquier medio.' },
    { type: 'paragraph', text: 'El protocolo de pedido de socorro responde a este mismo criterio, por lo tanto, las llamadas de socorro tienen absoluta prioridad sobre cualquier otro tipo de comunicación, y puesto que se encaminan por el canal 16 de VHF, es obligatorio que todas las estaciones permanezcan siempre en escucha en ese canal, reduciendo a su vez las transmisiones que eventualmente deban realizar al mínimo posible a fin de mantener el recurso disponible para su uso específico.' },
    { type: 'paragraph', text: 'Al momento de escucharse una llamada de socorro, todas las estaciones deberán cesar de inmediato las comunicaciones que tengan en curso sobre el canal 16 para no interferir el tráfico de socorro, quedando a la escucha.' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[MAYDAY]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[MAYDAY]' },
    { type: 'subtitle', text: 'MAYDAY, MAYDAY, MAYDAY' },
    { type: 'paragraph', text: 'AQUÍ' },
    { type: 'paragraph', text: 'PRIMAVERA, PRIMAVERA, PRIMAVERA' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'A continuación, cuando el acuse de recibo no haya sido recibido, debe enviarse el mensaje de socorro ampliando la información de la siguiente manera:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[MAYDAY]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: '[NATURALEZA DEL PELIGRO]' },
    { type: 'paragraph', text: '[TIPO DE ASISTENCIA REQUERIDA]' },
    { type: 'paragraph', text: '[POSICIÓN]' },
    { type: 'paragraph', text: '[RUMBO]' },
    { type: 'paragraph', text: '[VELOCIDAD]' },
    { type: 'paragraph', text: '[INFORMACION ADICIONAL DE INTERES]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[MAYDAY]' },
    { type: 'paragraph', text: 'NATURALEZA DEL PELIGRO y TIPO DE ASISTENCIA REQUERIDA deben ser mensajes concretos, que den idea clara de que sucede y que se requiere.' },
    { type: 'paragraph', text: 'TIPO DE ASISTENCIA REQUERIDA refiere a que tipo de acción se requiere por parte de la parte interlocutora. Puede ser, por ejemplo, un rescate en alta mar, o involucrar a personal médico para actuar ante un caso critico de salud.' },
    { type: 'paragraph', text: 'La POSICIÓN puede expresarse dando las coordenadas de latitud y longitud, o una referencia con respecto a un punto geográfico conocido, que sirva para ubicar la embarcación.' },
    { type: 'paragraph', text: 'RUMBO y VELOCIDAD deben ser las actuales al momento de la llamada. Le servirán a la estación interlocutora para, junto con la posición, elaborar las recomendaciones necesarias para iniciar el protocolo de rescate.' },
    { type: 'paragraph', text: 'INFORMACION ADICIONAL DE INTERES será cualquier otra información que permita al interlocutor tener una idea clara de la situación con la que deberá lidiar.' },
    { type: 'paragraph', text: 'Basados en el mismo nombre de barco del ejemplo anterior, se solicitaría ayuda ante un riesgo de hundimiento como sigue:' },
    { type: 'subtitle', text: 'MAYDAY, MAYDAY, MAYDAY' },
    { type: 'paragraph', text: 'AQUÍ VELERO' },
    { type: 'paragraph', text: 'PRIMAVERA, PRIMAVERA, PRIMAVERA' },
    { type: 'paragraph', text: 'TENEMOS UNA VIA DE AGUA INCONTROLABLE, NOS HUNDIMOS' },
    { type: 'paragraph', text: 'SOLICITO RESCATE URGENTE' },
    { type: 'paragraph', text: 'ESTAMOS A QUINCE MILLAS AL SUR DEL PUERTO DE PIRIAPOLIS' },
    { type: 'paragraph', text: 'SOMOS CINCO ADULTOS Y UN NIÑO' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'Note que en este caso se ha usado la palabra “quince” para indicar la distancia a la que se encuentra navegando la embarcación.' },
    { type: 'paragraph', text: 'Así entonces, será esperable escuchar lo siguiente:' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'PRIMAVERA, PRIMAVERA, PRIMAVERA' },
    { type: 'paragraph', text: 'ESTA ES' },
    { type: 'paragraph', text: 'CONTROL PIRIÁPOLIS' },
    { type: 'paragraph', text: 'RECIBIDO' },
    { type: 'paragraph', text: 'ENTENDEMOS QUE TIENE UNA VIA DE AGUA, QUE SE ESTÁN HUNDIENDO Y QUE SOLICITAN RESCATE URGENTE' },
    { type: 'paragraph', text: 'CONFIRME POR FAVOR' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'De la misma forma en que puede reemplazarse el separador "AQUÍ" o el "ESTA ES" por el código "DELTA ECHO" ante diferencias idiomáticas, también puede apelarse al código "ROMEO" para acusar recibo, como sigue:' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'PRIMAVERA, PRIMAVERA, PRIMAVERA' },
    { type: 'paragraph', text: 'DELTA ECHO' },
    { type: 'paragraph', text: 'CONTROL PIRIÁPOLIS' },
    { type: 'paragraph', text: 'ROMEO' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'A continuación, y una vez asegurada la información crítica, la estación costera mantendrá contacto periódico con la embarcación en emergencia para actualizar la situación, evaluar la evolución del riesgo y confirmar la capacidad de la tripulación para adoptar medidas de autoprotección. Paralelamente, podrá solicitar datos adicionales para terminar de definir el procedimiento de salvamento, y emitir los avisos correspondientes a otras embarcaciones en la zona.' },
    { type: 'subtitle', text: 'MAYDAY.' },
    { type: 'paragraph', text: 'escuchar' },
    { type: 'subtitle', text: 'MAYDAY - Llamada de Socorro' },
    { type: 'paragraph', text: 'Este es el audio un MAYDAY real, emitido por el capitán del de un pesquero de unos 75 pies, denominado "Northern Belle"  que se hundió frente a Alaska, aproximadamente a 50 millas al sur de Montague Island.' },
    { type: 'paragraph', text: 'A continuación reproducimos el texto de la llamada en su versión en ingles, y su traducción al español, al solo efecto de que se pueda apreciar como se ejecuta un protocolo de llamada de MAYDAY, cuando efectivamente ocurre.' },
    { type: 'paragraph', text: 'Capitán' },
    { type: 'paragraph', text: 'Northern Belle' },
    { type: 'paragraph', text: 'Mayday Mayday Mayday' },
    { type: 'paragraph', text: 'This is the Northern Belle' },
    { type: 'paragraph', text: 'We are 59 degress 10 minutes North… 146… 47… degress… West…' },
    { type: 'paragraph', text: 'This is the Northern Belle' },
    { type: 'paragraph', text: 'Mayday Mayday' },
    { type: 'paragraph', text: 'Mayday Mayday Mayday' },
    { type: 'paragraph', text: 'Este es el Northern Belle' },
    { type: 'paragraph', text: 'Estamos en 59 grados 10 minutos Norte… 146… 47… grados… Oeste…' },
    { type: 'paragraph', text: 'Este es el Northern Belle' },
    { type: 'paragraph', text: 'Mayday Mayday' },
    { type: 'paragraph', text: 'USGC' },
    { type: 'paragraph', text: 'Kodiak Alaska' },
    { type: 'paragraph', text: 'Roger' },
    { type: 'paragraph', text: 'I understand that the vessel name is Northern Belle' },
    { type: 'paragraph', text: 'Vessel Northern Belle' },
    { type: 'paragraph', text: 'Vessel Northern Belle' },
    { type: 'paragraph', text: 'This is the United States Coast Guard Kodiak Alaska, Communication station 4125.' },
    { type: 'paragraph', text: 'Over' },
    { type: 'paragraph', text: 'Comprendido' },
    { type: 'paragraph', text: 'Entiendo que el nombre del barco es Northern Belle' },
    { type: 'paragraph', text: 'Barco Northern Belle' },
    { type: 'paragraph', text: 'Barco Northern Belle' },
    { type: 'paragraph', text: 'Este es el Guarda Costas de Estados Unidos, Kodiak, Alaska, estación de Comunicaciones 4125.' },
    { type: 'paragraph', text: 'Cambio' },
    { type: 'paragraph', text: 'Capitán' },
    { type: 'paragraph', text: 'Northern Belle' },
    { type: 'paragraph', text: 'Yes Coast Guard' },
    { type: 'paragraph', text: 'We are Northern Belle' },
    { type: 'paragraph', text: 'Go ahead' },
    { type: 'paragraph', text: 'Si Guarda Costas' },
    { type: 'paragraph', text: 'Somos el Northern Belle' },
    { type: 'paragraph', text: 'Adelante' },
    { type: 'paragraph', text: 'USGC' },
    { type: 'paragraph', text: 'Kodiak Alaska' },
    { type: 'paragraph', text: 'Vessel Northern Belle' },
    { type: 'paragraph', text: 'This is comms station Kodiak, request to know if you are in need of assistance.' },
    { type: 'paragraph', text: 'Over' },
    { type: 'paragraph', text: 'Comprendido' },
    { type: 'paragraph', text: 'Buque Northern Belle' },
    { type: 'paragraph', text: 'Esta es la estación de Comunicaciones de Kodiak, requiriendo saber si necesitan asistencia' },
    { type: 'paragraph', text: 'Cambio' },
    { type: 'paragraph', text: 'Capitán' },
    { type: 'paragraph', text: 'Northern Belle' },
    { type: 'paragraph', text: 'Absolutely, we are going down!' },
    { type: 'paragraph', text: '¡Absolutamente, nos estamos hundiendo!' },
    { type: 'paragraph', text: 'USGC' },
    { type: 'paragraph', text: 'Kodiak Alaska' },
    { type: 'paragraph', text: 'Vessel Northern Belle, this is comms station Kodiak' },
    { type: 'paragraph', text: 'Roger' },
    { type: 'paragraph', text: 'Understand you are going down' },
    { type: 'paragraph', text: 'Request to know persons on board' },
    { type: 'paragraph', text: 'Over' },
    { type: 'paragraph', text: 'Buque Northern Belle, esta es la estación de comunicaciones de Kodiak' },
    { type: 'paragraph', text: 'Comprendido.' },
    { type: 'paragraph', text: 'Entiendo que se están hundiendo' },
    { type: 'paragraph', text: 'Solicito saber cuantas personas están a bordo' },
    { type: 'paragraph', text: 'Cambio' },
    { type: 'paragraph', text: 'Capitán' },
    { type: 'paragraph', text: 'Northern Belle' },
    { type: 'paragraph', text: 'We have four persons on board' },
    { type: 'paragraph', text: 'We are getting into a…' },
    { type: 'paragraph', text: 'We are getting in a life raft here' },
    { type: 'paragraph', text: 'We are aagoing down' },
    { type: 'paragraph', text: 'Tenemos cuatro personas a bordo' },
    { type: 'paragraph', text: 'Estamos subiendo a…' },
    { type: 'paragraph', text: 'Estamos subiendo a una balsa salvavidas aquí' },
    { type: 'paragraph', text: 'Nos estamos hundiendo' },
    { type: 'paragraph', text: 'USGC' },
    { type: 'paragraph', text: 'Kodiak Alaska' },
    { type: 'paragraph', text: 'Vessel Northern Belle, this is comms station Kodiak requesting say again person on board' },
    { type: 'paragraph', text: 'Over' },
    { type: 'paragraph', text: 'Buque Northern Belle, esta es la estación de comunicaciones de Kodiak requiriendo personas a bordo' },
    { type: 'paragraph', text: 'Cambio' },
    { type: 'paragraph', text: 'Capitán' },
    { type: 'paragraph', text: 'Northern Belle' },
    { type: 'paragraph', text: 'There are four people on board' },
    { type: 'paragraph', text: 'That is four' },
    { type: 'paragraph', text: 'Hay cuatro personas a bordo' },
    { type: 'paragraph', text: 'Esto es cuatro' },
    { type: 'paragraph', text: 'USGC' },
    { type: 'paragraph', text: 'Kodiak Alaska' },
    { type: 'paragraph', text: 'Vessel Northern Belle, this is comms station Kodiak' },
    { type: 'paragraph', text: 'Roger' },
    { type: 'paragraph', text: 'Understand that are four persons on board' },
    { type: 'paragraph', text: 'Request to know description of your vessel… make… and color' },
    { type: 'paragraph', text: 'Over' },
    { type: 'paragraph', text: 'Entiendo que son cuatro personas a bordo.' },
    { type: 'paragraph', text: 'Solicito saber la descripción de su barco… tipo… y color' },
    { type: 'paragraph', text: 'Cambio' },
    { type: 'subtitle', text: 'MAYDAY - Cancelación de la Llamada de Socorro' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[A TODAS LAS ESTACIONES]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[CANCELACION DE MI MAYDAY DE HORA (HORA)]' },
    { type: 'paragraph', text: 'A TODAS LAS ESTACIONES, A TODAS LAS ESTACIONES, A TODAS LAS ESTACIONES' },
    { type: 'paragraph', text: 'ESTE ES EL' },
    { type: 'paragraph', text: 'VELERO PRIMAVERA, VELERO PRIMAVERA, VELERO PRIMAVERA' },
    { type: 'paragraph', text: 'EMITO CANCELACION DE MI MAYDAY DE HORA 18:50 HORA LOCAL' },
    { type: 'paragraph', text: 'Note que, en ese ejemplo, la hora fue expresada en "HORA LOCAL". Si hubiera sido indicada en huso horario UTC u otro, tendría que ser anunciado en la cancelación de la misma forma.' },
    { type: 'paragraph', text: 'En ese caso, el mensaje podría ser emitido como sique:' },
    { type: 'paragraph', text: 'CQ CQ CQ' },
    { type: 'paragraph', text: 'ESTE ES EL' },
    { type: 'paragraph', text: 'VELERO PRIMAVERA' },
    { type: 'paragraph', text: 'EMITO CANCELACION DE MI MAYDAY DE HORA 21:50 UTC' },
    { type: 'paragraph', text: 'Una vez emitida la cancelación, deberá permanecerse en escucha sobre el mismo canal para responder a todas las comunicaciones e interrogaciones relativas a la alerta de socorro, según proceda, que pueda requerir la autoridad marítima.' },
    { type: 'paragraph', text: 'Otro dato para los lectores curiosos.' },
    { type: 'paragraph', text: 'La palabra MAYDAY fue adoptada en la década de 1920, en los inicios de la radiotelefonía aeronáutica y marítima.' },
    { type: 'paragraph', text: 'Su origen no es inglés, sino que proviene de la expresión francesa "m’aidez" o "venez m’aider" que significa literalmente "ayúdenme" o "vengan a ayudarme".' },
    { type: 'paragraph', text: 'La pronunciación francesa [mɛˈde] fue adaptada fonéticamente al inglés como mayday, porque se comprobó que era más fácil de pronunciar en condiciones de estrés, porque tiene un sonido claro y distintivo, incluso con ruido, interferencias o mala propagación, y porque es difícil de confundir con otras palabras comunes, además de que funciona bien para hablantes de distintos idiomas.' },
    { type: 'paragraph', text: 'Frederick Stanley Mockford.' },
    { type: 'paragraph', text: 'Inicialmente fue propuesta por Frederick Stanley Mockford, operador de radio del aeropuerto de Croydon, en el Reino Unido, para las comunicaciones aéreas entre Londres y París, y rápidamente fue adoptada también por el ámbito marítimo.' },
    { type: 'paragraph', text: 'Con el tiempo, MAYDAY quedó normalizada internacionalmente por la UIT - Unión Internacional de Telecomunicaciones y la OMI - Organización Marítima Internacional como la palabra clave para indicar peligro grave e inminente para la vida o la embarcación.' },
    { type: 'subtitle', text: 'MAYDAY SILENCE - Solicitud de Silencio de Radio' },
    { type: 'paragraph', text: 'ALL STATIONS, ALL ATATIONS, ALL ATATIONS' },
    { type: 'paragraph', text: 'ESTA ES' },
    { type: 'paragraph', text: 'CONTROL PIRIÁPOLIS, CONTROL PIRIÁPOLIS, CONTROL PIRIÁPOLIS' },
    { type: 'paragraph', text: 'SILENCE' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'paragraph', text: 'Generalmente, la palabra "SILENCE" es pronunciada enfáticamente, para que todas las estaciones puedan entender la solicitud.' },
    { type: 'paragraph', text: 'A TODAS LAS ESTACIONES, A TODAS LAS ESTACIONES, A TODAS LAS ESTACIONES' },
    { type: 'paragraph', text: 'ESTA ES' },
    { type: 'paragraph', text: 'CONTROL PIRIÁPOLIS, CONTROL PIRIÁPOLIS, CONTROL PIRIÁPOLIS' },
    { type: 'paragraph', text: 'SILENCE FINI' },
    { type: 'subtitle', text: 'MAYDAY' },
    { type: 'subtitle', text: 'MAYDAY.' },
    { type: 'paragraph', text: 'escuchar' },
    { type: 'subtitle', text: 'MAYDAY SILENCE' },
    { type: 'paragraph', text: 'Caso de solicitud de silencio durante una llamada de MAYDAY..' },
    { type: 'paragraph', text: 'Landsan Radio' },
    { type: 'paragraph', text: 'Mayday' },
    { type: 'paragraph', text: 'All stations, All stations, All stations' },
    { type: 'paragraph', text: 'This is Lansan Radio, Lansan Radio, Lansan Radio' },
    { type: 'paragraph', text: 'Silence' },
    { type: 'paragraph', text: 'Mayday' },
    { type: 'paragraph', text: 'Mayday' },
    { type: 'paragraph', text: 'Todas las estaciones, Todas las estaciones, Todas las estaciones' },
    { type: 'paragraph', text: 'Esta es Lansan Radio, Lansan Radio, Lansan Radio' },
    { type: 'paragraph', text: 'Silence' },
    { type: 'paragraph', text: 'Mayday Mayday' },
    { type: 'paragraph', text: 'escuchar' },
    { type: 'subtitle', text: 'MAYDAY SILENCE FINI' },
    { type: 'paragraph', text: 'Caso de finalización de la condición de silencio durante una llamada de MAYDAY.' },
    { type: 'paragraph', text: 'Landsan Radio' },
    { type: 'paragraph', text: 'Mayday' },
    { type: 'paragraph', text: 'All stations, All stations, All stations' },
    { type: 'paragraph', text: 'This is coast station Rotterdam' },
    { type: 'paragraph', text: 'Silence Fini' },
    { type: 'paragraph', text: 'Mayday' },
    { type: 'paragraph', text: 'Todas las estaciones, Todas las estaciones, Todas las estaciones' },
    { type: 'paragraph', text: 'Esta es la estación costera Rotterdam' },
    { type: 'paragraph', text: 'Silence Fini' },
    { type: 'subtitle', text: 'MAYDAY RELAY - Retransmisión de la Llamada de Socorro' },
    { type: 'paragraph', text: 'Veamos un ejemplo de este caso.' },
    { type: 'paragraph', text: 'Supongamos que la embarcación en peligro que está emitiendo el MAYDAY está lejos de la costa, debajo de la línea del horizonte visible, y fuera del horizonte radioeléctrico de la estación costera que controla la zona, por lo que su llamada no tiene las condiciones técnicas para ser escuchada por el sistema de emergencia.' },
    { type: 'paragraph', text: 'En ese caso, el radio operador de ese barco puede romper el silencio, y emitir un MAYDAY RELAY repitiendo lo que escuchó en la llamada original.' },
    { type: 'paragraph', text: 'En cualquier caso, la embarcación que retransmita una llamada de socorro, o la inicia a nombre de otra, deberá indicar claramente que ella misma no está en peligro.' },
    { type: 'paragraph', text: 'La retransmisión de una llamada de socorro debe efectuarse de la siguiente manera:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[MAYDAY RELAY]' },
    { type: 'paragraph', text: 'repetir 3 veces' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN COSTERA] LLAMADA' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir 3 veces' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE RETRANSMITE]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[MAYDAY RELAY]' },
    { type: 'paragraph', text: 'Esta llamada irá seguida de un mensaje de socorro en el que deberá repetirse la información contenida en el MAYDAY original. Si no puede identificarse la estación en peligro, habrá que enviar el mensaje de socorro utilizando, por ejemplo, términos tales como "buque no identificado" para referirse al barco en peligro. Si se conoce el nombre de la estación costera a la cual dirigir el mensaje, deberá agregárselo a la' },
    { type: 'paragraph', text: 'Por ejemplo, si hubiese que retransmitir el mensaje de socorro del "Primavera" desde otro barco llamado "Duquesa", dirigiéndolo a la estación costera del puerto de Piriápolis, se haría así:' },
    { type: 'subtitle', text: 'MAYDAY RELAY, MAYDAY RELAY, MAYDAY RELAY' },
    { type: 'paragraph', text: 'CONTROL PIRIAPOLIS, CONTROL PIRIAPOLIS, CONTROL PIRIAPOLIS' },
    { type: 'paragraph', text: 'AQUÍ' },
    { type: 'paragraph', text: 'DUQUESA, DUQUESA, DUQUESA' },
    { type: 'subtitle', text: 'MAYDAY RELAY' },
    { type: 'subtitle', text: 'MAYDAY RELAY' },
    { type: 'paragraph', text: 'PRIMAVERA' },
    { type: 'paragraph', text: 'AVEGANDO A QUINCE MILLAS AL SUR DEL PUERTO DE PIRIAPOLIS' },
    { type: 'paragraph', text: 'TIENE UNA VIA DE AGUA INCONTROLABLE, SE ESTA HUNDIENDO' },
    { type: 'paragraph', text: 'SON CINCO ADULTOS Y UN NIÑO A BORDO' },
    { type: 'paragraph', text: 'SOLICITAN RESCATE URGENTE' },
    { type: 'subtitle', text: 'MAYDAY RELAY' },
    { type: 'paragraph', text: 'En otros casos, una estación costera puede también emitir un MAYDAY RELAY para retransmitir una llamada de socorro previamente recibida, dirigiéndola a todas las embarcaciones en escucha, por ejemplo, para solicitar información o colaboración sobre un evento particular.' },
    { type: 'paragraph', text: 'escuchar' },
    { type: 'subtitle', text: 'MAYDAY RELAY' },
    { type: 'paragraph', text: 'Caso de retransmisión de un MAYDAY por parte de la estación costera a todas las embarcaciones, para que reporten novedades respecto de una embarcación en emergencia.' },
    { type: 'paragraph', text: 'Tenerife Radio' },
    { type: 'paragraph', text: 'Mayday Relay, Mayday Relay' },
    { type: 'subtitle', text: 'Llamada general, Llamada general, Llamada general' },
    { type: 'paragraph', text: 'Aquí Tenerife Radio, Tenerife Radio, Tenerife Radio' },
    { type: 'paragraph', text: 'Mayday' },
    { type: 'paragraph', text: 'Radiobaliza activada del velero Alboran 28 Mojito, distintivo de llamada Echo Charlie Segundo Segundo Cuarto Primero, MMSI Segundo Segundo Cuarto Segundo Cuarto Cuarto Cuarto Sexto Nada, en posición veintisiete grados, cincuenta y cinco coma un minutos Norte, cero diecisiete grados, cero cinco coma un minutos Oeste, a cero siete diez cuarenta y nueve UTC marzo dos mil diecisiete' },
    { type: 'paragraph', text: 'Se solicita a todos los buques en la zona estresen la vigilancia, asistan si fuese necesario, y reporten cualquier avistamiento a Salvamento Marítimo Tenerife o a la estación costera más próxima...' },
    { type: 'subtitle', text: 'PAN PAN - Llamada de Emergencia' },
    { type: 'paragraph', text: 'La llamada PAN PAN se emitirá siempre que exista una situación que requiere tratamiento urgente pero que no implica peligro inminente para la vida humana.' },
    { type: 'paragraph', text: 'Al escuchar una llamada de PAN PAN, todas las estaciones deberán cesar de inmediato las comunicaciones que tengan en curso sobre el canal 16 de VHF para no interferir el tráfico de emergencia, quedando a la escucha.' },
    { type: 'paragraph', text: 'La palabra PAN PAN también tiene origen francés y proviene de "panne", que significa "avería" o "falla".' },
    { type: 'paragraph', text: 'Las características que llevaron a su adopción fueron similares a las del MAYDAY, es decir: claridad fonética y fácil reconocimiento internacional.' },
    { type: 'paragraph', text: 'Con el tiempo, PAN PAN fue estandarizado para indicar urgencia, es decir, una situación que requiere atención inmediata, pero que todavía no ha escalado al nivel de socorro.' },
    { type: 'paragraph', text: 'El formato para comunicar una llamada de PAN PAN es el siguiente:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[PAN PAN]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[MAYDAY]' },
    { type: 'paragraph', text: 'Por ejemplo, si un tripulante a bordo del buque pesquero "Santa Clara" que se encuentra navegando rumbo al Puerto de Mar del Plata hubiese comenzado a mostrar signos de estar sufriendo algún problema de índole médico que no puede tratarse con los recursos con los que se cuenta a bordo, siendo necesario solicitar ayuda, puede procederse como sigue:' },
    { type: 'subtitle', text: 'PAN PAN, PAN PAN, PAN PAN' },
    { type: 'paragraph', text: 'LIMA DOS OSCAR, LIMA DOS OSCAR, LIMA DOS OSCAR' },
    { type: 'paragraph', text: 'AQUÍ' },
    { type: 'paragraph', text: 'BUQUE DE PESCA SANTA CLARA, SANTA CLARA, SANTA CLARA' },
    { type: 'subtitle', text: 'PAN PAN' },
    { type: 'paragraph', text: 'Note también que se ha antecedido el nombre de la embarcación con su tipo: buque de pesca. Esto es útil para que la autoridad marítima pueda identificar más rápidamente al barco que pide asistencia.' },
    { type: 'paragraph', text: 'Luego de efectuada la llamada debe procederse con el mismo protocolo aplicado para el caso de la llamada de socorro. Es decir, una vez que se haya recibido la respuesta por parte de la estación llamada, o en caso de que el PAN PAN no haya sido respondido en un tiempo adecuado, deberá transmitirse el mensaje ampliando la información, como sigue:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[PAN PAN]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: '[NATURALEZA DEL PELIGRO]' },
    { type: 'paragraph', text: '[TIPO DE ASISTENCIA REQUERIDA]' },
    { type: 'paragraph', text: '[POSICIÓN]' },
    { type: 'paragraph', text: '[RUMBO]' },
    { type: 'paragraph', text: '[VELOCIDAD]' },
    { type: 'paragraph', text: '[INFORMACION ADICIONAL DE INTERES]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[PAN PAN]' },
    { type: 'paragraph', text: 'Por ejemplo, siguiendo con el caso del "Santa Clara" podría transmitirse lo siguiente:' },
    { type: 'subtitle', text: 'PAN PAN' },
    { type: 'paragraph', text: 'LIMA DOS OSCAR' },
    { type: 'paragraph', text: 'AQUÍ' },
    { type: 'paragraph', text: 'SANTA CLARA' },
    { type: 'paragraph', text: 'TENEMOS UN MARINERO QUE SUFRE DOLORES ABDOMINALES INTENSOS' },
    { type: 'paragraph', text: 'SOLICITO CONSULTA MEDICA' },
    { type: 'paragraph', text: 'NOS ENCONTRAMOS NAVEGANDO CON RUMBO AL PUERTO DE MAR DEL PLATA ESTIMANDO INGRESAR EN DOS HORAS' },
    { type: 'subtitle', text: 'PAN PAN' },
    { type: 'paragraph', text: 'La cancelación de un mensaje de urgencia se debe realizar de la siguiente manera:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[A TODAS LAS ESTACIONES]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[CANCELACION DE MI PAN PAN DE HORA (HORA)]' },
    { type: 'subtitle', text: 'PAN PAN.' },
    { type: 'paragraph', text: 'escuchar' },
    { type: 'subtitle', text: 'PAN PAN' },
    { type: 'paragraph', text: 'Caso de llamada de PAN PAN efectuado por una estación costera, comunicando un evento a todas las embarcaciones.' },
    { type: 'paragraph', text: 'Palma Radio' },
    { type: 'paragraph', text: 'Pan Pan, Pan Pan, Pan Pan' },
    { type: 'subtitle', text: 'Llamada general, Llamada general, Llamada general' },
    { type: 'paragraph', text: 'Aquí Palma Radio, Palma Radio, Palma Radio' },
    { type: 'paragraph', text: 'Pan Pan' },
    { type: 'paragraph', text: 'Bengala luminosa de color rojoavistada en las proximidades de Candelera, posición latitud treinta y nueve grados, cuarenta decimal cinco minutos Norte, longitud cero cero tres grados veintisiete decimal ocho minutos Este, el d´+ia trece a las veinte quince UTC julio dos mil diecinueve.' },
    { type: 'paragraph', text: 'Buques en la zona extremen vigilancia y comparten con Salvamento Marítimo Pal,a el [...]' },
    { type: 'paragraph', text: 'Aquí Palma Radio a las cero ocho, cero dos UTC del catorce de julio de dos mil diecinueve...' },
    { type: 'subtitle', text: 'SECURITE - Llamada de Seguridad' },
    { type: 'paragraph', text: 'Al igual que con las demás llamadas, al escuchar una llamada de SECURITE, todas las estaciones deberán cesar de inmediato las comunicaciones que tengan en curso sobre el canal 16 de VHF para no interferir el tráfico de seguridad, quedando a la escucha.' },
    { type: 'paragraph', text: 'En caso de tener que participar de una llamada de SECURITE, hágalo también claramente, a fin de facilitar su interpretación.' },
    { type: 'paragraph', text: 'La llamada de SECURITE debe respetar el siguiente formato:' },
    { type: 'paragraph', text: 'Transmitir:' },
    { type: 'paragraph', text: 'repetir 3 veces:' },
    { type: 'paragraph', text: '[SECURITE]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN LLAMADA] o [TODAS LAS ESTACIONES]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[SEPARADOR]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[IDENTIFICACIÓN DE LA ESTACIÓN QUE LLAMA]' },
    { type: 'paragraph', text: 'agregar:' },
    { type: 'paragraph', text: '[MENSAJE DE INTERÉS]' },
    { type: 'paragraph', text: 'repetir un máximo de 3 veces:' },
    { type: 'paragraph', text: '[SECURITE]' },
    { type: 'paragraph', text: 'Para ejemplificarlo, supongamos que el velero "Marilyn" informa que ha avistados contenedores a la deriva en su derrota. En ese caso, debería informarlo como sigue:' },
    { type: 'subtitle', text: 'SECURITE, SECURITE, SECURITE' },
    { type: 'paragraph', text: 'LIMA DOS OSCAR' },
    { type: 'paragraph', text: 'ESTE ES EL' },
    { type: 'paragraph', text: 'VELERO MARILYN, MARILYN, MARILYN' },
    { type: 'paragraph', text: 'INFORMO LA PRESENCIA DE TRES CONTENEDORES FLOTANDO A LA DERIVA CON RUMBO SUR EN POSICION GPS LATITUD TRES CUATRO GRADOS CUATRO UNO DECIMAL CUATRO NUEVE MINUTOS SUR LONGITUD CERO CINCO SIETE GRADOS DOS TRES DECIMAL CERO UNO MINUTOS OESTE' },
    { type: 'subtitle', text: 'SECURITE' },
    { type: 'subtitle', text: 'SECURITE.' },
    { type: 'paragraph', text: 'escuchar' },
    { type: 'subtitle', text: 'SECURITE' },
    { type: 'paragraph', text: 'Caso de llamada de SECURITE emitido por una estación costera para dar un anuncio de tormenta.' },
    { type: 'paragraph', text: 'Limbik Radio' },
    { type: 'paragraph', text: 'Securite, Securite, Securite' },
    { type: 'paragraph', text: 'All stations, All Stations, All stations' },
    { type: 'paragraph', text: 'This is Limbik Radio with gale warning three one seven..' },
    { type: 'paragraph', text: 'Securite, Securite, Securite' },
    { type: 'paragraph', text: 'A todas las estaciones, A todas las estaciones, A todas las estaciones' },
    { type: 'paragraph', text: 'Esta es Limbik Radio con la alerta de tormenta tres uno siete...' },
    { type: 'subtitle', text: 'Los Códigos' },
    { type: 'paragraph', text: 'El conocimiento y uso correcto de estos códigos es una competencia básica para cualquier operador de radio que se desenvuelva en el contexto del Servicio Móvil Marítimo.' },
    { type: 'subtitle', text: 'Alfabeto Fonético Internacional' },
    { type: 'subtitle', text: 'Alfabeto Fonético Internacional.' },
    { type: 'paragraph', text: 'El Alfabeto Fonético Internacional es un conjunto estandarizado de palabras clave asignadas a cada letra del alfabeto, diseñado para permitir el deletreo claro y sin ambigüedades de palabras, nombres y números en radiocomunicaciones. Cada palabra fue seleccionada para ser fácilmente reconocible y distinguible, incluso en condiciones de ruido, interferencias o mala calidad de señal.' },
    { type: 'paragraph', text: 'Entre sus principales ventajas se destacan la uniformidad internacional, la reducción de errores por acentos o diferencias idiomáticas, y la mejora sustancial en la inteligibilidad de las comunicaciones.' },
    { type: 'subtitle', text: 'Alfabeto Fonético Internacional' },
    { type: 'subtitle', text: 'Código Internacional de Señales' },
    { type: 'paragraph', text: 'El Código Internacional de Señales es un sistema normalizado de banderas, señales visuales y sonoras destinado a facilitar la comunicación entre buques, y entre éstos y las estaciones costeras, cuando no existe un idioma común o cuando otros medios de comunicación no están disponibles o resultan inadecuados.' },
    { type: 'paragraph', text: 'El código se basa principalmente en el uso de banderas, aunque también contempla su transmisión mediante señales luminosas, radiotelegrafía y radiotelefonía.' },
    { type: 'paragraph', text: 'Su origen se remonta a mediados del siglo XIX, siendo adoptado oficialmente en 1857, y desde entonces ha sido revisado y actualizado en varias oportunidades. En su forma actual es mantenido por la OMI - Organización Marítima Internacional, que lo reconoce como un instrumento fundamental para la seguridad de la navegación.' },
    { type: 'paragraph', text: 'El código asigna significados estandarizados a banderas individuales, combinaciones de dos o tres banderas, y a grupos alfabéticos, permitiendo transmitir mensajes relacionados con maniobras, estado del buque, pedidos de asistencia, situaciones de emergencia y avisos de seguridad.' },
    { type: 'paragraph', text: 'La principal ventaja del Código Internacional de Señales es su carácter universal e independiente del idioma, lo que lo convierte en un recurso especialmente valioso en situaciones de emergencia, en aguas internacionales o cuando fallan los sistemas de radiocomunicaciones. Por este motivo, continúa siendo parte del equipamiento reglamentario y del adiestramiento básico de los navegantes, aún en la era de las comunicaciones digitales.' },
    { type: 'subtitle', text: 'Código Internacional de Señales' },
    { type: 'paragraph', text: 'Código "Q"' },
    { type: 'subtitle', text: 'Alfabeto "Q".' },
    { type: 'paragraph', text: 'El Código "Q" es un conjunto estandarizado de códigos de tres letras que comienzan siempre con la letra "Q", creadas para simplificar y agilizar las comunicaciones por radio, especialmente en radiotelegrafía. Su desarrollo se produjo a comienzos del siglo XX, en el ámbito de la telegrafía sin hilos, y fue posteriormente adoptado y normalizado por la UIT - Unión Internacional de Telecomunicaciones para su uso en distintos servicios de radiocomunicaciones.' },
    { type: 'paragraph', text: 'Cada código "Q" puede ser expresado como una pregunta o una respuesta, dependiendo de si se lo transmite en forma interrogativa o afirmativa. Por ejemplo, un mismo código puede significar "¿cuál es su posición?" o "mi posición es...", lo que permite transmitir información compleja con gran economía de tiempo y evitando ambigüedades, incluso entre operadores que no comparten un idioma común.' },
    { type: 'paragraph', text: 'La razón por la cual todos los códigos "Q" comienzan con la letra "Q" es bastante simple.' },
    { type: 'paragraph', text: 'Primero, debe tenerse en cuenta que el código "Q" fue desarrollado para facilitar la comunicación entre los operadores de los primeros sistemas de telegrafía sin hilos, allá a principios del siglo XX, y que esos sistemas se desarrollaron en países de habla inglesa y luego francesa y alemana.' },
    { type: 'paragraph', text: 'Básicamente, eligieron la "Q" porque era poco frecuente al inicio de palabras en inglés, francés y alemán.' },
    { type: 'paragraph', text: 'Luego la telegrafía se propagó a Italia y a países de habla hispana, pero el asunto ya estaba fuera de discusión para ese momento.' },
    { type: 'paragraph', text: 'Código "Q"' },
    { type: 'subtitle', text: 'ProSigns' },
    { type: 'paragraph', text: 'A diferencia de las letras o números, los ProSigns no se envían como caracteres separados, sino como una sola señal continua, sin pausas intermedias, lo que permite al receptor reconocerlos inequívocamente como órdenes o marcas de procedimiento. Su función es estructurar la comunicación: iniciar o finalizar un mensaje, indicar espera, corrección, repetición, cambio de operador, etc.' },
    { type: 'subtitle', text: 'ProSigns - Mensajes de Procedimiento"' },
    { type: 'paragraph', text: 'Esta ha sido la última nota del índice de este manual.' },
    { type: 'paragraph', text: 'Mientras tanto, puede entretenerse con este ejercicio.' },
    { type: 'subtitle', text: 'Maniobras y gobierno de la embarcación.' },
    { type: 'paragraph', text: 'Nudos: Tipos de nudos y su aplicación.' },
  ],

  quiz: [
    {
      question: '¿Cuál es el canal internacional de socorro en VHF marino?',
      options: ['Canal 06', 'Canal 13', 'Canal 16', 'Canal 70'],
      correctAnswer: 2,
      explanation: 'El canal 16 (156,800 MHz) es la frecuencia internacional de llamada, socorro, urgencia y seguridad en VHF marino.'
    },
    {
      question: '¿Qué significa MAYDAY?',
      options: ['Una llamada de urgencia', 'Una llamada de socorro que indica peligro grave e inminente', 'Una llamada de seguridad', 'Un mensaje informativo'],
      correctAnswer: 1,
      explanation: 'MAYDAY indica peligro grave e inminente para la vida humana o la embarcación. Proviene del francés \'m\'aidez\' (ayúdenme).'
    },
    {
      question: '¿Qué significa PAN PAN?',
      options: ['Una llamada de socorro', 'Una llamada de urgencia que requiere atención inmediata pero no implica peligro inminente', 'Una llamada de seguridad', 'Una llamada de prueba'],
      correctAnswer: 1,
      explanation: 'PAN PAN indica urgencia, es decir, una situación que requiere atención inmediata pero que no ha escalado al nivel de socorro.'
    },
    {
      question: '¿Cuál es la potencia máxima permitida para transmisores VHF en embarcaciones?',
      options: ['10 watts', '25 watts', '50 watts', '100 watts'],
      correctAnswer: 1,
      explanation: 'El Servicio Móvil Marítimo establece que la potencia máxima de los transmisores VHF no debe exceder los 25 watts.'
    },
    {
      question: '¿Qué canal se utiliza para llamadas selectivas digitales (DSC)?',
      options: ['Canal 16', 'Canal 13', 'Canal 70', 'Canal 06'],
      correctAnswer: 2,
      explanation: 'El canal 70 (156,525 MHz) es el canal simplex digital utilizado para llamada selectiva digital (DSC).'
    },
    {
      question: '¿Qué organismo es la autoridad competente en comunicaciones marítimas en Argentina?',
      options: ['Armada Argentina', 'Prefectura Naval Argentina', 'Servicio Meteorológico Nacional', 'Agencia de Protección Ambiental'],
      correctAnswer: 1,
      explanation: 'La Prefectura Naval Argentina es la autoridad competente para proveer y administrar los servicios de comunicaciones vinculados con la seguridad de la navegación.'
    },
  ]
};