import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'lucha-contra-incendios',
  title: 'Lucha Contra el Fuego',
  readingTime: 12,

  content: [
    { type: 'title', text: 'Control de Averías: Lucha Contra el Fuego' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'paragraph', text: 'El objeto de este título es considerar los principales riesgos que hacen a la seguridad de las embarcaciones, comenzando en este caso con la lucha contra incendios, y continuando en los próximos artículos con el control de las distintas averías que pueden afectar a una embarcación de tipo deportiva o recreativa.' },
    { type: 'subtitle', text: 'Lucha Contra Incendios' },
    { type: 'paragraph', text: 'El fuego es una de las emergencias más importantes que pueden suceder a bordo, y en la cual hay que actuar con rapidez, eficiencia, seguridad y decisión, además de conservar la calma para poder sofocar el fuego y asistir a otras personas hasta tanto pueda contarse con ayuda exterior. Analizaremos entonces las maneras de prevenir un incendio a bordo, y como desarrollar un plan de emergencia eficaz para responder a este tipo de situaciones.' },
    { type: 'subtitle', text: 'Incendio en una embarcación.' },
    { type: 'subtitle', text: 'El Fuego' },
    { type: 'paragraph', text: 'Desde el punto de vista físico, el fuego es un fenómeno donde el oxígeno del aire se combina con los materiales que arden, oxidándolos de forma violenta, proceso al que se lo denomina combustión”. Para que un material entre en combustión es necesario que se den tres condiciones simultáneas.' },
    { type: 'subtitle', text: 'Oxígeno.' },
    { type: 'paragraph', text: 'Debe haber suficiente oxígeno, y el aire que nos rodea contiene cantidades abundantes de éste como para alimentar cualquier proceso de combustión.' },
    { type: 'subtitle', text: 'Combustible.' },
    { type: 'paragraph', text: 'Debe existir un material que sea combustible, y buena parte del contenido de un barco lo es, además de lo que se pueda sumar como parte de la carga transportada.' },
    { type: 'subtitle', text: 'Calor.' },
    { type: 'paragraph', text: 'Debe haber suficiente calor como para iniciar la combustión.' },
    { type: 'paragraph', text: 'Tetraedro de fuego.' },
    { type: 'paragraph', text: 'Estas tres condiciones conforman el llamado triángulo de fuego. Eliminando cualquiera de estas condiciones o dejando una de ellas en una proporción que no sea la conveniente, será suficiente para eliminar el peligro de fuego, o bien si éste ya se ha iniciado, se lo sofocará.' },
    { type: 'paragraph', text: 'Por otra parte, para que se inicie la combustión, es necesario que los materiales se encuentren en forma de gases o vapores. Las naftas, por ejemplo, que desprenden vapores a temperatura ambiente, se inflaman con mucha facilidad, pero los materiales sólidos deben primero calentarse para que desprendan gases que puedan inflamarse. Sin embargo, esto no quiere decir que se vayan a encender por sí solos, sino que requieren mayor temperatura para hacerlo.' },
    { type: 'paragraph', text: 'En consecuencia, podemos diferenciar para cada material una temperatura a la cual el material se gasifica, llamada temperatura de gasificación y una temperatura a la cual el material ya gasificado se enciende, denominada temperatura de ignición.' },
    { type: 'paragraph', text: 'Es frecuente que el origen de los incendios sea un foco relativamente pequeño que luego, por otras circunstancias, se propaga a diferentes objetos y lugares hasta terminar en un gran siniestro. Por eso, una de las cosas importantes que deberá saber para prevenir incendios, es conocer en qué forma se transmite el calor, y en ese sentido podemos decir que lo hace de tres formas posibles, donde una es consecuencia de la otra:' },
    { type: 'subtitle', text: 'Transmisión por Conducción.' },
    { type: 'paragraph', text: 'Se produce cuando un objeto está en contacto directo con otro. En ese caso el calor del objeto más caliente se transmite hacia el más frío.' },
    { type: 'subtitle', text: 'Transmisión por convección.' },
    { type: 'paragraph', text: 'Esto significa que no solo el calor originado en un punto se propagará hacia otro lugar, sino que además lo hará preferentemente de forma convectiva, ascendiendo.' },
    { type: 'paragraph', text: 'Por ejemplo, si en un barco de varias cubiertas se iniciase un incendio en las bodegas, según lo explicado el fuego calentará el aire, el que a su vez ascenderá hacia las cubiertas superiores, arrastrando gases y humos, extendiendo el incendio.' },
    { type: 'subtitle', text: 'Transmisión por radiación.' },
    { type: 'paragraph', text: 'El calor de una llama se siente a cierta distancia del fuego, debido que su energía se irradia a través del medio con el que tiene contacto —por ejemplo, el aire, por efecto del caso anterior— alcanzando otros objetos.' },
    { type: 'paragraph', text: 'Esto quiere decir que no es necesario que un objeto esté en contacto directo con el fuego para que se queme, porque el calor puede transmitirse de un lugar a otro a través del aire.' },
    { type: 'subtitle', text: 'Prevención de Riesgos' },
    { type: 'paragraph', text: 'Lamentablemente, los barcos están compuestos por infinidad de materiales combustibles. Las embarcaciones deportivas, por ejemplo, tienen cascos construidos en resinas plásticas que resultan combustibles cuando alcanzan una cierta temperatura. A ello se añaden los riesgos de la nafta o gasoil almacenado, los mamparos y muebles de madera, las velas en el caso de los veleros, las lonas y los revestimientos sintéticos. En ese entorno, cualquier chispa o llama fuera de control que surja de un motor, de alguna hornalla de la cocina o de la instalación eléctrica, puede rápidamente desatar un incendio.' },
    { type: 'paragraph', text: 'Los incendios a bordo suceden en general debido a problemas de mantenimiento o a errores humanos. Un motor interno sucio de grasa o aceite, bidones de combustible expuestos al Sol, escasa atención a la cocina o un circuito eléctrico deteriorado, son las causas más frecuentes de incendios.' },
    { type: 'paragraph', text: 'De hecho, las fuentes principales de incendio en todo buque tienen que ver con el motor, la cocina, la instalación eléctrica… y los fumadores, por lo que los riesgos pueden reducirse prestando atención a las siguientes recomendaciones:' },
    { type: 'subtitle', text: 'Motor y Sala de Máquinas.' },
    { type: 'paragraph', text: 'Respecto del motor, debe mantenérselo limpio y ventilado, al igual que el compartimiento que lo contiene o la misma sala de máquinas en barcos más grandes, eliminando aceites, grasas y trapos húmedos con estos elementos de cualquier sitio cercano a fuentes de calor.' },
    { type: 'paragraph', text: 'Vigile la existencia de posibles fugas de combustible, corrigiéndolas de inmediato si existiesen.' },
    { type: 'paragraph', text: 'Estibe los bidones de aceite y combustible en sitios alejados de fuentes de calor, ventilados y donde no puedan moverse.' },
    { type: 'subtitle', text: 'Cocina.' },
    { type: 'paragraph', text: 'En la cocina, cierre el gas en el regulador de la garrafa o la llave de paso siempre que no se utilicen las hornallas.' },
    { type: 'paragraph', text: 'Revise a menudo el conducto del gas y sus conexiones en busca de fugas, sea oliéndolo o pintándolo con agua jabonosa. Mantenga los fósforos y encendedores en un cajón o contenedor y no sobre una repisa cercana, desde donde con el movimiento del barco puedan caer sobre el fuego.' },
    { type: 'paragraph', text: 'Mantenga siempre la supervisión sobre las sartenes y las ollas que estén sobre el fuego, ni aun cuando esté fondeado.' },
    { type: 'subtitle', text: 'Electricidad.' },
    { type: 'paragraph', text: 'Respecto de los circuitos eléctricos, revise la instalación en busca de conexiones que pudiesen haberse oxidado, que estén en contacto con humedad, o que se hallan deteriorado al punto de poder provocar un corto circuito.' },
    { type: 'paragraph', text: 'Si la instalación se ha humedecido, séquela y compruebe si existen falsos contactos.' },
    { type: 'paragraph', text: 'En caso de tener que reemplazar fusibles, hágalo con otros del mismo valor.' },
    { type: 'paragraph', text: 'Tampoco instale nuevos equipos o artefactos sin hacerlos pasar por sus correspondientes fusibles o llaves de corte, ni sobrecargue las instalaciones eléctricas.' },
    { type: 'subtitle', text: 'Fumadores.' },
    { type: 'paragraph', text: 'Los fumadores son el último factor de riesgo a controlar.' },
    { type: 'paragraph', text: 'Idealmente no debería permitirse fumar a bordo, pero en caso de acceder a que se lo haga, establezca un área específica para fumadores ubicada en cubierta, a sotavento, y mantenga la prohibición de fumar en el resto del barco y especialmente en el interior de la cabina.' },
    { type: 'paragraph', text: 'Las colillas y las cenizas deben depositarse en los ceniceros, asegurándose que estén apagadas cuando se los vacíe en el cesto de basura. Y nunca estará de más decirlo: no fume cuando cargue o trasvase combustible.' },
    { type: 'paragraph', text: 'Un tal Edward Aloysius Murphy Jr., ingeniero aeroespacial estadounidense, que trabajó buena parte de su vida en el desarrollo de sistemas críticos, se tomó el trabajo de anotar una serie de postulados cuasi empíricos, uno de los cuales dice algo así como que' },
    { type: 'paragraph', text: 'Ed Murphy.' },
    { type: 'paragraph', text: '"Si una cosa puede salir mal, entonces es seguro que saldrá mal".' },
    { type: 'paragraph', text: 'Sí... Estamos hablando de Murphy y sus Leyes.' },
    { type: 'paragraph', text: 'Por eso es que debemos mantenernos alertas a lo que tenemos en el fuego, aun cuando estamos fondeados... porque en cualquier momento puede pasar algún maleducado con su lancha a toda velocidad, sacudiendo nuestra embarcación con el oleaje, y lanzando al aire la sartén con ese poco de aceite que habíamos puesto para freír unas papas.' },
    { type: 'subtitle', text: 'Principio de incendio e Incendio' },
    { type: 'paragraph', text: 'El principio de incendio se convierte en un incendio propiamente dicho cuando el fuego ya se ha desarrollado, superando la capacidad de control inmediato con medios portátiles, propagándose o amenazando con propagarse, y poniendo en riesgo la integridad de la embarcación y la seguridad de las personas a bordo, requiriendo procedimientos de emergencia y, eventualmente, abandono o asistencia externa.' },
    { type: 'subtitle', text: 'Extinción del Fuego' },
    { type: 'paragraph', text: 'El fuego se lo clasifica según cinco tipos, denominados con las letras "A", "B", "C", "D" y "K", agrupando cada uno de ellos a los elementos combustibles de similares características, facilitando así la identificación de los medios de prevención y combate más adecuadas para cada caso.' },
    { type: 'paragraph', text: 'Fuego Clase "A"' },
    { type: 'paragraph', text: 'Fuego Clase "A".' },
    { type: 'paragraph', text: 'Es aquel que se inicia a partir de materiales que contienen carbono, como la madera, el papel, la basura, las telas y algunos plásticos, y que generan brasas de carbón y cenizas.' },
    { type: 'paragraph', text: 'La extinción de este tipo fuego puede realizarse con agua o con extintores basado en polvo químico seco y gas halón.' },
    { type: 'paragraph', text: 'Fuego Clase "B"' },
    { type: 'paragraph', text: 'Fuego Clase "B".' },
    { type: 'paragraph', text: 'Se origina a partir de líquidos o sólidos inflamables, que pueden o no ser solubles en agua, tales como los alcoholes, la nafta, el aguarrás, y los diluyentes de pinturas, y por otra parte los gases derivados del petróleo como el propano, el butano o el metano.' },
    { type: 'paragraph', text: 'Los extintores que se emplean para combatirlos son aquellos que contienen dióxido de carbono o bien los polvos químicos secos.' },
    { type: 'paragraph', text: 'Fuego Clase "C"' },
    { type: 'paragraph', text: 'Fuego Clase "C".' },
    { type: 'paragraph', text: 'Se produce por causas eléctricas y su mecanismo no es una combustión sino una ignición. Los sucesos más frecuentes que provocan este tipo de fuego son los cortocircuitos y el sobrecalentamiento de los cables, en los tomacorrientes o en el tablero, aunque también pueden ocurrir por la energía estática.' },
    { type: 'paragraph', text: 'Para combatir este tipo de fuego se recomienda el empleo de extintores en base a polvo químico, de monóxido de carbono y de gas halón. Recuerde que para sofocar este tipo de fuego no debe usarse agua o espuma, si antes no se ha interrumpido la corriente eléctrica.' },
    { type: 'paragraph', text: 'Fuego Clase "D"' },
    { type: 'paragraph', text: 'Fuego Clase "D".' },
    { type: 'paragraph', text: 'Se trata del producido por la reacción de algunos metales tales como el sodio, el potasio y el magnesio, los que reaccionan de manera explosiva al entrar en contacto con el agua.' },
    { type: 'paragraph', text: 'Cuando se produce un fuego de este tipo deben emplearse extintores de polvo químico seco. En ciertas condiciones puede emplearse tierra o arena seca y nunca agua ni extintores que contengan dióxido de carbono, líquidos vaporizantes o espuma, ya que pueden dar lugar a reacciones que podrían liberar mucho más calor.' },
    { type: 'paragraph', text: 'Fuego Clase "K"' },
    { type: 'paragraph', text: 'Fuego Clase "K".' },
    { type: 'paragraph', text: 'Es el derivado de la utilización de aceites y grasas para cocinar. Las altas temperaturas que alcanzan los aceites en un incendio superan largamente las de otros líquidos inflamables, haciendo inefectivos los agentes de extinción normales.' },
    { type: 'paragraph', text: 'El agente extintor para este tipo de fuego es una espuma que forma una capa sobre el combustible aislándolo del aire, impidiendo así la reignición. El agente extintor se descarga en forma de rocío fino sobre los artefactos en llamas, reduciendo la posibilidad de salpicar grasa o aceite caliente.' },
    { type: 'paragraph', text: 'Existe otra clase de fuego… el de tipo "F", que clasifica a los de origen radioactivo.' },
    { type: 'paragraph', text: 'Por lo tanto, hasta que no haya veleros o lanchas a propulsión atómica, no hablaremos de ellos.' },
    { type: 'paragraph', text: 'elemento extintor' },
    { type: 'paragraph', text: 'materiales que generan brasas (madera, papel, cartón y otros)' },
    { type: 'paragraph', text: 'líquidos inflamables (naftas, alcoholes y otros)' },
    { type: 'paragraph', text: 'energía eléctrica' },
    { type: 'paragraph', text: 'metales combustibles (aluminio, magnesio y otros)' },
    { type: 'paragraph', text: 'aceites y grasas de cocina' },
    { type: 'paragraph', text: 'agua' },
    { type: 'paragraph', text: '(acción de enfriamiento).' },
    { type: 'paragraph', text: '(esparce el combustible).' },
    { type: 'paragraph', text: '(conduce la electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'APFF' },
    { type: 'paragraph', text: '(enfría y sofoca).' },
    { type: 'paragraph', text: '(sofoca por medio de espuma).' },
    { type: 'paragraph', text: '(conduce la electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'anhídrido carbónico' },
    { type: 'paragraph', text: '(no apaga fuegos profundos).' },
    { type: 'paragraph', text: '(sofoca por medio de espuma).' },
    { type: 'paragraph', text: '(no es conductor de electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'polvo ABC' },
    { type: 'paragraph', text: '(se funde sobre los elementos).' },
    { type: 'paragraph', text: '(rompe la cadena de combustión).' },
    { type: 'paragraph', text: '(no es conductor de electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'polvo' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(rompe la cadena de combustión).' },
    { type: 'paragraph', text: '(no es conductor de electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'HFCC' },
    { type: 'paragraph', text: '(absorbe el calor).' },
    { type: 'paragraph', text: '(rompe la cadena de combustión).' },
    { type: 'paragraph', text: '(no es conductor de electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'polvo seco' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(usar el polvo específico).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'rocío de agua' },
    { type: 'paragraph', text: '(absorbe el calor).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es conductor de la electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: 'químico húmedo' },
    { type: 'paragraph', text: '(absorbe el calor).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(no es conductor de la electricidad).' },
    { type: 'paragraph', text: '(no es específico para este uso).' },
    { type: 'paragraph', text: '(actúa saponificando).' },
    { type: 'paragraph', text: 'La estrategia de ataque del fuego tiene que llevarse a cabo teniendo en mente los tres elementos básicos que facilitan su desarrollo: la necesidad de que exista un material combustible, que halla calor y presencia de oxígeno. En función de esto, habrá que atacar el fuego por uno de estos frentes, para luego operar sobre los tres.' },
    { type: 'paragraph', text: 'Considere entonces los siguientes aspectos:' },
    { type: 'paragraph', text: 'Eliminar los combustibles.' },
    { type: 'paragraph', text: 'Aleje del fuego los bidones de combustible, los contenedores de productos inflamables, las velas y los cabos, no solo porque puedan arder sino porque además producirán humos muy tóxicos.' },
    { type: 'paragraph', text: 'Cierre el paso de combustible del motor, el gas de la cocina y corte la electricidad.' },
    { type: 'paragraph', text: 'Suprimir el oxígeno.' },
    { type: 'paragraph', text: 'Elimine las corrientes de aire deteniendo el barco o, si hay viento, orientando la embarcación de tal forma que el fuego quede a sotavento de ésta.' },
    { type: 'paragraph', text: 'Enfriar el ambiente.' },
    { type: 'paragraph', text: 'Es importante bajar la temperatura de las zonas contiguas al incendio en cuanto sea posible, echando por ejemplo baldes de agua contra los mamparos o la cubierta. Y aquí vale el mismo comentario que para el caso anterior, tenga precaución con el agua si lo que arde son combustibles líquidos —fuego tipo “B”— para no esparcirlos.' },
    { type: 'paragraph', text: 'Como hemos visto, el elemento más común de lucha contra incendios es el "extintor", el cual deberá estar situado en un lugar de fácil y rápido acceso. Luego, teniendo en cuenta que no hay ningún extintor apto para combatir las cinco clases de fuego, no será una mala idea contar con más de uno a bordo, tal que se pueda combinar entre ellos la cobertura de todos los riesgos. Para operar el extinguidor deberá primero soltar la traba que asegura el gatillo, y luego accionarlo desde una distancia de unos 3 metros dirigiendo el chorro de gas hacia la base del fuego barriéndolo de lado a lado. Luego de la primera descarga, verifique si el fuego se ha extinguido, y en caso contrario repita la maniobra dirigiendo el chorro de gas hacia la base de las llamas residuales, hasta haberlo sofocado.' },
    { type: 'paragraph', text: 'No obstruya los lugares destinados a almacenar los elementos de lucha contra incendios. Los primeros minutos son importantes en toda extinción.' },
    { type: 'paragraph', text: 'Mantas ignífugas y extintores.' },
    { type: 'paragraph', text: 'Otro elemento útil para combatir el fuego es la manta ignífuga, que consiste en un cobertor similar a una manta, fabricada con telas de materiales resistentes al fuego, tales como el amianto, el nomex o lana humedecida con retardadores, y que actúan sofocando el fuego cuando se las arroja sobre las llamas.' },
    { type: 'paragraph', text: 'La velocidad de reacción es uno de los factores fundamentales en la lucha contra el fuego. Es vital, cuando se lo detecte, actuar con rapidez para contenerlo en su origen, no dejando que se expanda, para luego extinguirlo. Otro factor que suma al éxito en la lucha contra un principio de incendio es el conocimiento que los tripulantes tengan acerca del uso de los elementos de extinción, estrategias y técnicas de ataque y cuidados que deben tenerse.' },
    { type: 'paragraph', text: 'De acuerdo con estos conceptos, comentaremos ahora las tácticas más adecuadas para los principales principios de incendio que pueden ocurrir a bordo.' },
    { type: 'paragraph', text: 'Fuegos en la Cocina' },
    { type: 'paragraph', text: 'caso' },
    { type: 'paragraph', text: 'Sartén o cacerola con aceite o grasas ardiendo.' },
    { type: 'paragraph', text: 'extinción' },
    { type: 'paragraph', text: 'Ante esta situación, la mejor estrategia es extinguir el fuego quitándole el oxígeno.' },
    { type: 'paragraph', text: 'Si tiene una manta ignífuga, también puede usarla.' },
    { type: 'paragraph', text: 'no usar' },
    { type: 'paragraph', text: 'No eche agua al fuego, porque producirá un efecto explosivo, lanzando el aceite encendido en todas direcciones.' },
    { type: 'paragraph', text: 'Tampoco intente manipular la sartén o cacerola tratando de tirar su contenido al agua fuera del barco, pues lo más probable es que termine salpicando aceite ardiendo sobre el barco o sobre Usted mismo, complicando la situación.' },
    { type: 'paragraph', text: 'No utilice extintores tipo "ABC".' },
    { type: 'paragraph', text: 'Fuego en Maderas, Telas, Cartones o Papeles' },
    { type: 'paragraph', text: 'caso' },
    { type: 'paragraph', text: 'Principio de incendio o fuego en maderas, papeles, cartones, telas u otros materiales similares.' },
    { type: 'paragraph', text: 'extinción' },
    { type: 'paragraph', text: 'También puede usar agua lanzándola con un balde u otro contenedor directamente sobre el fuego.' },
    { type: 'paragraph', text: 'no usar' },
    { type: 'paragraph', text: 'No use polvos secos o arena seca, pues no lograr aislar el oxígeno del foco del fuego.' },
    { type: 'paragraph', text: 'Fuego en el Motor o la Sala de Máquinas' },
    { type: 'paragraph', text: 'caso' },
    { type: 'paragraph', text: 'Principio de incendio o fuego en un componente del motor o dentro de la sala de máquinas de la embarcación.' },
    { type: 'paragraph', text: 'extinción' },
    { type: 'paragraph', text: 'Corte de inmediato la entrada de combustible, y la electricidad si se tratase de un grupo electrógeno.' },
    { type: 'paragraph', text: 'Generalmente los gabinetes que contienen los motores internos de los barcos o las salas de máquinas en embarcaciones de mayor porte están equipadas con sistemas de extinción de incendios dedicados. Si no se ha activado automáticamente, hágalo manualmente.' },
    { type: 'paragraph', text: 'Si no cuenta con un sistema de extinción dedicado, utilice un extintor para fuegos clase "B" o triclase "ABC" dirigiendo el extintor por una abertura lo más pequeña posible descargando su contenido dentro del habitáculo. Hecho esto verifique visualmente si el fuego se vuelve a encender, repitiendo el procedimiento.' },
    { type: 'paragraph', text: 'no usar' },
    { type: 'paragraph', text: 'No abra el compartimiento en el que se encuentra el motor hasta tanto estar seguro de que el evento puede estar bajo control.' },
    { type: 'paragraph', text: 'Fuego en Cubierta' },
    { type: 'paragraph', text: 'caso' },
    { type: 'paragraph', text: 'Principio de incendio o incendio declarado en algún punto de la cubierta de la embarcación.' },
    { type: 'paragraph', text: 'extinción' },
    { type: 'paragraph', text: 'En caso de derrames, comience a extinguir desde abajo y hacia arriba. Oriente la embarcación de tal forma que el fuego quede a sotavento.' },
    { type: 'paragraph', text: 'no usar' },
    { type: 'paragraph', text: 'No le dé la espalda al fuego en ningún momento.' },
    { type: 'paragraph', text: 'Luego de Extinguido el Fuego' },
    { type: 'paragraph', text: 'Una vez que tiene el evento bajo control y el fuego apagado, permanezca atento a un posible reinicio. No se aleje de un lugar donde existan restos de fuego, sin tomar las medidas necesarias para extinguirlos totalmente.' },
    { type: 'paragraph', text: 'Por último, en cuanto a los cuidados a tener en la lucha contra incendios, es importante que los tripulantes tengan el conocimiento suficiente para atacar el fuego y que conozcan también como deben protegerse mientras lo hacen. Así entonces es recomendable actuar como sigue:' },
    { type: 'paragraph', text: 'Piense antes de actuar.' },
    { type: 'paragraph', text: 'Dé la voz de alarma, pero no cause pánico. Conserve siempre la serenidad.' },
    { type: 'paragraph', text: 'Siga las Instrucciones.' },
    { type: 'paragraph', text: 'Esto es muy importante. Siga las instrucciones de quién está dirigiendo, o asuma un buen papel de líder dando instrucciones claras y concretas.' },
    { type: 'paragraph', text: 'Formas de Escape.' },
    { type: 'paragraph', text: 'Para salir del compartimento en donde se desarrolla el fuego, hay que hacerlo arrastrándose ya que en el suelo hay más oxígeno y la temperatura es menor. Es conveniente taparse la nariz con un trapo húmedo para evitar aspirar el humo, e inclusive el cuerpo para evitar quemaduras. Si se encuentra en medio del fuego, sin ayuda y sin extintor, mantenga la calma y pida auxilio.' },
    { type: 'paragraph', text: 'Cabuyería: Tipos de cabos y su aplicación.' },
    { type: 'paragraph', text: 'Técnicas de Fondeo.' },
  ],

  quiz: [
    {
      question: '¿Cuáles son los tres elementos del triángulo del fuego?',
      options: ['Agua, combustible y calor', 'Oxígeno, combustible y calor', 'Oxígeno, agua y combustible', 'Calor, luz y oxígeno'],
      correctAnswer: 1,
      explanation: 'El triángulo del fuego está formado por oxígeno, combustible y calor. Sin uno de estos elementos, el fuego no puede iniciarse ni mantenerse.'
    },
    {
      question: '¿Qué tipo de extintor debe usarse en un fuego eléctrico (Clase C)?',
      options: ['Agua', 'Espuma', 'Polvo químico seco o CO2', 'Arena'],
      correctAnswer: 2,
      explanation: 'Para fuegos eléctricos se recomiendan extintores de polvo químico seco, CO2 o halón. Nunca debe usarse agua.'
    },
    {
      question: '¿Cuál es la causa más frecuente de incendios a bordo?',
      options: ['Rayos', 'Problemas de mantenimiento o errores humanos', 'Combustible almacenado', 'Cocina a gas'],
      correctAnswer: 1,
      explanation: 'Los incendios a bordo suceden generalmente debido a problemas de mantenimiento o errores humanos, especialmente en motor, cocina e instalación eléctrica.'
    },
    {
      question: '¿Qué debe hacerse ante un principio de incendio?',
      options: ['Abandonar el barco inmediatamente', 'Intentar extinguirlo con los medios portátiles disponibles', 'Esperar a que pase', 'Llamar por radio primero'],
      correctAnswer: 1,
      explanation: 'Un principio de incendio es un fuego incipiente que puede ser controlado con medios portátiles. Se debe actuar rápidamente para extinguirlo antes de que se propague.'
    },
  ]
};