import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'desarboladuras',
  title: 'Desarboladuras',
  readingTime: 7,

  content: [
    { type: 'title', text: 'Control de Averías: Desarboladuras' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'paragraph', text: 'La desarboladura es una de las averías más comunes y serias que puede sufrir una embarcación deportiva de vela, por lo que debe ser tratada con especial cuidado.' },
    { type: 'paragraph', text: 'Los arquitectos navales suelen ser conservadores cuando consideran los parámetros de seguridad de sus diseños. Tal es así que calculan la resistencia del mástil y su jarcia para soportar esfuerzos bien por sobre los valores nominales planteados para cada embarcación. Por este motivo es que cuando un velero desarbola se debe en general a la falla de alguna pieza, sea por defectos de construcción o por falta de mantenimiento, o bien a causa de errores de navegación que derivan en la rotura del mástil.' },
    { type: 'paragraph', text: 'En ese contexto, podemos resumir las causas de desarboladuras en las siguientes:' },
    { type: 'paragraph', text: 'Errores Humanos' },
    { type: 'paragraph', text: 'Debido a sobrecarga del aparejo, provocada por exceso de velamen ante condiciones de vientos fuertes y arrachados.' },
    { type: 'paragraph', text: 'Por golpes o abordajes, incluyendo el contacto con el fondo. En estos casos el mástil puede dañarse al engancharse con el de la embarcación abordada, o producto de la sacudida al golpear con el otro barco o el fondo.' },
    { type: 'paragraph', text: 'Debido a malas maniobras, como viradas o trasluchadas violentas, especialmente en condiciones de vientos fuertes.' },
    { type: 'paragraph', text: 'Un caso común de rotura de mástil ocurre durante las trasluchadas involuntarias en condiciones de vientos fuertes, en las que el velero termina acostado, después de haberse ido por ojo, con las velas en contacto o directamente sumergidas en el agua, oponiendo resistencia al adrizamiento.' },
    { type: 'paragraph', text: 'En ese caso, cuando el barco intenta lograr la vertical, el mástil cede y se parte al no poder sostener el peso de las velas cargadas de agua.' },
    { type: 'paragraph', text: 'Mantenimiento y Obsolescencia de Materiales' },
    { type: 'paragraph', text: 'Fallas estructurales en elementos de la jarcia firme, particularmente en cables, terminales o tensores, por corrosión, fatiga o mantenimiento deficiente.' },
    { type: 'paragraph', text: 'Construcción' },
    { type: 'paragraph', text: 'Defectos constructivos o armado incorrecto del aparejo.' },
    { type: 'paragraph', text: 'A partir de las probables causas de desarboladura mencionadas, la prevención pasará por el mantenimiento preventivo rutinario del mástil y su jarcia, y por los cuidados en las técnicas de navegación.' },
    { type: 'paragraph', text: 'Mantenimiento Preventivo' },
    { type: 'paragraph', text: 'El mantenimiento preventivo de la embarcación constituye una de las medidas más eficaces para reducir los riesgos de todo tipo a bordo. La inspección periódica de la arboladura y su jarcia permite detectar desgastes, corrosión o fallas incipientes antes de que se transformen en emergencias.' },
    { type: 'paragraph', text: 'Así entonces, proponemos revisar lo siguiente:' },
    { type: 'paragraph', text: 'Vida Útil.' },
    { type: 'paragraph', text: 'Ajuste de tensor de obenque.' },
    { type: 'paragraph', text: 'Los astilleros y la experiencia práctica indican que la jarcia fija debería ser reemplazada cada 8 a 10 años.' },
    { type: 'paragraph', text: 'Sin embargo, esta declaración merece comentarios adicionales.' },
    { type: 'paragraph', text: 'Luego, y aun cuando los materiales estén dentro de su rango de vida útil, y que son muy duraderos, tenga presente que están sometidas a tensiones todo el tiempo, aun cuando el barco se encuentra en la amarra. Por este motivo es que es recomendable efectuar una revisión periódica de todos los componentes desde el primer día.' },
    { type: 'paragraph', text: 'Óxido y Deterioro.' },
    { type: 'paragraph', text: 'Óxido en terminales.' },
    { type: 'paragraph', text: 'Si descubre algún elemento de la jarcia deteriorado, o con presencia de óxido o que muestra fisuras, deberá reemplazarlo.' },
    { type: 'paragraph', text: 'Tenga en cuenta que cuando se sustituye un cable de la jarcia por otro nuevo, éste deberá ser ajustado a lo largo de las primeras horas de uso, hasta tanto llegue a su tensión nominal.' },
    { type: 'paragraph', text: 'Revise también los herrajes de las crucetas y de las terminaciones de la jarcia en el palo.' },
    { type: 'paragraph', text: 'Verifique los anclajes de los obenques y estayes, y la fijación de las landas. La fibra o el material del casco alrededor de ellos deben estar sanos y sin ningún indicio de deslaminación.' },
    { type: 'paragraph', text: 'Mástil.' },
    { type: 'paragraph', text: 'Revisión de crucetas.' },
    { type: 'paragraph', text: 'Revise la alineación del mástil ajustando la tensión de los obenques en caso de que esté desviado a uno u otro lado. Si observa una pronunciada torsión o deformación deberá hacerlo revisar por un profesional, pues es probable que el barco haya navegado mucho tiempo con los obenques demasiado flojos lo cual habrá hecho trabajar excesivamente al palo corriendo el riesgo de partirse por esfuerzo excesivo del material.' },
    { type: 'paragraph', text: 'Observe también el pie del mástil en busca de señales de óxido que pudieran debilitar su soporte, ya que es aquí donde se concentran todos los esfuerzos de compresión del palo debido a la lógica tensión de toda la jarcia. Cuando la compresión del palo es muy alta, éste tiende a fatigarse más rápidamente aumentando el riesgo de rotura. Pase entonces la mano por la salida de las drizas en la parte baja del palo, y si al tacto detecta un ligero abultamiento en esa zona, se deberá a un problema de compresión.' },
    { type: 'paragraph', text: 'El palo actúa en ocasiones también como soporte para otras piezas, como por ejemplo el molinete de drizas, o puentes para fijación de motones, o para montar el soporte del radar o la guía del tangón, que se fijan al palo mediante remaches o tornillos. Verifique esas fijaciones en búsqueda de signos de óxido, desgaste, y asegurándose de que no se hayan aflojado.' },
    { type: 'paragraph', text: 'En cuanto a las crucetas, compruebe que la pieza que las conecta con el palo no tenga juego. Luego revise sus extremos verificando el punto de pasaje de los obenques medios y altos.' },
    { type: 'paragraph', text: 'Repuestos y Materiales de Reparación.' },
    { type: 'paragraph', text: 'En singladuras de larga distancia es conveniente equipar la caja de herramientas con algunas piezas de repuesto que puedan servir para resolver averías en la jarcia.' },
    { type: 'paragraph', text: 'Esto incluye tanto cables para reemplazar obenques y stays, como terminales, tensores, landas de fortuna y otros elementos auxiliares.' },
    { type: 'subtitle', text: 'Control de Daños' },
    { type: 'paragraph', text: 'Dependiendo de qué lado se inicie la falla: si del lado de sotavento o el de barlovento, habrá más o menos tiempo para tomar acciones que permitan salvar la arboladura.' },
    { type: 'paragraph', text: 'Por ejemplo, cuando se rompe un cable de la jarcia firme, tal como un obenque o un stay, del lado de barlovento, se verá al cable en cuestión soltarse y prácticamente en el mismo instante se escuchará la rotura del mástil, que caerá hacia sotavento.' },
    { type: 'paragraph', text: 'Todo eso sucede instantáneamente, en décimas de segundo, dándole nada de tiempo a la tripulación para salvar la situación.' },
    { type: 'paragraph', text: 'Veremos entonces dos casos posibles de control de daños: el primero estará dedicado a un evento en el cual se puede salvar el mástil ante el primer signo de riesgo de caída, y el segundo intentará dar ideas de cómo reaccionar si finalmente el mástil se ha caído.' },
    { type: 'paragraph', text: 'Reacción ante la Detección de una Falla' },
    { type: 'paragraph', text: 'En caso de que pudiese actuar, inmediatamente después de detectar alguna falla en la jarcia que ponga en riesgo la arboladura, deberá virar la embarcación tan rápido como pueda para sacarle tensión el cable dañado, dejándolo a sotavento. Hecho esto, deberá bajar el velamen para efectuar con urgencia una reparación de fortuna.' },
    { type: 'paragraph', text: 'La expresión "reparación de fortuna" refiere a toda reparación provisoria, realizada con los medios y elementos disponibles a bordo.' },
    { type: 'paragraph', text: 'El objetivo de la reparación de fortuna es restablecer en algún nivel la funcionalidad perdida, permitiendo continuar la navegación o alcanzar un lugar seguro en el cual realizar la reparación definitiva.' },
    { type: 'paragraph', text: 'Obenque de fortuna.' },
    { type: 'paragraph', text: 'Una de las alternativas para darle sostén al mástil a partir de la rotura de un obenque o un stay consiste en hacer firme cualquier driza disponible en el arraigo o en la landa de ese cable, o en todo caso en alguna cornamusa ubicada cerca de la base del obenque o del stay dañado. De más está decir que esta reparación solo será una medida paliativa destinada a resguardar el palo, y que no permitirá cargar de tensión el lado de la rotura. En esta condición, si no es imprescindible seguir navegado a vela, es aconsejable arriar las velas en su totalidad para limitar al mínimo los esfuerzos de la jarcia, y continuar navegando a motor.' },
    { type: 'paragraph', text: 'Si el cable se rompiese en la unión con uno de sus terminales deberá cortarlo por arriba de la zona del daño, y colocar un terminal nuevo o en todo caso usar prensacables para armar una gaza en el extremo del obenque o del stay que permita su unión con el tensor utilizando un grillete si hubiese quedado corto.' },
    { type: 'paragraph', text: 'Si la falla fuese en una de las crucetas, la forma de actuar deberá ser idéntica a la descripta más arriba, es decir, virar al instante para situar la cruceta dañada a sotavento y, de igual modo, deberá afirmar una driza a la banda correspondiente.' },
    { type: 'paragraph', text: 'Reacción ante la Caída del Mástil' },
    { type: 'paragraph', text: 'Si no se hubiese hecho a tiempo para resolver la rotura, el palo terminará finalmente rompiéndose y la magnitud de los daños dependerá del tipo de mástil.' },
    { type: 'paragraph', text: 'Si se trata de un palo apoyado en cubierta, caerá limpiamente, dañando parte de la jarcia, desgarrando quizás alguna de las velas y rompiendo seguramente alguno de los guardamancebos. Sin embargo, en los veleros que tienen palo pasante las consecuencias serán mayores, pues el eventual abanicado que producirá el palo debajo de la cubierta podría romper todo a su paso, dañando inclusive la cubierta por la fuerza de palanca que producirá en la fogonadura —el hueco por donde pasa el palo—.' },
    { type: 'paragraph', text: 'Corte de la jarcia.' },
    { type: 'paragraph', text: 'En cualquier caso, una vez que el palo ha caído deberá evaluarse rápidamente si hay heridos o caídas de tripulantes al agua, o daños a la estructura del barco que lo pongan en peligro, para luego decidir si es factible recuperar el palo y lo que quede del velamen.' },
    { type: 'paragraph', text: 'En cuanto tenga alguna oportunidad, deberá comunicar a la autoridad su situación y que ha abandonado el palo y su velamen a la deriva, puesto que al momento de hacerlo se ha convertido en un obstáculo para la navegación.' },
    { type: 'paragraph', text: 'Note que la comunicación por radio, si la o las antenas, estaban montadas en el mástil, ya no estarán disponibles, debiendo armar una antena de fortuna o bien efectuar la comunicación por otro equipo o medio disponible.' },
    { type: 'paragraph', text: 'Si en cambio las condiciones climáticas permitiesen recuperar el mástil, deberá intentar acercar los restos al costado de la embarcación, haciendo firme uno de sus extremos en alguna cornamusa a popa o a proa, y luego comenzar a levantarlo por el extremo libre hacia la cubierta. Si el mástil fuese demasiado pesado como para izarlo, podrá sujetar algunas defensas a sus restos para mantenerlos a flote a fin de poder remolcarlos, esta maniobra vale la pena realizarla solo si el palo no sufrió ningún daño o si lo que queda de él es recuperable.' },
    { type: 'paragraph', text: 'Recuperación del aparejo y las velas.' },
    { type: 'paragraph', text: 'Una de las alternativas más prácticas es utilizar alguna parte del palo rescatado, o de la botavara o el tangón para armar una nueva estructura lo suficientemente robusta, que permita montar alguna vela de la forma que sea con el objeto de lograr mover el barco. En última instancia, si no quedasen a bordo ninguna de estas partes, podrá fabricar algún sostén utilizando un remo o el bichero, o hasta inclusive el palo de alguna escoba. La intención del aparejo de fortuna es devolver la tracción del viento al barco, por lo que en ese sentido cualquier aparejo que surja de su imaginación será útil.' },
    { type: 'paragraph', text: 'Finalmente, considere que al caer el palo perderá también la antena del equipo de radio, por lo que para estas situaciones es útil contar a bordo con un equipo de mano —un handy— con el cual poder mantener las comunicaciones abiertas.' },
    { type: 'paragraph', text: 'Cabuyería: Tipos de cabos y su aplicación.' },
    { type: 'paragraph', text: 'Técnicas de Fondeo.' },
  ],

  quiz: [
    {
      question: '¿Qué es una desarboladura?',
      options: ['La pérdida de la arboladura (mástil, botavara, etc.)', 'La caída de una vela', 'El desgaste del casco', 'La rotura del timón'],
      correctAnswer: 0,
      explanation: 'Una desarboladura es la pérdida total o parcial de la arboladura, incluyendo mástil, botavara y otros elementos de soporte del velamen.'
    },
    {
      question: '¿Cuál es la prioridad inmediata tras una desarboladura?',
      options: ['Reparar el mástil', 'Garantizar la seguridad de la tripulación y evitar daños mayores', 'Arriar todas las velas', 'Llamar a un remolcador'],
      correctAnswer: 1,
      explanation: 'La prioridad es garantizar la seguridad de la tripulación y evitar que los restos de la arboladura causen daños adicionales al casco o a las personas.'
    },
  ]
};