import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'vias-de-agua',
  title: 'Vías de Agua',
  readingTime: 8,

  content: [
    { type: 'title', text: 'Control de Averías: Vías de Agua' },
    { type: 'subtitle', text: 'Introducción' },
    { type: 'paragraph', text: 'No necesariamente una vía de agua debe encontrarse por debajo de la línea de flotación para representar un peligro: un barco puede comenzar a embarcar agua, por ejemplo, a través de una ventilación o una escotilla que haya quedado abierta por falta de atención durante una navegación con mal tiempo.' },
    { type: 'paragraph', text: 'Vía de agua.' },
    { type: 'subtitle', text: 'Prevención' },
    { type: 'paragraph', text: 'Mantenimiento Preventivo' },
    { type: 'paragraph', text: 'Así entonces, proponemos revisar lo siguiente:' },
    { type: 'paragraph', text: 'Válvulas y Pasacascos.' },
    { type: 'paragraph', text: 'Tapón de madera de emergencia.' },
    { type: 'paragraph', text: 'Una parte significativa de las vías de agua se origina en las conexiones de las válvulas y pasacascos, que vinculan las tuberías de entrada y salida de los distintos circuitos de agua de la embarcación con el medio exterior. Con el paso del tiempo, estos elementos pueden degradarse, aflojarse o romperse, dando lugar a filtraciones o incluso a un ingreso masivo de agua.' },
    { type: 'paragraph', text: 'Es importante entonces revisar periódicamente el estado de los pasacascos y válvulas, verificando que no se encuentren corroídos, así como controlar las conexiones de los ductos asociados, comprobando que no presenten pérdidas.' },
    { type: 'subtitle', text: 'Motores Internos.' },
    { type: 'paragraph', text: 'En el caso de embarcaciones con motores internos, debe revisarse el prensaestopa ubicado en la bocina de la línea de eje, engrasándolo cuando sea necesario.' },
    { type: 'paragraph', text: 'Debe tenerse presente que, con el motor en marcha, es normal que ingresen algunas gotas de agua a través de este conjunto. Si, en cambio, se observa un hilo o chorro continuo, ello indica una falta de ajuste, por lo que deberá aumentarse la presión. Con el motor detenido, la estanqueidad debería ser total.' },
    { type: 'paragraph', text: 'Revise también el circuito de refrigeración, comprobando el buen estado del codo de escape, mangueras, sifones y válvulas antisifón, ya que una falla en estos elementos puede provocar un ingreso rápido de agua.' },
    { type: 'subtitle', text: 'Timón.' },
    { type: 'paragraph', text: 'En el caso del mecanismo del timón, cuando este cruza el casco, revise la limera y el ajuste de la mecha del timón.' },
    { type: 'paragraph', text: 'Instrumentos y Sensores.' },
    { type: 'paragraph', text: 'Verifique las interfaces de los sensores que tienen contacto directo con el agua, tales como la ecosonda y la corredera.' },
    { type: 'paragraph', text: 'Bombas de Achique.' },
    { type: 'paragraph', text: 'Compruebe el correcto funcionamiento de las bombas de achique, incluyendo sus sensores, tanto en los sistemas automáticos como en los manuales.' },
    { type: 'paragraph', text: 'Desagües e Imbornales.' },
    { type: 'paragraph', text: 'Controle los imbornales y ductos de desagüe del cockpit y áreas que puedan acumular agua, asegurando que se encuentren libres de obstrucciones y correctamente conectados, ya que su obstrucción puede generar embarque de agua desde cubierta hacia el interior.' },
    { type: 'paragraph', text: 'Casco y Cubierta.' },
    { type: 'paragraph', text: 'Inspeccione el casco en búsqueda de grietas, golpes o delaminaciones, prestando especial atención a zonas cercanas a quilla, codaste y refuerzos estructurales.' },
    { type: 'paragraph', text: 'En barcos de madera, controle particularmente las filtraciones entre las tracas y el estado general de las mismas.' },
    { type: 'paragraph', text: 'En la cubierta verifique el correcto asentamiento de escotillas y tambuchos, asegurando que sus burletes y sellos se encuentren limpios y en buen estado.' },
    { type: 'paragraph', text: 'Herramientas.' },
    { type: 'paragraph', text: 'Kit de reparación de casco.' },
    { type: 'paragraph', text: 'Equipe la caja de herramientas con algún sellador siliconado, masilla epoxi apta para aplicación sobre superficies húmedas, y un rollo de "duct tape", ya que estos elementos pueden resultar útiles para taponar filtraciones o efectuar reparaciones de emergencia.' },
    { type: 'paragraph', text: 'Para singladuras de larga duración, es conveniente llevar, además, un "kit de reparación de casco". Estos pueden adquirirse directamente bajo esa denominación en casas especializadas, o bien configutar uno a medida de las propias necesidades.' },
    { type: 'subtitle', text: 'Control Previo a la Zarpada' },
    { type: 'paragraph', text: 'Antes de zarpar, y especialmente cuando se prevea una navegación en aguas con oleaje importante o en condiciones de mal tiempo, puede realizar lo siguiente:' },
    { type: 'paragraph', text: 'Casco y Cubierta.' },
    { type: 'paragraph', text: 'Cierre todos los tambuchos, ventilaciones, escotillas y esclusas que no sea necesario mantener abiertos durante la singladura.' },
    { type: 'paragraph', text: 'Actualización de Información.' },
    { type: 'paragraph', text: 'Consulte los Radioavisos a los Navegantes, ya que en ellos se informan nuevos riesgos para la navegación, tales como naufragios recientes o la presencia de objetos a la deriva potencialmente peligrosos.' },
    { type: 'paragraph', text: 'Durante la Navegación' },
    { type: 'paragraph', text: 'Durante la navegación, especialmente en condiciones de mal tiempo, adopte las siguientes medidas:' },
    { type: 'paragraph', text: 'Sentina.' },
    { type: 'paragraph', text: 'Mantenga la sentina siempre seca, a fin de poder detectar con certeza cualquier entrada de agua y, en caso de producirse, evaluar el caudal que ingresa.' },
    { type: 'subtitle', text: 'Seguridad.' },
    { type: 'paragraph', text: 'Asimismo, evite navegar en zonas donde la profundidad no ofrezca un margen de seguridad adecuado para su embarcación. En caso de hacerlo, opere siempre a velocidad de seguridad y teniendo en cuenta la información proporcionada por la ecosonda.' },
    { type: 'subtitle', text: 'Control de Daños' },
    { type: 'paragraph', text: 'Al detectar un volumen de agua inusual en el interior de la embarcación, es imperativo identificar su punto de origen y aplicar las medidas de control necesarias con la mayor rapidez posible.' },
    { type: 'paragraph', text: 'En todos los casos, ante una situación de emergencia, el procedimiento de control de daños deberá seguir, en líneas generales, los pasos que se detallan a continuación:' },
    { type: 'paragraph', text: 'paso 1' },
    { type: 'paragraph', text: 'Confirmar el Caso' },
    { type: 'paragraph', text: 'Si al momento de actuar no se tiene certeza de que la inundación se debe a una vía de agua, es posible confirmar rápidamente su origen observando, oliendo o probando el líquido.' },
    { type: 'paragraph', text: 'Si el agua tiene sabor salado o presenta el color característico del agua del río, puede sospecharse la existencia de una vía de agua, ya sea por rotura de una válvula, una perforación en la obra viva, o el ingreso a través de ventilaciones, escotillas o tambuchos abiertos.' },
    { type: 'paragraph', text: 'paso 2' },
    { type: 'paragraph', text: 'Activar las Bombas de Achique' },
    { type: 'paragraph', text: 'Ante la detección de una inundación seria a bordo, lo primero que debe hacerse es activar la bomba de achique eléctrica y, simultáneamente, asignar a uno o más tripulantes la tarea de achicar agua utilizando una bomba manual o baldes.' },
    { type: 'paragraph', text: 'Existe un dicho popular en la náutica que resume bien esta situación:' },
    { type: 'paragraph', text: '"No hay mejor bomba de achique que un marinero asustado con un balde en la mano."' },
    { type: 'paragraph', text: 'Bomba de achique de mamparo, a pedal.' },
    { type: 'paragraph', text: 'La bomba de achique manual es un elemento obligatorio del equipamiento de seguridad, por lo que siempre debe haber al menos una a bordo. A ella puede sumarse una o más bombas automáticas, tanto por comodidad como para asegurar que la embarcación se mantenga seca cuando se encuentra amarrada o desatendida.' },
    { type: 'paragraph', text: 'Debe tenerse en cuenta que una bomba manual de mamparo puede bombear aproximadamente 6 metros cúbicos por hora, mientras que una bomba eléctrica de sentina de caudal medio suele evacuar menos de la mitad de ese volumen.' },
    { type: 'paragraph', text: 'Como último recurso, y en embarcaciones con motor interno, puede desviarse el circuito de refrigeración por agua del motor para que, en lugar de tomar agua del exterior, la aspire desde el interior del barco. Para ello deberá cerrarse la llave de paso de admisión, desconectar el conducto de entrada a la bomba de refrigeración y sumergirlo en la sentina inundada. De este modo puede lograrse un caudal adicional de achique de entre 1 y 4 m³ por hora.' },
    { type: 'paragraph', text: 'paso 3' },
    { type: 'paragraph', text: 'Localizar la Vía de Agua' },
    { type: 'paragraph', text: 'La primera forma de localizar la entrada de agua es realizar una recorrida visual sistemática por el interior de la embarcación.' },
    { type: 'paragraph', text: 'Si no logra identificarla rápidamente, puede deberse a que la vía de agua sea pequeña o se encuentre en un punto poco accesible. En ese caso, intente escuchar el sonido del ingreso de agua o seguir su recorrido hasta llegar al punto de origen.' },
    { type: 'paragraph', text: 'paso 4' },
    { type: 'subtitle', text: 'Controle la Vía de Agua' },
    { type: 'paragraph', text: 'El objetivo principal de este paso es detener por completo el ingreso de agua. No obstante, si ello no fuera posible, deberá buscarse reducir el caudal hasta un nivel que permita mantener la situación bajo control, evacuando tanta o más agua de la que ingresa, hasta poder efectuar una reparación adecuada o regresar a puerto.' },
    { type: 'paragraph', text: 'Si la entrada de agua se origina en una válvula o pasacasco, podrá obturarse utilizando un tapón diseñado para tal fin, ya sea comercial o improvisado. En este último caso, puede emplearse, por ejemplo, un trozo del mango de una escoba envuelto en "duck tape" o un trapo, insertándolo firmemente en el orificio.' },
    { type: 'paragraph', text: 'Si la vía de agua se localiza en un tubo o manguera, como las del circuito de refrigeración del motor, será necesario detener el flujo para realizar una reparación de emergencia. Lo ideal sería reemplazar la manguera, pero si no se dispone del repuesto adecuado, puede bloquearse la abertura con sellador siliconado y reforzarse envolviéndola firmemente con cinta adhesiva. Otra alternativa consiste en cortar el tramo dañado y empalmar los extremos mediante un tubo rígido del diámetro adecuado, fijándolo con abrazaderas o precintos.' },
    { type: 'paragraph', text: 'Las vías de agua abiertas en el casco deberán evaluarse según su tamaño y gravedad.' },
    { type: 'subtitle', text: 'Vías de Agua Sobre la Línea de Flotación' },
    { type: 'paragraph', text: 'Parche atornillado sobre el casco.' },
    { type: 'paragraph', text: 'Cuando la vía de agua lo permite y se dispone de un kit de reparación de casco, es posible construir un parche resistente utilizando fibra de vidrio y resina, suficiente para contener la entrada de agua.' },
    { type: 'paragraph', text: 'Antes de aplicar el parche, debe reducirse el ingreso de agua mediante achique continuo y obturaciones provisorias, limpiando la zona dañada y secándola en la medida de lo posible.' },
    { type: 'paragraph', text: 'La reparación se realiza aplicando varias capas de tela de fibra de vidrio impregnadas en resina, comenzando por las más pequeñas y superponiéndolas progresivamente hasta cubrir holgadamente la zona afectada. Es fundamental presionar el parche contra el casco para eliminar burbujas de aire y asegurar su correcta adhesión, manteniendo dicha presión hasta que la resina comience a endurecer. Para ello puede utilizarse una placa rígida y un puntal improvisado, o incluso la fuerza manual de un tripulante.' },
    { type: 'paragraph', text: 'Una vez endurecida la resina, el parche debe controlarse verificando que el ingreso de agua haya cesado o se haya reducido a un nivel manejable.' },
    { type: 'subtitle', text: 'Vías de Agua Debajo la Línea de Flotación' },
    { type: 'paragraph', text: 'Apuntalamiento de parche sobre el casco.' },
    { type: 'paragraph', text: 'En caso de vías de agua importantes, seguramente deberá actuar en etapas, tratando primero de reducir el flujo de ingreso de agua para luego aplicar alguna reparación de fortuna que termine de cerrarlo.' },
    { type: 'paragraph', text: 'Una técnica efectiva para reducir el ingreso de agua consiste en pasar una vela o toldilla por debajo del casco y sujetarla desde la cubierta. La presión del agua hará que la tela se adhiera al casco, reduciendo el flujo de agua. Asimismo, puede escorarse la embarcación hacia la banda opuesta a la dañada para disminuir la presión hidrostática sobre la zona afectada.' },
    { type: 'paragraph', text: 'Si la vía de agua se encuentra en cubierta, por ejemplo, debido a la rotura de una escotilla, puede tapársela provisionalmente con lona, plástico o una placa rígida, fijándola con cinta adhesiva o tornillos en caso extremo.' },
    { type: 'paragraph', text: 'Este tipo de reparaciones debe considerarse siempre provisorias y destinadas únicamente a estabilizar la situación, y permitir el regreso inmediato a puerto.' },
    { type: 'paragraph', text: 'En ningún caso es recomendable continuar la navegación con una vía de agua reparada provisionalmente.' },
    { type: 'paragraph', text: 'paso 5' },
    { type: 'paragraph', text: 'Asegurar la Provisión de Energía' },
    { type: 'paragraph', text: 'Este paso, si bien es accesorio, resulta de gran importancia.' },
    { type: 'paragraph', text: 'Contar con energía eléctrica durante una emergencia es esencial para mantener la iluminación, las comunicaciones y el funcionamiento de las bombas de achique eléctricas.' },
    { type: 'paragraph', text: 'Por esta razón, deberá asegurarse la carga de las baterías mediante el encendido del motor o cualquier otro sistema de generación disponible. Si existiera riesgo de que las baterías queden sumergidas, deberán retirarse de su compartimiento y trasladarse a un lugar seco y seguro.' },
    { type: 'paragraph', text: 'Cuando, a pesar de las acciones de control de daños, la vía de agua no puede ser contenida y existe riesgo cierto de que la situación evolucione hacia una emergencia mayor, deberá solicitarse asistencia por radio sin demora. La emisión temprana de un mensaje de socorro o urgencia permite alertar a otras embarcaciones y a los servicios de búsqueda y rescate, aumentando significativamente las posibilidades de recibir ayuda oportuna.' },
    { type: 'paragraph', text: 'Si la situación es grave pero aún no implica un peligro inmediato para la vida, se transmitirá un mensaje de PAN PAN, indicando la posición, la naturaleza de la emergencia y la asistencia requerida. En cambio, si la inundación es incontrolable, la embarcación corre peligro inminente de hundimiento o la vida de las personas a bordo está en riesgo, deberá emitirse un mensaje de MAYDAY, siguiendo el procedimiento radiotelefónico establecido, y prepararse simultáneamente para una posible evacuación o abandono de la embarcación.' },
    { type: 'paragraph', text: 'Cabuyería: Tipos de cabos y su aplicación.' },
    { type: 'paragraph', text: 'Técnicas de Fondeo.' },
  ],

  quiz: [
    {
      question: '¿Qué es una vía de agua?',
      options: ['La entrada de agua de lluvia', 'Una entrada no controlada de agua al interior del casco', 'El agua que entra por la escotilla', 'La condensación en el casco'],
      correctAnswer: 1,
      explanation: 'Una vía de agua es cualquier entrada no controlada de agua al interior del casco, que puede comprometer la flotabilidad de la embarcación.'
    },
    {
      question: '¿Cuál es la primera acción ante una vía de agua?',
      options: ['Llamar por radio MAYDAY', 'Localizar la vía de agua y contener la entrada', 'Abandonar el barco', 'Arriar las velas'],
      correctAnswer: 1,
      explanation: 'Lo primero es localizar la vía de agua y contener la entrada usando los medios disponibles (bombas, tapones, colchonetas).'
    },
    {
      question: '¿Qué elementos pueden usarse para taponar una vía de agua?',
      options: ['Solo tapones comerciales', 'Cualquier material disponible: colchonetas, trapos, cuñas de madera, masilla', 'Cemento', 'Solo bombas de achique'],
      correctAnswer: 1,
      explanation: 'Para taponar una vía de agua puede usarse cualquier material disponible: colchonetas, trapos, cuñas de madera, masilla epoxy, etc.'
    },
  ]
};