export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as Chapter } from './Chapter'
export { default as Section } from './Section/Section'
export { default as Topic } from './Topic/Topic'
export { default as Quiz } from './Quiz/Quiz'
export { default as Practice } from './Practice'
