import { Topic } from '@/content/types';

export const topic: Topic = {
  id: 'rigging',
  title: 'La arboladura y la jarcia',
  readingTime: 17,
  audioTime: '15:39',

  content: [
    { type: 'title', text: 'La Arboladura y la Jarcia' },
    { type: 'paragraph', text: 'El término arboladura refiere al conjunto de mástiles, perchas, vergas, botalones y cualquier otro elemento similar, utilizado para montar o sostener el velamen de un buque de vela.' },
    { type: 'paragraph', text: 'Los mástiles o palos se emplazan de forma vertical y tienen por objeto soportar el peso y la fuerza de tracción del velamen, y las perchas, que se disponen perpendicularmente a los mástiles y tienen por función dar soporte horizontal a las velas. Las perchas, a su vez, son un conjunto en el que entran, por ejemplo, las vergas que son los palos que se cuelgan transversalmente en los mástiles de los grandes veleros para sostener las velas cuadras; otro tipo de perchas son el bauprés y el botalón, usados para montar velas por delante de la proa del barco y, por último, la botavara y el tangón, utilizados para sostener la vela mayor y extender la apertura de otras velas de proa, respectivamente.' },
    { type: 'paragraph', text: 'Antiguamente, los palos y perchas eran construidos en madera, a partir de troncos de árboles, y actualmente se los fabrica de aluminio o de materiales sintéticos tales como la fibra de carbono.' },
    { type: 'paragraph', text: 'Los veleros de crucero que vemos en nuestros días cuentan en su gran mayoría con un solo mástil o palo —a esa configuración se la llama aparejo sloop— al que simplemente se lo denomina con esos nombres: mástil o palo. En los barcos que tienen varios mástiles se denomina palo mayor al más alto, generalmente ubicado en el centro del barco, palo de mesana al que se encuentra a popa —o sea, hacia atrás— del palo mayor, y palo de trinquete al que se ubica a proa del palo mayor.' },
    { type: 'paragraph', text: 'Cada uno de esos palos cuenta con una verga que, como ya explicamos, es el nombre que se le da a los palos colgados horizontalmente desde un mástil, y que se utilizan para sostener diferentes tipos de velas.' },
    { type: 'paragraph', text: 'Los veleros que vemos a diario llevan un tipo de percha particular, denominada botavara, que se proyecta desde el mástil hacia la popa. La pieza que une la botavara con el mástil se llama gancera, que es un herraje que le permite a la botavara pivotear en todos los sentidos para acompañar el movimiento de la vela que lleva montada. El tangón es otro tipo de percha móvil que, cuando se la necesita, se coloca tomada al mástil, pero orientada hacia la proa en este caso, y que, como dijimos, se utiliza para obligar a determinados tipos de velas de proa a mantenerse abiertas, a fin de que ofrezcan mayor cantidad de superficie al viento.' },
    { type: 'paragraph', text: 'En algunos veleros, generalmente en los de menores esloras, el mástil se apoya sobre la carlinga, que es una base metálica o de madera robusta que va fijada en la cubierta sobre la posición del bao de la cuaderna maestra —es la cuaderna principal del barco, donde éste tiene su mayor manga—. La carlinga permite mover el palo hacia proa o popa a fin de adelantar o retrasar la posición relativa del eje de fuerzas del velamen sobre la embarcación. En algunos casos, para aportar resistencia vertical, se agrega un pie de amigo, que consiste en un refuerzo vertical que va en el interior del barco, apoyado sobre la quilla y llega hasta la base del bao sobre el cual está instalada la carlinga y el palo.' },
    { type: 'paragraph', text: 'En las demás embarcaciones el mástil pasa a través de la fogonadura — que es un orificio practicado para tal efecto en la cubierta— y se apoya sobre la quilla. El espacio que queda entre el mástil y el borde de la fogonadura se rellena con cuñas de madera o goma para mantener el palo estabilizado en su posición, y sobre ese relleno se aplica luego algún material sellador para evitar que el agua pase hacia el interior de la cabina.' },
    { type: 'paragraph', text: 'En los grandes barcos de vela —la Fragata ARA Libertad es un ejemplo de ellos— cada mástil consta de dos o tres secciones encastradas entre sí para lograr la altura requerida.' },
    { type: 'paragraph', text: 'La sección principal, llamada palo macho, se apoya en la quilla elevándose por sobre la cubierta. Sobre este se encastra el mastelero, que luego continúa en el mastelerillo.' },
    { type: 'paragraph', text: 'Por supuesto, para no confundirse, cada sección lleva de "apellido" el nombre del mástil al que corresponde; por ejemplo, palo macho de mayor, mastelero de mesana o mastelerillo de trinquete.' },
    { type: 'paragraph', text: 'A su vez, cada uno de esos mástiles lleva varias vergas cruzadas de las que se cuelgan las velas. Y como corresponde, cada verga toma el nombre de la vela que porta.' },
    { type: 'paragraph', text: 'En la proa, inclinado hacia adelante, se ubica otro palo llamado bauprés que se extiende agregando el botalón.' },
    { type: 'title', text: 'La Jarcia' },
    { type: 'paragraph', text: 'La jarcia, por su parte, es el término que se utiliza para denominar al conjunto de elementos, cabos y cables, utilizados para sostener la arboladura —el aparejo de mástiles— y maniobrar las perchas —la botavara, por ejemplo— y las velas.' },
    { type: 'paragraph', text: 'La jarcia se clasifica a su vez en dos grandes grupos, según sea su aplicación.' },
    { type: 'title', text: 'La Jarcia Fija' },
    { type: 'paragraph', text: 'La jarcia fija, también llamada jarcia firme o jarcia muerta, es la que agrupa a los cabos y cables encargados de dar sostén y resistencia lateral y longitudinal a los mástiles, y se la llama así: fija, pues una vez montada no requiere ser removida ni necesita de mayores ajustes durante la navegación.' },
    { type: 'paragraph', text: 'Dentro de este grupo encontramos a los stays y los obenques, que consisten en cables metálicos —generalmente de acero inoxidable—. Los primeros se usan para sostener el mástil desde la proa y la popa, por lo que se los llaman respectivamente stay proel y stay popel, mientras que los segundos hacen el mismo trabajo manteniendo el palo amurado a estribor y babor. Tanto los stays como los obenques se afirman a piezas fijadas firmemente en el casco y el palo.' },
    { type: 'paragraph', text: 'El extremo superior del stay proel se sujeta al tope —o cerca del tope— del mástil, y el inferior al caperol, que es una pieza que va fijada sobre la roda. Algunos veleros tienen además un stay adicional en proa, llamado baby stay, que parte de un punto medio del mástil y termina en una landa en la sección media de la cubierta, a proa, y que además de aportarle al mástil un punto adicional de resistencia estructural, sirve para curvarlo hacia adelante, cuando es necesario hacerlo.' },
    { type: 'paragraph', text: 'El extremo superior del stay popel también está tomado al tope del palo, pero la punta inferior puede terminar en un aparejo llamado pata de gallo que distribuye la tensión en las aletas del barco o bien en una única landa fijada al codaste. El stay popel también puede ser tensado para curvar el extremo superior del mástil hacia popa.' },
    { type: 'paragraph', text: 'Los obenques también se afirman en una o más landas fijadas a cada lado del barco —hacia las bandas— y se toman a distintas alturas del mástil para darle a éste el requerido soporte y resistencia lateral en toda su extensión. Así pueden encontrarse varios pares de obenques que se nombran según la altura del palo en la que terminan. En el caso del velero de la figura siguiente, que tiene dos pares de obenques se llamará obenque bajo —de estribor o de babor, según corresponda— al que termina en la mitad del palo y obenque alto al que termina en su tope. Los obenques que llegan a alturas por arriba del par más bajo se los separa del palo mediante crucetas, que son un tipo de brazo extensor, que se coloca transversalmente en el mástil, y que permite mejorar el trabajo de soporte estructural provisto por los obenques.' },
    { type: 'paragraph', text: 'Cuando el barco se escora —es decir, se inclina— producto de la fuerza ejercida por el viento sobre el velamen, son los obenques del lado de barlovento —del lado del que proviene el viento— los que deben soportar esa fuerza manteniendo el mástil "amurado" —es decir, sostenido— a la banda, mientras que los obenques del lado de sotavento —del lado por el que sale el viento— se encuentran flojos, sin carga.' },
    { type: 'paragraph', text: 'En algunos veleros se agregan burdas, que son cables o cabos que parten de un punto en el tercio superior del mástil y que se llevan hacia las aletas del barco, y que al tensarlas le agregan resistencia al palo.' },
    { type: 'paragraph', text: 'Las burdas son aparejos que pueden tensarse a demanda, según la amura en la que se navega, porque solo cumple su función la burda de barlovento —la de sotavento se deja suelta para permitir el paso de la botavara y de la vela mayor—.' },
    { type: 'paragraph', text: 'Su misión principal es aportarle sostén y controlar la flexión del palo, especialmente en su tercio superior, y mantenerlo firme cuando el aparejo es muy alto o cuando no existe un baby stay o crucetas con retención suficiente hacia popa. Esto es típico en muchos veleros de regata, en mástiles de aparejo fraccionado, o en embarcaciones con tangón y spinnaker, donde las cargas hacia adelante pueden llegar a ser enormes.' },
    { type: 'title', text: 'La Jarcia Móvil' },
    { type: 'paragraph', text: 'La jarcia móvil —o jarcia de labor o jarcia de trabajo— en cambio, refiere a las drizas, las escotas y el resto de los cabos utilizados a bordo para maniobrar las perchas y el velamen.' },
    { type: 'paragraph', text: 'Las drizas son los cabos utilizados para izar las velas y se las identifica por el nombre de la vela con la cual trabajan; por ejemplo, driza de vela mayor, driza de spinnaker o drizas de velas de proa. Las escotas, en cambio, se utilizan para ajustar el ángulo de apertura de las velas respectos de la línea de incidencia del viento.' },
    { type: 'paragraph', text: 'La vela mayor de un velero utiliza una escota montada en una polea cuya función es reducir la fuerza requerida para poder operar esa vela cuando se encuentra portando —cargada de viento—. El extremo superior del aparejo de polea se une al penol de la botavara —es decir, a la punta libre de esa percha, donde a su vez se encuentra fijado el puño de escota de la vela mayor— y el inferior se fija al carro del traveller, que permite desplazar el aparejo hacia una banda o la otra. Las velas de proa utilizan un par de escotas tendidas sobre cada una de las bandas, que son dirigidas hacia el cockpit mediante un conjunto de desvíos y guías especiales.' },
    { type: 'paragraph', text: 'Además de las drizas y escotas, existen otros cabos que forman parte de la jarcia de labor, tales como las brazas que son los cabos que se utilizan para manejar lateralmente el penol —el extremo— del tangón cuando se utilizan velas como el spinnaker; otros son los amantillos y contramantillos que son los encargados de sostener el penol de las perchas —es decir, los extremos de la botavara y el tangón— desde arriba y abajo respectivamente.' },
    { type: 'paragraph', text: 'El vang también forma parte de la jarcia móvil, y cuya función es evitar que la botavara se eleve más de los deseado.' },
    { type: 'paragraph', text: 'Podemos completar el grupo agregando a los amantes que son aquellos cabos que se utilizan para sujetar cualquier elemento de una percha. El caso más usual a bordo de un velero son los amantes de rizos usados para sujetar los pliegues de la vela rizada a la botavara.' },
    { type: 'title', text: 'Elementos de Maniobra' },
    { type: 'paragraph', text: 'En veleros chicos las escotas, las drizas y demás cabos de la jarcia móvil pueden ser operados a mano sin tener que hacer grandes esfuerzos, sin embargo, a medida que aumenta el porte del barco, las cargas ejercidas por esos cabos crece geométricamente, siendo ya no solo difícil sino además peligroso tratarlos a mano, sin la ayuda de herramientas adecuadas tales como los molinetes, que son un tipo particular de cabrestante dispuesto de forma vertical y cuya función es justamente reducir la cantidad de fuerza necesaria para operar una escota, una driza o cualquier otro cabo a bordo.' },
    { type: 'paragraph', text: 'Los molinetes se operan manualmente, enrollando el cabo a su alrededor en sentido horario, y cazando —tirando— del chicote. Cuando la fuerza de la mano no es suficiente para lograr cazar el cabo, se utiliza una manija que trabaja como palanca del molinete. Otra opción más cómoda —pero también más cara— consiste en utilizar molinetes ayudados por motores eléctricos.' },
    { type: 'paragraph', text: 'Resulta que los nautas, y especialmente los veleristas suelen ser muy respetuosos y celosos de su argot, llegando casi al fundamentalismo.' },
    { type: 'paragraph', text: 'Tan es así que el uso de palabras tales como "soga" o "cuerda" asociadas a un barco les suena en sus oídos como la peor de las blasfemias. Para esta gente, las "sogas" se utilizan para colgar la ropa recién lavada y las "cuerdas" son esas cosas finitas que van en las guitarras.' },
    { type: 'paragraph', text: 'Nosotros, los navegantes bien hablados, usamos las palabras "cabo" y "cable".' },
    { type: 'paragraph', text: 'La primera para referirnos a los hechos de fibras flexibles sintéticas o textiles, y la segunda para hablar de los metálicos.' },
    { type: 'paragraph', text: 'Ya que estamos le explico que la frase "cazar un cabo" no significa salir a correr a un soldado con una escopeta, sino "tirar o jalar de un cabo", para tensarlo, y que "filar un cabo" quiere decir lo contrario, es decir "soltar un cabo, para aflojar su tensión".' },
    { type: 'paragraph', text: 'Para hacer firme —es decir, para sujetar o atar— los cabos se utilizan mordazas, stoppers y cornamusas.' },
    { type: 'paragraph', text: 'Las mordazas y los stoppers son herrajes que permiten sujetar firmemente un cabo y trabarlo mediante un mecanismo de presión que impide que se suelten. Las mordazas sujetan los cabos mordiéndolos entre dos ruedas excéntricas dentadas que se abren al cazar el cabo y que se cierran, aprisionándolo, cuando el cabo intenta ceder a la tensión. Los stoppers cumplen una tarea similar, pero sujetando el cabo mediante un mecanismo de pinza y palanca mucho más robusto, destinado a operar con cabos que soportan fuerzas mayores, tales como las drizas. Las cornamusas son otro tipo de herraje macizo formado por dos extremos o cuernos —de allí viene su nombre— que data de los orígenes de la náutica y al cual se atan los cabos para hacerlos firmes.' },
    { type: 'paragraph', text: 'Los motones, que son equivalentes a las roldanas de uso terrestre, y que sirven para cambiar la dirección de un cabo. Los hay de diferentes formas, tamaños y combinaciones, y según sea su destino adoptan distintos nombres. Por ejemplo, y además del tradicional motón, podemos nombrar a las pastecas que son los motones que pueden abrirse por un lado para enhebrar un cabo fácilmente, y los desvíos que son los que se afirman a algún punto para encaminar o cambiar la dirección de un cabo.' },
    { type: 'paragraph', text: 'Finalmente, los portaespías son otro tipo de herraje que se utiliza para guiar aquellos cabos que deben mantener una posición específica, como los de amarre o de fondeo. Existen dos tipos de portaespías, los abiertos y los cerrados; en los primeros el cabo se coloca manualmente sobre la apertura para que quede guiado, mientras que en los segundos debe ser enhebrado.' }
  ],

  quiz: [
    {
      question: '¿Qué es la jarcia fija?',
      options: ['La que se mueve', 'La que mantiene los mástiles fijos', 'La de las velas', 'La de anclas'],
      correctAnswer: 1,
      explanation: 'La jarcia fija son los cabos que mantienen los mástiles en su lugar y no se mueven.'
    },
    {
      question: '¿Qué son los obenques?',
      options: ['Cabos de las velas', 'Cables que sostienen el mástil lateralmente', 'Parte del timón', 'Tipo de vela'],
      correctAnswer: 1,
      explanation: 'Los obenques son cables metálicos que sostienen el mástil desde los costados del barco.'
    },
    {
      question: '¿Qué es la botavara?',
      options: ['Un tipo de vela', 'Una percha que sostiene la base de la vela mayor', 'El timón', 'Un cable de acero'],
      correctAnswer: 1,
      explanation: 'La botavara es una percha que se proyecta desde el mástil hacia la popa para sostener la vela mayor.'
    },
    {
      question: '¿Qué es un molinete?',
      options: ['Un tipo de vela', 'Un cabo', 'Una herramienta para reducir la fuerza necesaria en cabos', 'El timón'],
      correctAnswer: 2,
      explanation: 'El molinete es un tipo de cabrestante que reduce la fuerza necesaria para operar cabos.'
    }
  ]
};
